apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: code-code-egress-trust-bundle
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: code-code-egress-root-ca
        key: tls.crt
  target:
    configMap:
      key: ca-certificates.crt
    namespaceSelector:
      matchLabels:
        egress.platform.code-code.internal/trust-bundle: "enabled"
