apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: code-code

resources:
  - configmap.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: code-code/platform-support-service
    newTag: 0.0.0
