// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: observability/v1/observability.proto

package observabilityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObservabilityMetricKind identifies the instrument kind of one metric.
type ObservabilityMetricKind int32

const (
	ObservabilityMetricKind_OBSERVABILITY_METRIC_KIND_UNSPECIFIED ObservabilityMetricKind = 0
	ObservabilityMetricKind_OBSERVABILITY_METRIC_KIND_GAUGE       ObservabilityMetricKind = 1
	ObservabilityMetricKind_OBSERVABILITY_METRIC_KIND_COUNTER     ObservabilityMetricKind = 2
	ObservabilityMetricKind_OBSERVABILITY_METRIC_KIND_HISTOGRAM   ObservabilityMetricKind = 3
)

// Enum value maps for ObservabilityMetricKind.
var (
	ObservabilityMetricKind_name = map[int32]string{
		0: "OBSERVABILITY_METRIC_KIND_UNSPECIFIED",
		1: "OBSERVABILITY_METRIC_KIND_GAUGE",
		2: "OBSERVABILITY_METRIC_KIND_COUNTER",
		3: "OBSERVABILITY_METRIC_KIND_HISTOGRAM",
	}
	ObservabilityMetricKind_value = map[string]int32{
		"OBSERVABILITY_METRIC_KIND_UNSPECIFIED": 0,
		"OBSERVABILITY_METRIC_KIND_GAUGE":       1,
		"OBSERVABILITY_METRIC_KIND_COUNTER":     2,
		"OBSERVABILITY_METRIC_KIND_HISTOGRAM":   3,
	}
)

func (x ObservabilityMetricKind) Enum() *ObservabilityMetricKind {
	p := new(ObservabilityMetricKind)
	*p = x
	return p
}

func (x ObservabilityMetricKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObservabilityMetricKind) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[0].Descriptor()
}

func (ObservabilityMetricKind) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[0]
}

func (x ObservabilityMetricKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObservabilityMetricKind.Descriptor instead.
func (ObservabilityMetricKind) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{0}
}

// ObservabilityMetricCategory identifies the business category of one metric.
type ObservabilityMetricCategory int32

const (
	ObservabilityMetricCategory_OBSERVABILITY_METRIC_CATEGORY_UNSPECIFIED ObservabilityMetricCategory = 0
	ObservabilityMetricCategory_OBSERVABILITY_METRIC_CATEGORY_QUOTA       ObservabilityMetricCategory = 1
	ObservabilityMetricCategory_OBSERVABILITY_METRIC_CATEGORY_USAGE       ObservabilityMetricCategory = 2
	ObservabilityMetricCategory_OBSERVABILITY_METRIC_CATEGORY_RATE_LIMIT  ObservabilityMetricCategory = 3
)

// Enum value maps for ObservabilityMetricCategory.
var (
	ObservabilityMetricCategory_name = map[int32]string{
		0: "OBSERVABILITY_METRIC_CATEGORY_UNSPECIFIED",
		1: "OBSERVABILITY_METRIC_CATEGORY_QUOTA",
		2: "OBSERVABILITY_METRIC_CATEGORY_USAGE",
		3: "OBSERVABILITY_METRIC_CATEGORY_RATE_LIMIT",
	}
	ObservabilityMetricCategory_value = map[string]int32{
		"OBSERVABILITY_METRIC_CATEGORY_UNSPECIFIED": 0,
		"OBSERVABILITY_METRIC_CATEGORY_QUOTA":       1,
		"OBSERVABILITY_METRIC_CATEGORY_USAGE":       2,
		"OBSERVABILITY_METRIC_CATEGORY_RATE_LIMIT":  3,
	}
)

func (x ObservabilityMetricCategory) Enum() *ObservabilityMetricCategory {
	p := new(ObservabilityMetricCategory)
	*p = x
	return p
}

func (x ObservabilityMetricCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObservabilityMetricCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[1].Descriptor()
}

func (ObservabilityMetricCategory) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[1]
}

func (x ObservabilityMetricCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObservabilityMetricCategory.Descriptor instead.
func (ObservabilityMetricCategory) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{1}
}

// ObservabilityAttributeRequirementLevel identifies how strongly one attribute
// is expected to be present.
type ObservabilityAttributeRequirementLevel int32

const (
	ObservabilityAttributeRequirementLevel_OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_UNSPECIFIED ObservabilityAttributeRequirementLevel = 0
	ObservabilityAttributeRequirementLevel_OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_REQUIRED    ObservabilityAttributeRequirementLevel = 1
	ObservabilityAttributeRequirementLevel_OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_RECOMMENDED ObservabilityAttributeRequirementLevel = 2
)

// Enum value maps for ObservabilityAttributeRequirementLevel.
var (
	ObservabilityAttributeRequirementLevel_name = map[int32]string{
		0: "OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_UNSPECIFIED",
		1: "OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_REQUIRED",
		2: "OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_RECOMMENDED",
	}
	ObservabilityAttributeRequirementLevel_value = map[string]int32{
		"OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_UNSPECIFIED": 0,
		"OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_REQUIRED":    1,
		"OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_RECOMMENDED": 2,
	}
)

func (x ObservabilityAttributeRequirementLevel) Enum() *ObservabilityAttributeRequirementLevel {
	p := new(ObservabilityAttributeRequirementLevel)
	*p = x
	return p
}

func (x ObservabilityAttributeRequirementLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObservabilityAttributeRequirementLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[2].Descriptor()
}

func (ObservabilityAttributeRequirementLevel) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[2]
}

func (x ObservabilityAttributeRequirementLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObservabilityAttributeRequirementLevel.Descriptor instead.
func (ObservabilityAttributeRequirementLevel) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{2}
}

// MetricQueryLanguage identifies the query language used by one metric query.
type MetricQueryLanguage int32

const (
	MetricQueryLanguage_METRIC_QUERY_LANGUAGE_UNSPECIFIED MetricQueryLanguage = 0
	MetricQueryLanguage_METRIC_QUERY_LANGUAGE_PROMQL      MetricQueryLanguage = 1
)

// Enum value maps for MetricQueryLanguage.
var (
	MetricQueryLanguage_name = map[int32]string{
		0: "METRIC_QUERY_LANGUAGE_UNSPECIFIED",
		1: "METRIC_QUERY_LANGUAGE_PROMQL",
	}
	MetricQueryLanguage_value = map[string]int32{
		"METRIC_QUERY_LANGUAGE_UNSPECIFIED": 0,
		"METRIC_QUERY_LANGUAGE_PROMQL":      1,
	}
)

func (x MetricQueryLanguage) Enum() *MetricQueryLanguage {
	p := new(MetricQueryLanguage)
	*p = x
	return p
}

func (x MetricQueryLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricQueryLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[3].Descriptor()
}

func (MetricQueryLanguage) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[3]
}

func (x MetricQueryLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricQueryLanguage.Descriptor instead.
func (MetricQueryLanguage) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{3}
}

// MetricQueryResultKind identifies the expected result shape of one query.
type MetricQueryResultKind int32

const (
	MetricQueryResultKind_METRIC_QUERY_RESULT_KIND_UNSPECIFIED  MetricQueryResultKind = 0
	MetricQueryResultKind_METRIC_QUERY_RESULT_KIND_SCALAR       MetricQueryResultKind = 1
	MetricQueryResultKind_METRIC_QUERY_RESULT_KIND_VECTOR       MetricQueryResultKind = 2
	MetricQueryResultKind_METRIC_QUERY_RESULT_KIND_RANGE_VECTOR MetricQueryResultKind = 3
)

// Enum value maps for MetricQueryResultKind.
var (
	MetricQueryResultKind_name = map[int32]string{
		0: "METRIC_QUERY_RESULT_KIND_UNSPECIFIED",
		1: "METRIC_QUERY_RESULT_KIND_SCALAR",
		2: "METRIC_QUERY_RESULT_KIND_VECTOR",
		3: "METRIC_QUERY_RESULT_KIND_RANGE_VECTOR",
	}
	MetricQueryResultKind_value = map[string]int32{
		"METRIC_QUERY_RESULT_KIND_UNSPECIFIED":  0,
		"METRIC_QUERY_RESULT_KIND_SCALAR":       1,
		"METRIC_QUERY_RESULT_KIND_VECTOR":       2,
		"METRIC_QUERY_RESULT_KIND_RANGE_VECTOR": 3,
	}
)

func (x MetricQueryResultKind) Enum() *MetricQueryResultKind {
	p := new(MetricQueryResultKind)
	*p = x
	return p
}

func (x MetricQueryResultKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricQueryResultKind) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[4].Descriptor()
}

func (MetricQueryResultKind) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[4]
}

func (x MetricQueryResultKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricQueryResultKind.Descriptor instead.
func (MetricQueryResultKind) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{4}
}

// AvailabilitySubjectKind identifies the entity type judged by one profile.
type AvailabilitySubjectKind int32

const (
	AvailabilitySubjectKind_AVAILABILITY_SUBJECT_KIND_UNSPECIFIED AvailabilitySubjectKind = 0
	AvailabilitySubjectKind_AVAILABILITY_SUBJECT_KIND_MODEL       AvailabilitySubjectKind = 1
)

// Enum value maps for AvailabilitySubjectKind.
var (
	AvailabilitySubjectKind_name = map[int32]string{
		0: "AVAILABILITY_SUBJECT_KIND_UNSPECIFIED",
		1: "AVAILABILITY_SUBJECT_KIND_MODEL",
	}
	AvailabilitySubjectKind_value = map[string]int32{
		"AVAILABILITY_SUBJECT_KIND_UNSPECIFIED": 0,
		"AVAILABILITY_SUBJECT_KIND_MODEL":       1,
	}
)

func (x AvailabilitySubjectKind) Enum() *AvailabilitySubjectKind {
	p := new(AvailabilitySubjectKind)
	*p = x
	return p
}

func (x AvailabilitySubjectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailabilitySubjectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[5].Descriptor()
}

func (AvailabilitySubjectKind) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[5]
}

func (x AvailabilitySubjectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailabilitySubjectKind.Descriptor instead.
func (AvailabilitySubjectKind) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{5}
}

// AvailabilityState identifies the derived availability state of one subject.
type AvailabilityState int32

const (
	AvailabilityState_AVAILABILITY_STATE_UNSPECIFIED AvailabilityState = 0
	AvailabilityState_AVAILABILITY_STATE_AVAILABLE   AvailabilityState = 1
	AvailabilityState_AVAILABILITY_STATE_DEGRADED    AvailabilityState = 2
	AvailabilityState_AVAILABILITY_STATE_UNAVAILABLE AvailabilityState = 3
)

// Enum value maps for AvailabilityState.
var (
	AvailabilityState_name = map[int32]string{
		0: "AVAILABILITY_STATE_UNSPECIFIED",
		1: "AVAILABILITY_STATE_AVAILABLE",
		2: "AVAILABILITY_STATE_DEGRADED",
		3: "AVAILABILITY_STATE_UNAVAILABLE",
	}
	AvailabilityState_value = map[string]int32{
		"AVAILABILITY_STATE_UNSPECIFIED": 0,
		"AVAILABILITY_STATE_AVAILABLE":   1,
		"AVAILABILITY_STATE_DEGRADED":    2,
		"AVAILABILITY_STATE_UNAVAILABLE": 3,
	}
)

func (x AvailabilityState) Enum() *AvailabilityState {
	p := new(AvailabilityState)
	*p = x
	return p
}

func (x AvailabilityState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailabilityState) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[6].Descriptor()
}

func (AvailabilityState) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[6]
}

func (x AvailabilityState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailabilityState.Descriptor instead.
func (AvailabilityState) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{6}
}

// ComparisonOperator identifies how one query result should be compared to a
// threshold.
type ComparisonOperator int32

const (
	ComparisonOperator_COMPARISON_OPERATOR_UNSPECIFIED ComparisonOperator = 0
	ComparisonOperator_COMPARISON_OPERATOR_LT          ComparisonOperator = 1
	ComparisonOperator_COMPARISON_OPERATOR_LTE         ComparisonOperator = 2
	ComparisonOperator_COMPARISON_OPERATOR_GT          ComparisonOperator = 3
	ComparisonOperator_COMPARISON_OPERATOR_GTE         ComparisonOperator = 4
	ComparisonOperator_COMPARISON_OPERATOR_EQ          ComparisonOperator = 5
	ComparisonOperator_COMPARISON_OPERATOR_NEQ         ComparisonOperator = 6
)

// Enum value maps for ComparisonOperator.
var (
	ComparisonOperator_name = map[int32]string{
		0: "COMPARISON_OPERATOR_UNSPECIFIED",
		1: "COMPARISON_OPERATOR_LT",
		2: "COMPARISON_OPERATOR_LTE",
		3: "COMPARISON_OPERATOR_GT",
		4: "COMPARISON_OPERATOR_GTE",
		5: "COMPARISON_OPERATOR_EQ",
		6: "COMPARISON_OPERATOR_NEQ",
	}
	ComparisonOperator_value = map[string]int32{
		"COMPARISON_OPERATOR_UNSPECIFIED": 0,
		"COMPARISON_OPERATOR_LT":          1,
		"COMPARISON_OPERATOR_LTE":         2,
		"COMPARISON_OPERATOR_GT":          3,
		"COMPARISON_OPERATOR_GTE":         4,
		"COMPARISON_OPERATOR_EQ":          5,
		"COMPARISON_OPERATOR_NEQ":         6,
	}
)

func (x ComparisonOperator) Enum() *ComparisonOperator {
	p := new(ComparisonOperator)
	*p = x
	return p
}

func (x ComparisonOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[7].Descriptor()
}

func (ComparisonOperator) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[7]
}

func (x ComparisonOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonOperator.Descriptor instead.
func (ComparisonOperator) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{7}
}

// HeaderValueType identifies how one header value should be parsed.
type HeaderValueType int32

const (
	HeaderValueType_HEADER_VALUE_TYPE_UNSPECIFIED       HeaderValueType = 0
	HeaderValueType_HEADER_VALUE_TYPE_INT64             HeaderValueType = 1
	HeaderValueType_HEADER_VALUE_TYPE_DOUBLE            HeaderValueType = 2
	HeaderValueType_HEADER_VALUE_TYPE_DURATION_SECONDS  HeaderValueType = 3
	HeaderValueType_HEADER_VALUE_TYPE_UNIX_SECONDS      HeaderValueType = 4
	HeaderValueType_HEADER_VALUE_TYPE_RFC3339_TIMESTAMP HeaderValueType = 5
)

// Enum value maps for HeaderValueType.
var (
	HeaderValueType_name = map[int32]string{
		0: "HEADER_VALUE_TYPE_UNSPECIFIED",
		1: "HEADER_VALUE_TYPE_INT64",
		2: "HEADER_VALUE_TYPE_DOUBLE",
		3: "HEADER_VALUE_TYPE_DURATION_SECONDS",
		4: "HEADER_VALUE_TYPE_UNIX_SECONDS",
		5: "HEADER_VALUE_TYPE_RFC3339_TIMESTAMP",
	}
	HeaderValueType_value = map[string]int32{
		"HEADER_VALUE_TYPE_UNSPECIFIED":       0,
		"HEADER_VALUE_TYPE_INT64":             1,
		"HEADER_VALUE_TYPE_DOUBLE":            2,
		"HEADER_VALUE_TYPE_DURATION_SECONDS":  3,
		"HEADER_VALUE_TYPE_UNIX_SECONDS":      4,
		"HEADER_VALUE_TYPE_RFC3339_TIMESTAMP": 5,
	}
)

func (x HeaderValueType) Enum() *HeaderValueType {
	p := new(HeaderValueType)
	*p = x
	return p
}

func (x HeaderValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeaderValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_observability_v1_observability_proto_enumTypes[8].Descriptor()
}

func (HeaderValueType) Type() protoreflect.EnumType {
	return &file_observability_v1_observability_proto_enumTypes[8]
}

func (x HeaderValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeaderValueType.Descriptor instead.
func (HeaderValueType) EnumDescriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{8}
}

// ObservabilityCapability describes a reusable observability capability block
// hosted by one support surface.
type ObservabilityCapability struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Profiles      []*ObservabilityProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservabilityCapability) Reset() {
	*x = ObservabilityCapability{}
	mi := &file_observability_v1_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservabilityCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservabilityCapability) ProtoMessage() {}

func (x *ObservabilityCapability) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservabilityCapability.ProtoReflect.Descriptor instead.
func (*ObservabilityCapability) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{0}
}

func (x *ObservabilityCapability) GetProfiles() []*ObservabilityProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// ObservabilityProfile describes one coherent metric collection contract.
type ObservabilityProfile struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ProfileId   string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional binding to host-package sub-surfaces. Semantics are defined by
	// the host package. Empty means host-wide.
	ScopeIds []string               `protobuf:"bytes,3,rep,name=scope_ids,json=scopeIds,proto3" json:"scope_ids,omitempty"`
	Metrics  []*ObservabilityMetric `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Types that are valid to be assigned to Collection:
	//
	//	*ObservabilityProfile_ActiveQuery
	//	*ObservabilityProfile_ResponseHeaders
	Collection isObservabilityProfile_Collection `protobuf_oneof:"collection"`
	// Stable metric queries consumed by availability judgment.
	MetricQueries []*MetricQuery `protobuf:"bytes,7,rep,name=metric_queries,json=metricQueries,proto3" json:"metric_queries,omitempty"`
	// Subject-level availability judgment rules derived from declared queries.
	AvailabilityJudgment *AvailabilityJudgment `protobuf:"bytes,8,opt,name=availability_judgment,json=availabilityJudgment,proto3" json:"availability_judgment,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ObservabilityProfile) Reset() {
	*x = ObservabilityProfile{}
	mi := &file_observability_v1_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservabilityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservabilityProfile) ProtoMessage() {}

func (x *ObservabilityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservabilityProfile.ProtoReflect.Descriptor instead.
func (*ObservabilityProfile) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{1}
}

func (x *ObservabilityProfile) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ObservabilityProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ObservabilityProfile) GetScopeIds() []string {
	if x != nil {
		return x.ScopeIds
	}
	return nil
}

func (x *ObservabilityProfile) GetMetrics() []*ObservabilityMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ObservabilityProfile) GetCollection() isObservabilityProfile_Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *ObservabilityProfile) GetActiveQuery() *ActiveQueryCollection {
	if x != nil {
		if x, ok := x.Collection.(*ObservabilityProfile_ActiveQuery); ok {
			return x.ActiveQuery
		}
	}
	return nil
}

func (x *ObservabilityProfile) GetResponseHeaders() *ResponseHeaderCollection {
	if x != nil {
		if x, ok := x.Collection.(*ObservabilityProfile_ResponseHeaders); ok {
			return x.ResponseHeaders
		}
	}
	return nil
}

func (x *ObservabilityProfile) GetMetricQueries() []*MetricQuery {
	if x != nil {
		return x.MetricQueries
	}
	return nil
}

func (x *ObservabilityProfile) GetAvailabilityJudgment() *AvailabilityJudgment {
	if x != nil {
		return x.AvailabilityJudgment
	}
	return nil
}

type isObservabilityProfile_Collection interface {
	isObservabilityProfile_Collection()
}

type ObservabilityProfile_ActiveQuery struct {
	ActiveQuery *ActiveQueryCollection `protobuf:"bytes,5,opt,name=active_query,json=activeQuery,proto3,oneof"`
}

type ObservabilityProfile_ResponseHeaders struct {
	ResponseHeaders *ResponseHeaderCollection `protobuf:"bytes,6,opt,name=response_headers,json=responseHeaders,proto3,oneof"`
}

func (*ObservabilityProfile_ActiveQuery) isObservabilityProfile_Collection() {}

func (*ObservabilityProfile_ResponseHeaders) isObservabilityProfile_Collection() {}

// ObservabilityMetric describes one OTel-style metric contract.
type ObservabilityMetric struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Name          string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Unit          string                          `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Kind          ObservabilityMetricKind         `protobuf:"varint,4,opt,name=kind,proto3,enum=observability.v1.ObservabilityMetricKind" json:"kind,omitempty"`
	Category      ObservabilityMetricCategory     `protobuf:"varint,5,opt,name=category,proto3,enum=observability.v1.ObservabilityMetricCategory" json:"category,omitempty"`
	Attributes    []*ObservabilityMetricAttribute `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservabilityMetric) Reset() {
	*x = ObservabilityMetric{}
	mi := &file_observability_v1_observability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservabilityMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservabilityMetric) ProtoMessage() {}

func (x *ObservabilityMetric) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservabilityMetric.ProtoReflect.Descriptor instead.
func (*ObservabilityMetric) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{2}
}

func (x *ObservabilityMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObservabilityMetric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ObservabilityMetric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ObservabilityMetric) GetKind() ObservabilityMetricKind {
	if x != nil {
		return x.Kind
	}
	return ObservabilityMetricKind_OBSERVABILITY_METRIC_KIND_UNSPECIFIED
}

func (x *ObservabilityMetric) GetCategory() ObservabilityMetricCategory {
	if x != nil {
		return x.Category
	}
	return ObservabilityMetricCategory_OBSERVABILITY_METRIC_CATEGORY_UNSPECIFIED
}

func (x *ObservabilityMetric) GetAttributes() []*ObservabilityMetricAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ObservabilityMetricAttribute describes one metric attribute contract.
type ObservabilityMetricAttribute struct {
	state            protoimpl.MessageState                 `protogen:"open.v1"`
	Name             string                                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RequirementLevel ObservabilityAttributeRequirementLevel `protobuf:"varint,3,opt,name=requirement_level,json=requirementLevel,proto3,enum=observability.v1.ObservabilityAttributeRequirementLevel" json:"requirement_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ObservabilityMetricAttribute) Reset() {
	*x = ObservabilityMetricAttribute{}
	mi := &file_observability_v1_observability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservabilityMetricAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservabilityMetricAttribute) ProtoMessage() {}

func (x *ObservabilityMetricAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservabilityMetricAttribute.ProtoReflect.Descriptor instead.
func (*ObservabilityMetricAttribute) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{3}
}

func (x *ObservabilityMetricAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObservabilityMetricAttribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ObservabilityMetricAttribute) GetRequirementLevel() ObservabilityAttributeRequirementLevel {
	if x != nil {
		return x.RequirementLevel
	}
	return ObservabilityAttributeRequirementLevel_OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_UNSPECIFIED
}

// ActiveQueryCollection declares an active query collection policy.
type ActiveQueryCollection struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MinimumPollInterval *durationpb.Duration   `protobuf:"bytes,1,opt,name=minimum_poll_interval,json=minimumPollInterval,proto3" json:"minimum_poll_interval,omitempty"`
	// Dynamic parameters required by the collector when surface auth is not
	// sufficient. Actual values are supplied by the host provider config.
	DynamicParameters []*DynamicParameterDefinition `protobuf:"bytes,2,rep,name=dynamic_parameters,json=dynamicParameters,proto3" json:"dynamic_parameters,omitempty"`
	// Optional collector implementation key resolved by the host package.
	// Empty means host-default active query execution.
	CollectorId   string `protobuf:"bytes,3,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveQueryCollection) Reset() {
	*x = ActiveQueryCollection{}
	mi := &file_observability_v1_observability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveQueryCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveQueryCollection) ProtoMessage() {}

func (x *ActiveQueryCollection) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveQueryCollection.ProtoReflect.Descriptor instead.
func (*ActiveQueryCollection) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{4}
}

func (x *ActiveQueryCollection) GetMinimumPollInterval() *durationpb.Duration {
	if x != nil {
		return x.MinimumPollInterval
	}
	return nil
}

func (x *ActiveQueryCollection) GetDynamicParameters() []*DynamicParameterDefinition {
	if x != nil {
		return x.DynamicParameters
	}
	return nil
}

func (x *ActiveQueryCollection) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

// DynamicParameterDefinition describes one dynamically supplied parameter.
type DynamicParameterDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterId   string                 `protobuf:"bytes,1,opt,name=parameter_id,json=parameterId,proto3" json:"parameter_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Secret        bool                   `protobuf:"varint,5,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicParameterDefinition) Reset() {
	*x = DynamicParameterDefinition{}
	mi := &file_observability_v1_observability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicParameterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicParameterDefinition) ProtoMessage() {}

func (x *DynamicParameterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicParameterDefinition.ProtoReflect.Descriptor instead.
func (*DynamicParameterDefinition) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{5}
}

func (x *DynamicParameterDefinition) GetParameterId() string {
	if x != nil {
		return x.ParameterId
	}
	return ""
}

func (x *DynamicParameterDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DynamicParameterDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DynamicParameterDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *DynamicParameterDefinition) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

// ResponseHeaderCollection declares how response headers map to metrics.
type ResponseHeaderCollection struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HeaderMetricMappings []*HeaderMetricMapping `protobuf:"bytes,1,rep,name=header_metric_mappings,json=headerMetricMappings,proto3" json:"header_metric_mappings,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResponseHeaderCollection) Reset() {
	*x = ResponseHeaderCollection{}
	mi := &file_observability_v1_observability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeaderCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeaderCollection) ProtoMessage() {}

func (x *ResponseHeaderCollection) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeaderCollection.ProtoReflect.Descriptor instead.
func (*ResponseHeaderCollection) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseHeaderCollection) GetHeaderMetricMappings() []*HeaderMetricMapping {
	if x != nil {
		return x.HeaderMetricMappings
	}
	return nil
}

// HeaderMetricMapping maps one response header to one declared metric.
type HeaderMetricMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeaderName    string                 `protobuf:"bytes,1,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	ValueType     HeaderValueType        `protobuf:"varint,3,opt,name=value_type,json=valueType,proto3,enum=observability.v1.HeaderValueType" json:"value_type,omitempty"`
	Labels        []*HeaderMetricLabel   `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderMetricMapping) Reset() {
	*x = HeaderMetricMapping{}
	mi := &file_observability_v1_observability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderMetricMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderMetricMapping) ProtoMessage() {}

func (x *HeaderMetricMapping) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderMetricMapping.ProtoReflect.Descriptor instead.
func (*HeaderMetricMapping) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{7}
}

func (x *HeaderMetricMapping) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

func (x *HeaderMetricMapping) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *HeaderMetricMapping) GetValueType() HeaderValueType {
	if x != nil {
		return x.ValueType
	}
	return HeaderValueType_HEADER_VALUE_TYPE_UNSPECIFIED
}

func (x *HeaderMetricMapping) GetLabels() []*HeaderMetricLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

// HeaderMetricLabel binds one fixed label value to one header-derived metric
// sample.
type HeaderMetricLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderMetricLabel) Reset() {
	*x = HeaderMetricLabel{}
	mi := &file_observability_v1_observability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderMetricLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderMetricLabel) ProtoMessage() {}

func (x *HeaderMetricLabel) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderMetricLabel.ProtoReflect.Descriptor instead.
func (*HeaderMetricLabel) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{8}
}

func (x *HeaderMetricLabel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeaderMetricLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MetricQuery describes one stable metrics query statement.
type MetricQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Language      MetricQueryLanguage    `protobuf:"varint,3,opt,name=language,proto3,enum=observability.v1.MetricQueryLanguage" json:"language,omitempty"`
	Statement     string                 `protobuf:"bytes,4,opt,name=statement,proto3" json:"statement,omitempty"`
	MetricNames   []string               `protobuf:"bytes,5,rep,name=metric_names,json=metricNames,proto3" json:"metric_names,omitempty"`
	ResultKind    MetricQueryResultKind  `protobuf:"varint,6,opt,name=result_kind,json=resultKind,proto3,enum=observability.v1.MetricQueryResultKind" json:"result_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricQuery) Reset() {
	*x = MetricQuery{}
	mi := &file_observability_v1_observability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricQuery) ProtoMessage() {}

func (x *MetricQuery) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricQuery.ProtoReflect.Descriptor instead.
func (*MetricQuery) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{9}
}

func (x *MetricQuery) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *MetricQuery) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MetricQuery) GetLanguage() MetricQueryLanguage {
	if x != nil {
		return x.Language
	}
	return MetricQueryLanguage_METRIC_QUERY_LANGUAGE_UNSPECIFIED
}

func (x *MetricQuery) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *MetricQuery) GetMetricNames() []string {
	if x != nil {
		return x.MetricNames
	}
	return nil
}

func (x *MetricQuery) GetResultKind() MetricQueryResultKind {
	if x != nil {
		return x.ResultKind
	}
	return MetricQueryResultKind_METRIC_QUERY_RESULT_KIND_UNSPECIFIED
}

// AvailabilityJudgment describes how one subject's availability is derived
// from declared metric queries.
type AvailabilityJudgment struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	SubjectKind     AvailabilitySubjectKind `protobuf:"varint,1,opt,name=subject_kind,json=subjectKind,proto3,enum=observability.v1.AvailabilitySubjectKind" json:"subject_kind,omitempty"`
	SubjectLabelKey string                  `protobuf:"bytes,2,opt,name=subject_label_key,json=subjectLabelKey,proto3" json:"subject_label_key,omitempty"`
	QueryIds        []string                `protobuf:"bytes,3,rep,name=query_ids,json=queryIds,proto3" json:"query_ids,omitempty"`
	Rules           []*AvailabilityRule     `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AvailabilityJudgment) Reset() {
	*x = AvailabilityJudgment{}
	mi := &file_observability_v1_observability_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityJudgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityJudgment) ProtoMessage() {}

func (x *AvailabilityJudgment) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityJudgment.ProtoReflect.Descriptor instead.
func (*AvailabilityJudgment) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{10}
}

func (x *AvailabilityJudgment) GetSubjectKind() AvailabilitySubjectKind {
	if x != nil {
		return x.SubjectKind
	}
	return AvailabilitySubjectKind_AVAILABILITY_SUBJECT_KIND_UNSPECIFIED
}

func (x *AvailabilityJudgment) GetSubjectLabelKey() string {
	if x != nil {
		return x.SubjectLabelKey
	}
	return ""
}

func (x *AvailabilityJudgment) GetQueryIds() []string {
	if x != nil {
		return x.QueryIds
	}
	return nil
}

func (x *AvailabilityJudgment) GetRules() []*AvailabilityRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// AvailabilityRule maps one predicate set to one derived availability state.
type AvailabilityRule struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RuleId        string                   `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	DisplayName   string                   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AllOf         []*AvailabilityPredicate `protobuf:"bytes,3,rep,name=all_of,json=allOf,proto3" json:"all_of,omitempty"`
	State         AvailabilityState        `protobuf:"varint,4,opt,name=state,proto3,enum=observability.v1.AvailabilityState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityRule) Reset() {
	*x = AvailabilityRule{}
	mi := &file_observability_v1_observability_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRule) ProtoMessage() {}

func (x *AvailabilityRule) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRule.ProtoReflect.Descriptor instead.
func (*AvailabilityRule) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{11}
}

func (x *AvailabilityRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AvailabilityRule) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AvailabilityRule) GetAllOf() []*AvailabilityPredicate {
	if x != nil {
		return x.AllOf
	}
	return nil
}

func (x *AvailabilityRule) GetState() AvailabilityState {
	if x != nil {
		return x.State
	}
	return AvailabilityState_AVAILABILITY_STATE_UNSPECIFIED
}

// AvailabilityPredicate compares one query result against one threshold.
type AvailabilityPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Operator      ComparisonOperator     `protobuf:"varint,2,opt,name=operator,proto3,enum=observability.v1.ComparisonOperator" json:"operator,omitempty"`
	Threshold     float64                `protobuf:"fixed64,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityPredicate) Reset() {
	*x = AvailabilityPredicate{}
	mi := &file_observability_v1_observability_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityPredicate) ProtoMessage() {}

func (x *AvailabilityPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_observability_v1_observability_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityPredicate.ProtoReflect.Descriptor instead.
func (*AvailabilityPredicate) Descriptor() ([]byte, []int) {
	return file_observability_v1_observability_proto_rawDescGZIP(), []int{12}
}

func (x *AvailabilityPredicate) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *AvailabilityPredicate) GetOperator() ComparisonOperator {
	if x != nil {
		return x.Operator
	}
	return ComparisonOperator_COMPARISON_OPERATOR_UNSPECIFIED
}

func (x *AvailabilityPredicate) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

var File_observability_v1_observability_proto protoreflect.FileDescriptor

const file_observability_v1_observability_proto_rawDesc = "" +
	"\n" +
	"$observability/v1/observability.proto\x12\x10observability.v1\x1a\x1egoogle/protobuf/duration.proto\"]\n" +
	"\x17ObservabilityCapability\x12B\n" +
	"\bprofiles\x18\x01 \x03(\v2&.observability.v1.ObservabilityProfileR\bprofiles\"\x8e\x04\n" +
	"\x14ObservabilityProfile\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tscope_ids\x18\x03 \x03(\tR\bscopeIds\x12?\n" +
	"\ametrics\x18\x04 \x03(\v2%.observability.v1.ObservabilityMetricR\ametrics\x12L\n" +
	"\factive_query\x18\x05 \x01(\v2'.observability.v1.ActiveQueryCollectionH\x00R\vactiveQuery\x12W\n" +
	"\x10response_headers\x18\x06 \x01(\v2*.observability.v1.ResponseHeaderCollectionH\x00R\x0fresponseHeaders\x12D\n" +
	"\x0emetric_queries\x18\a \x03(\v2\x1d.observability.v1.MetricQueryR\rmetricQueries\x12[\n" +
	"\x15availability_judgment\x18\b \x01(\v2&.observability.v1.AvailabilityJudgmentR\x14availabilityJudgmentB\f\n" +
	"\n" +
	"collection\"\xb9\x02\n" +
	"\x13ObservabilityMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12=\n" +
	"\x04kind\x18\x04 \x01(\x0e2).observability.v1.ObservabilityMetricKindR\x04kind\x12I\n" +
	"\bcategory\x18\x05 \x01(\x0e2-.observability.v1.ObservabilityMetricCategoryR\bcategory\x12N\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2..observability.v1.ObservabilityMetricAttributeR\n" +
	"attributes\"\xbb\x01\n" +
	"\x1cObservabilityMetricAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12e\n" +
	"\x11requirement_level\x18\x03 \x01(\x0e28.observability.v1.ObservabilityAttributeRequirementLevelR\x10requirementLevel\"\xe6\x01\n" +
	"\x15ActiveQueryCollection\x12M\n" +
	"\x15minimum_poll_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x13minimumPollInterval\x12[\n" +
	"\x12dynamic_parameters\x18\x02 \x03(\v2,.observability.v1.DynamicParameterDefinitionR\x11dynamicParameters\x12!\n" +
	"\fcollector_id\x18\x03 \x01(\tR\vcollectorId\"\xb8\x01\n" +
	"\x1aDynamicParameterDefinition\x12!\n" +
	"\fparameter_id\x18\x01 \x01(\tR\vparameterId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x16\n" +
	"\x06secret\x18\x05 \x01(\bR\x06secret\"w\n" +
	"\x18ResponseHeaderCollection\x12[\n" +
	"\x16header_metric_mappings\x18\x01 \x03(\v2%.observability.v1.HeaderMetricMappingR\x14headerMetricMappings\"\xd6\x01\n" +
	"\x13HeaderMetricMapping\x12\x1f\n" +
	"\vheader_name\x18\x01 \x01(\tR\n" +
	"headerName\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12@\n" +
	"\n" +
	"value_type\x18\x03 \x01(\x0e2!.observability.v1.HeaderValueTypeR\tvalueType\x12;\n" +
	"\x06labels\x18\x04 \x03(\v2#.observability.v1.HeaderMetricLabelR\x06labels\"=\n" +
	"\x11HeaderMetricLabel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x99\x02\n" +
	"\vMetricQuery\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12A\n" +
	"\blanguage\x18\x03 \x01(\x0e2%.observability.v1.MetricQueryLanguageR\blanguage\x12\x1c\n" +
	"\tstatement\x18\x04 \x01(\tR\tstatement\x12!\n" +
	"\fmetric_names\x18\x05 \x03(\tR\vmetricNames\x12H\n" +
	"\vresult_kind\x18\x06 \x01(\x0e2'.observability.v1.MetricQueryResultKindR\n" +
	"resultKind\"\xe7\x01\n" +
	"\x14AvailabilityJudgment\x12L\n" +
	"\fsubject_kind\x18\x01 \x01(\x0e2).observability.v1.AvailabilitySubjectKindR\vsubjectKind\x12*\n" +
	"\x11subject_label_key\x18\x02 \x01(\tR\x0fsubjectLabelKey\x12\x1b\n" +
	"\tquery_ids\x18\x03 \x03(\tR\bqueryIds\x128\n" +
	"\x05rules\x18\x04 \x03(\v2\".observability.v1.AvailabilityRuleR\x05rules\"\xc9\x01\n" +
	"\x10AvailabilityRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12>\n" +
	"\x06all_of\x18\x03 \x03(\v2'.observability.v1.AvailabilityPredicateR\x05allOf\x129\n" +
	"\x05state\x18\x04 \x01(\x0e2#.observability.v1.AvailabilityStateR\x05state\"\x92\x01\n" +
	"\x15AvailabilityPredicate\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12@\n" +
	"\boperator\x18\x02 \x01(\x0e2$.observability.v1.ComparisonOperatorR\boperator\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x01R\tthreshold*\xb9\x01\n" +
	"\x17ObservabilityMetricKind\x12)\n" +
	"%OBSERVABILITY_METRIC_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fOBSERVABILITY_METRIC_KIND_GAUGE\x10\x01\x12%\n" +
	"!OBSERVABILITY_METRIC_KIND_COUNTER\x10\x02\x12'\n" +
	"#OBSERVABILITY_METRIC_KIND_HISTOGRAM\x10\x03*\xcc\x01\n" +
	"\x1bObservabilityMetricCategory\x12-\n" +
	")OBSERVABILITY_METRIC_CATEGORY_UNSPECIFIED\x10\x00\x12'\n" +
	"#OBSERVABILITY_METRIC_CATEGORY_QUOTA\x10\x01\x12'\n" +
	"#OBSERVABILITY_METRIC_CATEGORY_USAGE\x10\x02\x12,\n" +
	"(OBSERVABILITY_METRIC_CATEGORY_RATE_LIMIT\x10\x03*\xd6\x01\n" +
	"&ObservabilityAttributeRequirementLevel\x129\n" +
	"5OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_UNSPECIFIED\x10\x00\x126\n" +
	"2OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_REQUIRED\x10\x01\x129\n" +
	"5OBSERVABILITY_ATTRIBUTE_REQUIREMENT_LEVEL_RECOMMENDED\x10\x02*^\n" +
	"\x13MetricQueryLanguage\x12%\n" +
	"!METRIC_QUERY_LANGUAGE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMETRIC_QUERY_LANGUAGE_PROMQL\x10\x01*\xb6\x01\n" +
	"\x15MetricQueryResultKind\x12(\n" +
	"$METRIC_QUERY_RESULT_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fMETRIC_QUERY_RESULT_KIND_SCALAR\x10\x01\x12#\n" +
	"\x1fMETRIC_QUERY_RESULT_KIND_VECTOR\x10\x02\x12)\n" +
	"%METRIC_QUERY_RESULT_KIND_RANGE_VECTOR\x10\x03*i\n" +
	"\x17AvailabilitySubjectKind\x12)\n" +
	"%AVAILABILITY_SUBJECT_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fAVAILABILITY_SUBJECT_KIND_MODEL\x10\x01*\x9e\x01\n" +
	"\x11AvailabilityState\x12\"\n" +
	"\x1eAVAILABILITY_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAVAILABILITY_STATE_AVAILABLE\x10\x01\x12\x1f\n" +
	"\x1bAVAILABILITY_STATE_DEGRADED\x10\x02\x12\"\n" +
	"\x1eAVAILABILITY_STATE_UNAVAILABLE\x10\x03*\xe4\x01\n" +
	"\x12ComparisonOperator\x12#\n" +
	"\x1fCOMPARISON_OPERATOR_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMPARISON_OPERATOR_LT\x10\x01\x12\x1b\n" +
	"\x17COMPARISON_OPERATOR_LTE\x10\x02\x12\x1a\n" +
	"\x16COMPARISON_OPERATOR_GT\x10\x03\x12\x1b\n" +
	"\x17COMPARISON_OPERATOR_GTE\x10\x04\x12\x1a\n" +
	"\x16COMPARISON_OPERATOR_EQ\x10\x05\x12\x1b\n" +
	"\x17COMPARISON_OPERATOR_NEQ\x10\x06*\xe4\x01\n" +
	"\x0fHeaderValueType\x12!\n" +
	"\x1dHEADER_VALUE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17HEADER_VALUE_TYPE_INT64\x10\x01\x12\x1c\n" +
	"\x18HEADER_VALUE_TYPE_DOUBLE\x10\x02\x12&\n" +
	"\"HEADER_VALUE_TYPE_DURATION_SECONDS\x10\x03\x12\"\n" +
	"\x1eHEADER_VALUE_TYPE_UNIX_SECONDS\x10\x04\x12'\n" +
	"#HEADER_VALUE_TYPE_RFC3339_TIMESTAMP\x10\x05BAZ?code-code.internal/go-contract/observability/v1;observabilityv1b\x06proto3"

var (
	file_observability_v1_observability_proto_rawDescOnce sync.Once
	file_observability_v1_observability_proto_rawDescData []byte
)

func file_observability_v1_observability_proto_rawDescGZIP() []byte {
	file_observability_v1_observability_proto_rawDescOnce.Do(func() {
		file_observability_v1_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observability_v1_observability_proto_rawDesc), len(file_observability_v1_observability_proto_rawDesc)))
	})
	return file_observability_v1_observability_proto_rawDescData
}

var file_observability_v1_observability_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_observability_v1_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_observability_v1_observability_proto_goTypes = []any{
	(ObservabilityMetricKind)(0),                // 0: observability.v1.ObservabilityMetricKind
	(ObservabilityMetricCategory)(0),            // 1: observability.v1.ObservabilityMetricCategory
	(ObservabilityAttributeRequirementLevel)(0), // 2: observability.v1.ObservabilityAttributeRequirementLevel
	(MetricQueryLanguage)(0),                    // 3: observability.v1.MetricQueryLanguage
	(MetricQueryResultKind)(0),                  // 4: observability.v1.MetricQueryResultKind
	(AvailabilitySubjectKind)(0),                // 5: observability.v1.AvailabilitySubjectKind
	(AvailabilityState)(0),                      // 6: observability.v1.AvailabilityState
	(ComparisonOperator)(0),                     // 7: observability.v1.ComparisonOperator
	(HeaderValueType)(0),                        // 8: observability.v1.HeaderValueType
	(*ObservabilityCapability)(nil),             // 9: observability.v1.ObservabilityCapability
	(*ObservabilityProfile)(nil),                // 10: observability.v1.ObservabilityProfile
	(*ObservabilityMetric)(nil),                 // 11: observability.v1.ObservabilityMetric
	(*ObservabilityMetricAttribute)(nil),        // 12: observability.v1.ObservabilityMetricAttribute
	(*ActiveQueryCollection)(nil),               // 13: observability.v1.ActiveQueryCollection
	(*DynamicParameterDefinition)(nil),          // 14: observability.v1.DynamicParameterDefinition
	(*ResponseHeaderCollection)(nil),            // 15: observability.v1.ResponseHeaderCollection
	(*HeaderMetricMapping)(nil),                 // 16: observability.v1.HeaderMetricMapping
	(*HeaderMetricLabel)(nil),                   // 17: observability.v1.HeaderMetricLabel
	(*MetricQuery)(nil),                         // 18: observability.v1.MetricQuery
	(*AvailabilityJudgment)(nil),                // 19: observability.v1.AvailabilityJudgment
	(*AvailabilityRule)(nil),                    // 20: observability.v1.AvailabilityRule
	(*AvailabilityPredicate)(nil),               // 21: observability.v1.AvailabilityPredicate
	(*durationpb.Duration)(nil),                 // 22: google.protobuf.Duration
}
var file_observability_v1_observability_proto_depIdxs = []int32{
	10, // 0: observability.v1.ObservabilityCapability.profiles:type_name -> observability.v1.ObservabilityProfile
	11, // 1: observability.v1.ObservabilityProfile.metrics:type_name -> observability.v1.ObservabilityMetric
	13, // 2: observability.v1.ObservabilityProfile.active_query:type_name -> observability.v1.ActiveQueryCollection
	15, // 3: observability.v1.ObservabilityProfile.response_headers:type_name -> observability.v1.ResponseHeaderCollection
	18, // 4: observability.v1.ObservabilityProfile.metric_queries:type_name -> observability.v1.MetricQuery
	19, // 5: observability.v1.ObservabilityProfile.availability_judgment:type_name -> observability.v1.AvailabilityJudgment
	0,  // 6: observability.v1.ObservabilityMetric.kind:type_name -> observability.v1.ObservabilityMetricKind
	1,  // 7: observability.v1.ObservabilityMetric.category:type_name -> observability.v1.ObservabilityMetricCategory
	12, // 8: observability.v1.ObservabilityMetric.attributes:type_name -> observability.v1.ObservabilityMetricAttribute
	2,  // 9: observability.v1.ObservabilityMetricAttribute.requirement_level:type_name -> observability.v1.ObservabilityAttributeRequirementLevel
	22, // 10: observability.v1.ActiveQueryCollection.minimum_poll_interval:type_name -> google.protobuf.Duration
	14, // 11: observability.v1.ActiveQueryCollection.dynamic_parameters:type_name -> observability.v1.DynamicParameterDefinition
	16, // 12: observability.v1.ResponseHeaderCollection.header_metric_mappings:type_name -> observability.v1.HeaderMetricMapping
	8,  // 13: observability.v1.HeaderMetricMapping.value_type:type_name -> observability.v1.HeaderValueType
	17, // 14: observability.v1.HeaderMetricMapping.labels:type_name -> observability.v1.HeaderMetricLabel
	3,  // 15: observability.v1.MetricQuery.language:type_name -> observability.v1.MetricQueryLanguage
	4,  // 16: observability.v1.MetricQuery.result_kind:type_name -> observability.v1.MetricQueryResultKind
	5,  // 17: observability.v1.AvailabilityJudgment.subject_kind:type_name -> observability.v1.AvailabilitySubjectKind
	20, // 18: observability.v1.AvailabilityJudgment.rules:type_name -> observability.v1.AvailabilityRule
	21, // 19: observability.v1.AvailabilityRule.all_of:type_name -> observability.v1.AvailabilityPredicate
	6,  // 20: observability.v1.AvailabilityRule.state:type_name -> observability.v1.AvailabilityState
	7,  // 21: observability.v1.AvailabilityPredicate.operator:type_name -> observability.v1.ComparisonOperator
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_observability_v1_observability_proto_init() }
func file_observability_v1_observability_proto_init() {
	if File_observability_v1_observability_proto != nil {
		return
	}
	file_observability_v1_observability_proto_msgTypes[1].OneofWrappers = []any{
		(*ObservabilityProfile_ActiveQuery)(nil),
		(*ObservabilityProfile_ResponseHeaders)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observability_v1_observability_proto_rawDesc), len(file_observability_v1_observability_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_observability_v1_observability_proto_goTypes,
		DependencyIndexes: file_observability_v1_observability_proto_depIdxs,
		EnumInfos:         file_observability_v1_observability_proto_enumTypes,
		MessageInfos:      file_observability_v1_observability_proto_msgTypes,
	}.Build()
	File_observability_v1_observability_proto = out.File
	file_observability_v1_observability_proto_goTypes = nil
	file_observability_v1_observability_proto_depIdxs = nil
}
