apiVersion: v1
kind: Service
metadata:
  name: platform-network-service
spec:
  selector:
    app.kubernetes.io/name: platform-network-service
  ports:
    - name: grpc
      port: 8081
      targetPort: grpc
