// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_INFO        NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_SUCCESS     NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_WARNING     NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_FAILURE     NotificationType = 4
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_INFO",
		2: "NOTIFICATION_TYPE_SUCCESS",
		3: "NOTIFICATION_TYPE_WARNING",
		4: "NOTIFICATION_TYPE_FAILURE",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"NOTIFICATION_TYPE_INFO":        1,
		"NOTIFICATION_TYPE_SUCCESS":     2,
		"NOTIFICATION_TYPE_WARNING":     3,
		"NOTIFICATION_TYPE_FAILURE":     4,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_platform_notification_v1_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_platform_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationFormat int32

const (
	NotificationFormat_NOTIFICATION_FORMAT_UNSPECIFIED NotificationFormat = 0
	NotificationFormat_NOTIFICATION_FORMAT_MARKDOWN    NotificationFormat = 1
	NotificationFormat_NOTIFICATION_FORMAT_TEXT        NotificationFormat = 2
	NotificationFormat_NOTIFICATION_FORMAT_HTML        NotificationFormat = 3
)

// Enum value maps for NotificationFormat.
var (
	NotificationFormat_name = map[int32]string{
		0: "NOTIFICATION_FORMAT_UNSPECIFIED",
		1: "NOTIFICATION_FORMAT_MARKDOWN",
		2: "NOTIFICATION_FORMAT_TEXT",
		3: "NOTIFICATION_FORMAT_HTML",
	}
	NotificationFormat_value = map[string]int32{
		"NOTIFICATION_FORMAT_UNSPECIFIED": 0,
		"NOTIFICATION_FORMAT_MARKDOWN":    1,
		"NOTIFICATION_FORMAT_TEXT":        2,
		"NOTIFICATION_FORMAT_HTML":        3,
	}
)

func (x NotificationFormat) Enum() *NotificationFormat {
	p := new(NotificationFormat)
	*p = x
	return p
}

func (x NotificationFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_notification_v1_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationFormat) Type() protoreflect.EnumType {
	return &file_platform_notification_v1_notification_proto_enumTypes[1]
}

func (x NotificationFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationFormat.Descriptor instead.
func (NotificationFormat) EnumDescriptor() ([]byte, []int) {
	return file_platform_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

type NotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Type          NotificationType       `protobuf:"varint,4,opt,name=type,proto3,enum=platform.notification.v1.NotificationType" json:"type,omitempty"`
	Format        NotificationFormat     `protobuf:"varint,5,opt,name=format,proto3,enum=platform.notification.v1.NotificationFormat" json:"format,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_platform_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_platform_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationRequest) GetFormat() NotificationFormat {
	if x != nil {
		return x.Format
	}
	return NotificationFormat_NOTIFICATION_FORMAT_UNSPECIFIED
}

func (x *NotificationRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// InboundMessageEvent carries one verified inbound provider callback.
type InboundMessageEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Provider   string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*InboundMessageEvent_Wecom
	Payload       isInboundMessageEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessageEvent) Reset() {
	*x = InboundMessageEvent{}
	mi := &file_platform_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessageEvent) ProtoMessage() {}

func (x *InboundMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_platform_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessageEvent.ProtoReflect.Descriptor instead.
func (*InboundMessageEvent) Descriptor() ([]byte, []int) {
	return file_platform_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *InboundMessageEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *InboundMessageEvent) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *InboundMessageEvent) GetPayload() isInboundMessageEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InboundMessageEvent) GetWecom() *WeComInboundMessage {
	if x != nil {
		if x, ok := x.Payload.(*InboundMessageEvent_Wecom); ok {
			return x.Wecom
		}
	}
	return nil
}

type isInboundMessageEvent_Payload interface {
	isInboundMessageEvent_Payload()
}

type InboundMessageEvent_Wecom struct {
	Wecom *WeComInboundMessage `protobuf:"bytes,10,opt,name=wecom,proto3,oneof"`
}

func (*InboundMessageEvent_Wecom) isInboundMessageEvent_Payload() {}

// WeComInboundMessage carries one decrypted Enterprise WeChat callback message.
type WeComInboundMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ReceiveId     string                 `protobuf:"bytes,3,opt,name=receive_id,json=receiveId,proto3" json:"receive_id,omitempty"`
	MessageXml    string                 `protobuf:"bytes,4,opt,name=message_xml,json=messageXml,proto3" json:"message_xml,omitempty"`
	Message       *structpb.Struct       `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeComInboundMessage) Reset() {
	*x = WeComInboundMessage{}
	mi := &file_platform_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeComInboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeComInboundMessage) ProtoMessage() {}

func (x *WeComInboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_platform_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeComInboundMessage.ProtoReflect.Descriptor instead.
func (*WeComInboundMessage) Descriptor() ([]byte, []int) {
	return file_platform_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *WeComInboundMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *WeComInboundMessage) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *WeComInboundMessage) GetReceiveId() string {
	if x != nil {
		return x.ReceiveId
	}
	return ""
}

func (x *WeComInboundMessage) GetMessageXml() string {
	if x != nil {
		return x.MessageXml
	}
	return ""
}

func (x *WeComInboundMessage) GetMessage() *structpb.Struct {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_platform_notification_v1_notification_proto protoreflect.FileDescriptor

const file_platform_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"+platform/notification/v1/notification.proto\x12\x18platform.notification.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\x13NotificationRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12>\n" +
	"\x04type\x18\x04 \x01(\x0e2*.platform.notification.v1.NotificationTypeR\x04type\x12D\n" +
	"\x06format\x18\x05 \x01(\x0e2,.platform.notification.v1.NotificationFormatR\x06format\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xc0\x01\n" +
	"\x13InboundMessageEvent\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12;\n" +
	"\vreceived_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12E\n" +
	"\x05wecom\x18\n" +
	" \x01(\v2-.platform.notification.v1.WeComInboundMessageH\x00R\x05wecomB\t\n" +
	"\apayload\"\xbc\x01\n" +
	"\x13WeComInboundMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"receive_id\x18\x03 \x01(\tR\treceiveId\x12\x1f\n" +
	"\vmessage_xml\x18\x04 \x01(\tR\n" +
	"messageXml\x121\n" +
	"\amessage\x18\x05 \x01(\v2\x17.google.protobuf.StructR\amessage*\xae\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_INFO\x10\x01\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_SUCCESS\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_WARNING\x10\x03\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_FAILURE\x10\x04*\x97\x01\n" +
	"\x12NotificationFormat\x12#\n" +
	"\x1fNOTIFICATION_FORMAT_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cNOTIFICATION_FORMAT_MARKDOWN\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_FORMAT_TEXT\x10\x02\x12\x1c\n" +
	"\x18NOTIFICATION_FORMAT_HTML\x10\x03BHZFcode-code.internal/go-contract/platform/notification/v1;notificationv1b\x06proto3"

var (
	file_platform_notification_v1_notification_proto_rawDescOnce sync.Once
	file_platform_notification_v1_notification_proto_rawDescData []byte
)

func file_platform_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_platform_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_platform_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_notification_v1_notification_proto_rawDesc), len(file_platform_notification_v1_notification_proto_rawDesc)))
	})
	return file_platform_notification_v1_notification_proto_rawDescData
}

var file_platform_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_platform_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_platform_notification_v1_notification_proto_goTypes = []any{
	(NotificationType)(0),         // 0: platform.notification.v1.NotificationType
	(NotificationFormat)(0),       // 1: platform.notification.v1.NotificationFormat
	(*NotificationRequest)(nil),   // 2: platform.notification.v1.NotificationRequest
	(*InboundMessageEvent)(nil),   // 3: platform.notification.v1.InboundMessageEvent
	(*WeComInboundMessage)(nil),   // 4: platform.notification.v1.WeComInboundMessage
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
}
var file_platform_notification_v1_notification_proto_depIdxs = []int32{
	0, // 0: platform.notification.v1.NotificationRequest.type:type_name -> platform.notification.v1.NotificationType
	1, // 1: platform.notification.v1.NotificationRequest.format:type_name -> platform.notification.v1.NotificationFormat
	5, // 2: platform.notification.v1.NotificationRequest.occurred_at:type_name -> google.protobuf.Timestamp
	5, // 3: platform.notification.v1.InboundMessageEvent.received_at:type_name -> google.protobuf.Timestamp
	4, // 4: platform.notification.v1.InboundMessageEvent.wecom:type_name -> platform.notification.v1.WeComInboundMessage
	6, // 5: platform.notification.v1.WeComInboundMessage.message:type_name -> google.protobuf.Struct
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_platform_notification_v1_notification_proto_init() }
func file_platform_notification_v1_notification_proto_init() {
	if File_platform_notification_v1_notification_proto != nil {
		return
	}
	file_platform_notification_v1_notification_proto_msgTypes[1].OneofWrappers = []any{
		(*InboundMessageEvent_Wecom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_notification_v1_notification_proto_rawDesc), len(file_platform_notification_v1_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_platform_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_platform_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_platform_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_platform_notification_v1_notification_proto = out.File
	file_platform_notification_v1_notification_proto_goTypes = nil
	file_platform_notification_v1_notification_proto_depIdxs = nil
}
