// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/agent_run/v1/agent_run.proto

package agentrunv1

import (
	v1 "code-code.internal/go-contract/agent/core/v1"
	v13 "code-code.internal/go-contract/agent/result/v1"
	v12 "code-code.internal/go-contract/platform/condition/v1"
	v11 "code-code.internal/go-contract/provider/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentRunPrepareJobRunType identifies when one prepare job should run.
type AgentRunPrepareJobRunType int32

const (
	AgentRunPrepareJobRunType_AGENT_RUN_PREPARE_JOB_RUN_TYPE_UNSPECIFIED AgentRunPrepareJobRunType = 0
	AgentRunPrepareJobRunType_AGENT_RUN_PREPARE_JOB_RUN_TYPE_INIT        AgentRunPrepareJobRunType = 1
	AgentRunPrepareJobRunType_AGENT_RUN_PREPARE_JOB_RUN_TYPE_PER_RUN     AgentRunPrepareJobRunType = 2
	AgentRunPrepareJobRunType_AGENT_RUN_PREPARE_JOB_RUN_TYPE_ON_CHANGED  AgentRunPrepareJobRunType = 3
)

// Enum value maps for AgentRunPrepareJobRunType.
var (
	AgentRunPrepareJobRunType_name = map[int32]string{
		0: "AGENT_RUN_PREPARE_JOB_RUN_TYPE_UNSPECIFIED",
		1: "AGENT_RUN_PREPARE_JOB_RUN_TYPE_INIT",
		2: "AGENT_RUN_PREPARE_JOB_RUN_TYPE_PER_RUN",
		3: "AGENT_RUN_PREPARE_JOB_RUN_TYPE_ON_CHANGED",
	}
	AgentRunPrepareJobRunType_value = map[string]int32{
		"AGENT_RUN_PREPARE_JOB_RUN_TYPE_UNSPECIFIED": 0,
		"AGENT_RUN_PREPARE_JOB_RUN_TYPE_INIT":        1,
		"AGENT_RUN_PREPARE_JOB_RUN_TYPE_PER_RUN":     2,
		"AGENT_RUN_PREPARE_JOB_RUN_TYPE_ON_CHANGED":  3,
	}
)

func (x AgentRunPrepareJobRunType) Enum() *AgentRunPrepareJobRunType {
	p := new(AgentRunPrepareJobRunType)
	*p = x
	return p
}

func (x AgentRunPrepareJobRunType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRunPrepareJobRunType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_agent_run_v1_agent_run_proto_enumTypes[0].Descriptor()
}

func (AgentRunPrepareJobRunType) Type() protoreflect.EnumType {
	return &file_platform_agent_run_v1_agent_run_proto_enumTypes[0]
}

func (x AgentRunPrepareJobRunType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRunPrepareJobRunType.Descriptor instead.
func (AgentRunPrepareJobRunType) EnumDescriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{0}
}

// AgentRunPrepareJobPhase describes the observed lifecycle phase of one prepare job.
type AgentRunPrepareJobPhase int32

const (
	AgentRunPrepareJobPhase_AGENT_RUN_PREPARE_JOB_PHASE_UNSPECIFIED AgentRunPrepareJobPhase = 0
	AgentRunPrepareJobPhase_AGENT_RUN_PREPARE_JOB_PHASE_PENDING     AgentRunPrepareJobPhase = 1
	AgentRunPrepareJobPhase_AGENT_RUN_PREPARE_JOB_PHASE_SKIPPED     AgentRunPrepareJobPhase = 2
	AgentRunPrepareJobPhase_AGENT_RUN_PREPARE_JOB_PHASE_RUNNING     AgentRunPrepareJobPhase = 3
	AgentRunPrepareJobPhase_AGENT_RUN_PREPARE_JOB_PHASE_SUCCEEDED   AgentRunPrepareJobPhase = 4
	AgentRunPrepareJobPhase_AGENT_RUN_PREPARE_JOB_PHASE_FAILED      AgentRunPrepareJobPhase = 5
	AgentRunPrepareJobPhase_AGENT_RUN_PREPARE_JOB_PHASE_CANCELED    AgentRunPrepareJobPhase = 6
)

// Enum value maps for AgentRunPrepareJobPhase.
var (
	AgentRunPrepareJobPhase_name = map[int32]string{
		0: "AGENT_RUN_PREPARE_JOB_PHASE_UNSPECIFIED",
		1: "AGENT_RUN_PREPARE_JOB_PHASE_PENDING",
		2: "AGENT_RUN_PREPARE_JOB_PHASE_SKIPPED",
		3: "AGENT_RUN_PREPARE_JOB_PHASE_RUNNING",
		4: "AGENT_RUN_PREPARE_JOB_PHASE_SUCCEEDED",
		5: "AGENT_RUN_PREPARE_JOB_PHASE_FAILED",
		6: "AGENT_RUN_PREPARE_JOB_PHASE_CANCELED",
	}
	AgentRunPrepareJobPhase_value = map[string]int32{
		"AGENT_RUN_PREPARE_JOB_PHASE_UNSPECIFIED": 0,
		"AGENT_RUN_PREPARE_JOB_PHASE_PENDING":     1,
		"AGENT_RUN_PREPARE_JOB_PHASE_SKIPPED":     2,
		"AGENT_RUN_PREPARE_JOB_PHASE_RUNNING":     3,
		"AGENT_RUN_PREPARE_JOB_PHASE_SUCCEEDED":   4,
		"AGENT_RUN_PREPARE_JOB_PHASE_FAILED":      5,
		"AGENT_RUN_PREPARE_JOB_PHASE_CANCELED":    6,
	}
)

func (x AgentRunPrepareJobPhase) Enum() *AgentRunPrepareJobPhase {
	p := new(AgentRunPrepareJobPhase)
	*p = x
	return p
}

func (x AgentRunPrepareJobPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRunPrepareJobPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_agent_run_v1_agent_run_proto_enumTypes[1].Descriptor()
}

func (AgentRunPrepareJobPhase) Type() protoreflect.EnumType {
	return &file_platform_agent_run_v1_agent_run_proto_enumTypes[1]
}

func (x AgentRunPrepareJobPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRunPrepareJobPhase.Descriptor instead.
func (AgentRunPrepareJobPhase) EnumDescriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{1}
}

// AgentRunPhase describes the observed lifecycle phase of one turn.
type AgentRunPhase int32

const (
	AgentRunPhase_AGENT_RUN_PHASE_UNSPECIFIED AgentRunPhase = 0
	AgentRunPhase_AGENT_RUN_PHASE_PENDING     AgentRunPhase = 1
	AgentRunPhase_AGENT_RUN_PHASE_SCHEDULED   AgentRunPhase = 2
	AgentRunPhase_AGENT_RUN_PHASE_RUNNING     AgentRunPhase = 3
	AgentRunPhase_AGENT_RUN_PHASE_SUCCEEDED   AgentRunPhase = 4
	AgentRunPhase_AGENT_RUN_PHASE_FAILED      AgentRunPhase = 5
	AgentRunPhase_AGENT_RUN_PHASE_CANCELED    AgentRunPhase = 6
)

// Enum value maps for AgentRunPhase.
var (
	AgentRunPhase_name = map[int32]string{
		0: "AGENT_RUN_PHASE_UNSPECIFIED",
		1: "AGENT_RUN_PHASE_PENDING",
		2: "AGENT_RUN_PHASE_SCHEDULED",
		3: "AGENT_RUN_PHASE_RUNNING",
		4: "AGENT_RUN_PHASE_SUCCEEDED",
		5: "AGENT_RUN_PHASE_FAILED",
		6: "AGENT_RUN_PHASE_CANCELED",
	}
	AgentRunPhase_value = map[string]int32{
		"AGENT_RUN_PHASE_UNSPECIFIED": 0,
		"AGENT_RUN_PHASE_PENDING":     1,
		"AGENT_RUN_PHASE_SCHEDULED":   2,
		"AGENT_RUN_PHASE_RUNNING":     3,
		"AGENT_RUN_PHASE_SUCCEEDED":   4,
		"AGENT_RUN_PHASE_FAILED":      5,
		"AGENT_RUN_PHASE_CANCELED":    6,
	}
)

func (x AgentRunPhase) Enum() *AgentRunPhase {
	p := new(AgentRunPhase)
	*p = x
	return p
}

func (x AgentRunPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRunPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_agent_run_v1_agent_run_proto_enumTypes[2].Descriptor()
}

func (AgentRunPhase) Type() protoreflect.EnumType {
	return &file_platform_agent_run_v1_agent_run_proto_enumTypes[2]
}

func (x AgentRunPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRunPhase.Descriptor instead.
func (AgentRunPhase) EnumDescriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{2}
}

// AgentRunSpec describes the desired state for one turn within one
// AgentSession. The frozen generation fields capture which version of the
// session and its reload surfaces were bound to this turn at submit time.
type AgentRunSpec struct {
	state                    protoimpl.MessageState   `protogen:"open.v1"`
	RunId                    string                   `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SessionId                string                   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionGeneration        int64                    `protobuf:"varint,3,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`
	RuntimeConfigGeneration  int64                    `protobuf:"varint,4,opt,name=runtime_config_generation,json=runtimeConfigGeneration,proto3" json:"runtime_config_generation,omitempty"`
	ResourceConfigGeneration int64                    `protobuf:"varint,5,opt,name=resource_config_generation,json=resourceConfigGeneration,proto3" json:"resource_config_generation,omitempty"`
	StateGeneration          int64                    `protobuf:"varint,6,opt,name=state_generation,json=stateGeneration,proto3" json:"state_generation,omitempty"`
	Request                  *v1.RunRequest           `protobuf:"bytes,7,opt,name=request,proto3" json:"request,omitempty"`
	ExecutionClass           string                   `protobuf:"bytes,8,opt,name=execution_class,json=executionClass,proto3" json:"execution_class,omitempty"`
	ContainerImage           string                   `protobuf:"bytes,9,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	CpuRequest               string                   `protobuf:"bytes,10,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	MemoryRequest            string                   `protobuf:"bytes,11,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	ProviderId               string                   `protobuf:"bytes,12,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	AuthRequirement          *AgentRunAuthRequirement `protobuf:"bytes,13,opt,name=auth_requirement,json=authRequirement,proto3" json:"auth_requirement,omitempty"`
	CancelRequested          bool                     `protobuf:"varint,14,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	RuntimeEnvironment       *v1.RuntimeEnvironment   `protobuf:"bytes,15,opt,name=runtime_environment,json=runtimeEnvironment,proto3" json:"runtime_environment,omitempty"`
	WorkspaceId              string                   `protobuf:"bytes,16,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	HomeStateId              string                   `protobuf:"bytes,17,opt,name=home_state_id,json=homeStateId,proto3" json:"home_state_id,omitempty"`
	PrepareJobs              []*AgentRunPrepareJob    `protobuf:"bytes,18,rep,name=prepare_jobs,json=prepareJobs,proto3" json:"prepare_jobs,omitempty"`
	AgentRuntimeId           string                   `protobuf:"bytes,19,opt,name=agent_runtime_id,json=agentRuntimeId,proto3" json:"agent_runtime_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentRunSpec) Reset() {
	*x = AgentRunSpec{}
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunSpec) ProtoMessage() {}

func (x *AgentRunSpec) ProtoReflect() protoreflect.Message {
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunSpec.ProtoReflect.Descriptor instead.
func (*AgentRunSpec) Descriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRunSpec) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentRunSpec) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentRunSpec) GetSessionGeneration() int64 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

func (x *AgentRunSpec) GetRuntimeConfigGeneration() int64 {
	if x != nil {
		return x.RuntimeConfigGeneration
	}
	return 0
}

func (x *AgentRunSpec) GetResourceConfigGeneration() int64 {
	if x != nil {
		return x.ResourceConfigGeneration
	}
	return 0
}

func (x *AgentRunSpec) GetStateGeneration() int64 {
	if x != nil {
		return x.StateGeneration
	}
	return 0
}

func (x *AgentRunSpec) GetRequest() *v1.RunRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AgentRunSpec) GetExecutionClass() string {
	if x != nil {
		return x.ExecutionClass
	}
	return ""
}

func (x *AgentRunSpec) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *AgentRunSpec) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *AgentRunSpec) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *AgentRunSpec) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AgentRunSpec) GetAuthRequirement() *AgentRunAuthRequirement {
	if x != nil {
		return x.AuthRequirement
	}
	return nil
}

func (x *AgentRunSpec) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

func (x *AgentRunSpec) GetRuntimeEnvironment() *v1.RuntimeEnvironment {
	if x != nil {
		return x.RuntimeEnvironment
	}
	return nil
}

func (x *AgentRunSpec) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AgentRunSpec) GetHomeStateId() string {
	if x != nil {
		return x.HomeStateId
	}
	return ""
}

func (x *AgentRunSpec) GetPrepareJobs() []*AgentRunPrepareJob {
	if x != nil {
		return x.PrepareJobs
	}
	return nil
}

func (x *AgentRunSpec) GetAgentRuntimeId() string {
	if x != nil {
		return x.AgentRuntimeId
	}
	return ""
}

// AgentRunAuthRequirement captures the provider auth requirement visible to
// the session/run domain.
type AgentRunAuthRequirement struct {
	state                    protoimpl.MessageState  `protogen:"open.v1"`
	ProviderId               string                  `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderSurfaceBindingId string                  `protobuf:"bytes,2,opt,name=provider_surface_binding_id,json=providerSurfaceBindingId,proto3" json:"provider_surface_binding_id,omitempty"`
	AuthStatus               string                  `protobuf:"bytes,3,opt,name=auth_status,json=authStatus,proto3" json:"auth_status,omitempty"`
	RuntimeUrl               string                  `protobuf:"bytes,4,opt,name=runtime_url,json=runtimeUrl,proto3" json:"runtime_url,omitempty"`
	MaterializationKey       string                  `protobuf:"bytes,5,opt,name=materialization_key,json=materializationKey,proto3" json:"materialization_key,omitempty"`
	ProviderRunBinding       *v11.ProviderRunBinding `protobuf:"bytes,6,opt,name=provider_run_binding,json=providerRunBinding,proto3" json:"provider_run_binding,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentRunAuthRequirement) Reset() {
	*x = AgentRunAuthRequirement{}
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunAuthRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunAuthRequirement) ProtoMessage() {}

func (x *AgentRunAuthRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunAuthRequirement.ProtoReflect.Descriptor instead.
func (*AgentRunAuthRequirement) Descriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRunAuthRequirement) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AgentRunAuthRequirement) GetProviderSurfaceBindingId() string {
	if x != nil {
		return x.ProviderSurfaceBindingId
	}
	return ""
}

func (x *AgentRunAuthRequirement) GetAuthStatus() string {
	if x != nil {
		return x.AuthStatus
	}
	return ""
}

func (x *AgentRunAuthRequirement) GetRuntimeUrl() string {
	if x != nil {
		return x.RuntimeUrl
	}
	return ""
}

func (x *AgentRunAuthRequirement) GetMaterializationKey() string {
	if x != nil {
		return x.MaterializationKey
	}
	return ""
}

func (x *AgentRunAuthRequirement) GetProviderRunBinding() *v11.ProviderRunBinding {
	if x != nil {
		return x.ProviderRunBinding
	}
	return nil
}

// AgentRunPrepareJob captures one CLI-scoped prepare workload before execution.
type AgentRunPrepareJob struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	JobId          string                    `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobType        string                    `protobuf:"bytes,2,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	RunType        AgentRunPrepareJobRunType `protobuf:"varint,3,opt,name=run_type,json=runType,proto3,enum=platform.agent_run.v1.AgentRunPrepareJobRunType" json:"run_type,omitempty"`
	ChangeKey      string                    `protobuf:"bytes,4,opt,name=change_key,json=changeKey,proto3" json:"change_key,omitempty"`
	Cleanup        bool                      `protobuf:"varint,5,opt,name=cleanup,proto3" json:"cleanup,omitempty"`
	ParametersYaml string                    `protobuf:"bytes,6,opt,name=parameters_yaml,json=parametersYaml,proto3" json:"parameters_yaml,omitempty"`
	CliId          string                    `protobuf:"bytes,7,opt,name=cli_id,json=cliId,proto3" json:"cli_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRunPrepareJob) Reset() {
	*x = AgentRunPrepareJob{}
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunPrepareJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunPrepareJob) ProtoMessage() {}

func (x *AgentRunPrepareJob) ProtoReflect() protoreflect.Message {
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunPrepareJob.ProtoReflect.Descriptor instead.
func (*AgentRunPrepareJob) Descriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{2}
}

func (x *AgentRunPrepareJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AgentRunPrepareJob) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *AgentRunPrepareJob) GetRunType() AgentRunPrepareJobRunType {
	if x != nil {
		return x.RunType
	}
	return AgentRunPrepareJobRunType_AGENT_RUN_PREPARE_JOB_RUN_TYPE_UNSPECIFIED
}

func (x *AgentRunPrepareJob) GetChangeKey() string {
	if x != nil {
		return x.ChangeKey
	}
	return ""
}

func (x *AgentRunPrepareJob) GetCleanup() bool {
	if x != nil {
		return x.Cleanup
	}
	return false
}

func (x *AgentRunPrepareJob) GetParametersYaml() string {
	if x != nil {
		return x.ParametersYaml
	}
	return ""
}

func (x *AgentRunPrepareJob) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

// AgentRunPrepareJobStatus captures the observed summary for one prepare job.
type AgentRunPrepareJobStatus struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Phase         AgentRunPrepareJobPhase `protobuf:"varint,2,opt,name=phase,proto3,enum=platform.agent_run.v1.AgentRunPrepareJobPhase" json:"phase,omitempty"`
	Message       string                  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunPrepareJobStatus) Reset() {
	*x = AgentRunPrepareJobStatus{}
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunPrepareJobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunPrepareJobStatus) ProtoMessage() {}

func (x *AgentRunPrepareJobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunPrepareJobStatus.ProtoReflect.Descriptor instead.
func (*AgentRunPrepareJobStatus) Descriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRunPrepareJobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AgentRunPrepareJobStatus) GetPhase() AgentRunPrepareJobPhase {
	if x != nil {
		return x.Phase
	}
	return AgentRunPrepareJobPhase_AGENT_RUN_PREPARE_JOB_PHASE_UNSPECIFIED
}

func (x *AgentRunPrepareJobStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentRunPrepareJobStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AgentRunPrepareJobStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// AgentRunRef identifies one submitted agent run.
type AgentRunRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunRef) Reset() {
	*x = AgentRunRef{}
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunRef) ProtoMessage() {}

func (x *AgentRunRef) ProtoReflect() protoreflect.Message {
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunRef.ProtoReflect.Descriptor instead.
func (*AgentRunRef) Descriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{4}
}

func (x *AgentRunRef) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// WorkloadRef identifies the workload backing one agent run.
type WorkloadRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadRef) Reset() {
	*x = WorkloadRef{}
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRef) ProtoMessage() {}

func (x *WorkloadRef) ProtoReflect() protoreflect.Message {
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRef.ProtoReflect.Descriptor instead.
func (*WorkloadRef) Descriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{5}
}

func (x *WorkloadRef) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

// AgentRunStatus describes observed summary state for one turn. run_id
// keeps the run identity available when status is serialized independently of a
// Kubernetes resource envelope.
type AgentRunStatus struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	RunId              string                      `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Phase              AgentRunPhase               `protobuf:"varint,2,opt,name=phase,proto3,enum=platform.agent_run.v1.AgentRunPhase" json:"phase,omitempty"`
	ObservedGeneration int64                       `protobuf:"varint,3,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	Message            string                      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Workload           *WorkloadRef                `protobuf:"bytes,5,opt,name=workload,proto3" json:"workload,omitempty"`
	Conditions         []*v12.Condition            `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Result             *v13.RunResult              `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	UpdatedAt          *timestamppb.Timestamp      `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PrepareJobs        []*AgentRunPrepareJobStatus `protobuf:"bytes,9,rep,name=prepare_jobs,json=prepareJobs,proto3" json:"prepare_jobs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentRunStatus) Reset() {
	*x = AgentRunStatus{}
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunStatus) ProtoMessage() {}

func (x *AgentRunStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunStatus.ProtoReflect.Descriptor instead.
func (*AgentRunStatus) Descriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{6}
}

func (x *AgentRunStatus) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentRunStatus) GetPhase() AgentRunPhase {
	if x != nil {
		return x.Phase
	}
	return AgentRunPhase_AGENT_RUN_PHASE_UNSPECIFIED
}

func (x *AgentRunStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *AgentRunStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentRunStatus) GetWorkload() *WorkloadRef {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *AgentRunStatus) GetConditions() []*v12.Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *AgentRunStatus) GetResult() *v13.RunResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentRunStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AgentRunStatus) GetPrepareJobs() []*AgentRunPrepareJobStatus {
	if x != nil {
		return x.PrepareJobs
	}
	return nil
}

// AgentRunState combines desired state and observed state for one turn.
// The wrapper does not repeat run_id; identity is carried by spec and status.
type AgentRunState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    int64                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Spec          *AgentRunSpec          `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *AgentRunStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunState) Reset() {
	*x = AgentRunState{}
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunState) ProtoMessage() {}

func (x *AgentRunState) ProtoReflect() protoreflect.Message {
	mi := &file_platform_agent_run_v1_agent_run_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunState.ProtoReflect.Descriptor instead.
func (*AgentRunState) Descriptor() ([]byte, []int) {
	return file_platform_agent_run_v1_agent_run_proto_rawDescGZIP(), []int{7}
}

func (x *AgentRunState) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *AgentRunState) GetSpec() *AgentRunSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AgentRunState) GetStatus() *AgentRunStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_platform_agent_run_v1_agent_run_proto protoreflect.FileDescriptor

const file_platform_agent_run_v1_agent_run_proto_rawDesc = "" +
	"\n" +
	"%platform/agent_run/v1/agent_run.proto\x12\x15platform.agent_run.v1\x1a\x19agent/core/v1/agent.proto\x1a\x1cagent/result/v1/result.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aprovider/v1/provider.proto\x1a%platform/condition/v1/condition.proto\"\xa1\a\n" +
	"\fAgentRunSpec\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12-\n" +
	"\x12session_generation\x18\x03 \x01(\x03R\x11sessionGeneration\x12:\n" +
	"\x19runtime_config_generation\x18\x04 \x01(\x03R\x17runtimeConfigGeneration\x12<\n" +
	"\x1aresource_config_generation\x18\x05 \x01(\x03R\x18resourceConfigGeneration\x12)\n" +
	"\x10state_generation\x18\x06 \x01(\x03R\x0fstateGeneration\x123\n" +
	"\arequest\x18\a \x01(\v2\x19.agent.core.v1.RunRequestR\arequest\x12'\n" +
	"\x0fexecution_class\x18\b \x01(\tR\x0eexecutionClass\x12'\n" +
	"\x0fcontainer_image\x18\t \x01(\tR\x0econtainerImage\x12\x1f\n" +
	"\vcpu_request\x18\n" +
	" \x01(\tR\n" +
	"cpuRequest\x12%\n" +
	"\x0ememory_request\x18\v \x01(\tR\rmemoryRequest\x12\x1f\n" +
	"\vprovider_id\x18\f \x01(\tR\n" +
	"providerId\x12Y\n" +
	"\x10auth_requirement\x18\r \x01(\v2..platform.agent_run.v1.AgentRunAuthRequirementR\x0fauthRequirement\x12)\n" +
	"\x10cancel_requested\x18\x0e \x01(\bR\x0fcancelRequested\x12R\n" +
	"\x13runtime_environment\x18\x0f \x01(\v2!.agent.core.v1.RuntimeEnvironmentR\x12runtimeEnvironment\x12!\n" +
	"\fworkspace_id\x18\x10 \x01(\tR\vworkspaceId\x12\"\n" +
	"\rhome_state_id\x18\x11 \x01(\tR\vhomeStateId\x12L\n" +
	"\fprepare_jobs\x18\x12 \x03(\v2).platform.agent_run.v1.AgentRunPrepareJobR\vprepareJobs\x12(\n" +
	"\x10agent_runtime_id\x18\x13 \x01(\tR\x0eagentRuntimeId\"\xbf\x02\n" +
	"\x17AgentRunAuthRequirement\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12=\n" +
	"\x1bprovider_surface_binding_id\x18\x02 \x01(\tR\x18providerSurfaceBindingId\x12\x1f\n" +
	"\vauth_status\x18\x03 \x01(\tR\n" +
	"authStatus\x12\x1f\n" +
	"\vruntime_url\x18\x04 \x01(\tR\n" +
	"runtimeUrl\x12/\n" +
	"\x13materialization_key\x18\x05 \x01(\tR\x12materializationKey\x12Q\n" +
	"\x14provider_run_binding\x18\x06 \x01(\v2\x1f.provider.v1.ProviderRunBindingR\x12providerRunBinding\"\x8c\x02\n" +
	"\x12AgentRunPrepareJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_type\x18\x02 \x01(\tR\ajobType\x12K\n" +
	"\brun_type\x18\x03 \x01(\x0e20.platform.agent_run.v1.AgentRunPrepareJobRunTypeR\arunType\x12\x1d\n" +
	"\n" +
	"change_key\x18\x04 \x01(\tR\tchangeKey\x12\x18\n" +
	"\acleanup\x18\x05 \x01(\bR\acleanup\x12'\n" +
	"\x0fparameters_yaml\x18\x06 \x01(\tR\x0eparametersYaml\x12\x15\n" +
	"\x06cli_id\x18\a \x01(\tR\x05cliId\"\x89\x02\n" +
	"\x18AgentRunPrepareJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12D\n" +
	"\x05phase\x18\x02 \x01(\x0e2..platform.agent_run.v1.AgentRunPrepareJobPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"$\n" +
	"\vAgentRunRef\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\".\n" +
	"\vWorkloadRef\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\"\xf3\x03\n" +
	"\x0eAgentRunStatus\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12:\n" +
	"\x05phase\x18\x02 \x01(\x0e2$.platform.agent_run.v1.AgentRunPhaseR\x05phase\x12/\n" +
	"\x13observed_generation\x18\x03 \x01(\x03R\x12observedGeneration\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12>\n" +
	"\bworkload\x18\x05 \x01(\v2\".platform.agent_run.v1.WorkloadRefR\bworkload\x12@\n" +
	"\n" +
	"conditions\x18\x06 \x03(\v2 .platform.condition.v1.ConditionR\n" +
	"conditions\x122\n" +
	"\x06result\x18\a \x01(\v2\x1a.agent.result.v1.RunResultR\x06result\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12R\n" +
	"\fprepare_jobs\x18\t \x03(\v2/.platform.agent_run.v1.AgentRunPrepareJobStatusR\vprepareJobs\"\xa7\x01\n" +
	"\rAgentRunState\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x03R\n" +
	"generation\x127\n" +
	"\x04spec\x18\x02 \x01(\v2#.platform.agent_run.v1.AgentRunSpecR\x04spec\x12=\n" +
	"\x06status\x18\x03 \x01(\v2%.platform.agent_run.v1.AgentRunStatusR\x06status*\xcf\x01\n" +
	"\x19AgentRunPrepareJobRunType\x12.\n" +
	"*AGENT_RUN_PREPARE_JOB_RUN_TYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#AGENT_RUN_PREPARE_JOB_RUN_TYPE_INIT\x10\x01\x12*\n" +
	"&AGENT_RUN_PREPARE_JOB_RUN_TYPE_PER_RUN\x10\x02\x12-\n" +
	")AGENT_RUN_PREPARE_JOB_RUN_TYPE_ON_CHANGED\x10\x03*\xbe\x02\n" +
	"\x17AgentRunPrepareJobPhase\x12+\n" +
	"'AGENT_RUN_PREPARE_JOB_PHASE_UNSPECIFIED\x10\x00\x12'\n" +
	"#AGENT_RUN_PREPARE_JOB_PHASE_PENDING\x10\x01\x12'\n" +
	"#AGENT_RUN_PREPARE_JOB_PHASE_SKIPPED\x10\x02\x12'\n" +
	"#AGENT_RUN_PREPARE_JOB_PHASE_RUNNING\x10\x03\x12)\n" +
	"%AGENT_RUN_PREPARE_JOB_PHASE_SUCCEEDED\x10\x04\x12&\n" +
	"\"AGENT_RUN_PREPARE_JOB_PHASE_FAILED\x10\x05\x12(\n" +
	"$AGENT_RUN_PREPARE_JOB_PHASE_CANCELED\x10\x06*\xe2\x01\n" +
	"\rAgentRunPhase\x12\x1f\n" +
	"\x1bAGENT_RUN_PHASE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17AGENT_RUN_PHASE_PENDING\x10\x01\x12\x1d\n" +
	"\x19AGENT_RUN_PHASE_SCHEDULED\x10\x02\x12\x1b\n" +
	"\x17AGENT_RUN_PHASE_RUNNING\x10\x03\x12\x1d\n" +
	"\x19AGENT_RUN_PHASE_SUCCEEDED\x10\x04\x12\x1a\n" +
	"\x16AGENT_RUN_PHASE_FAILED\x10\x05\x12\x1c\n" +
	"\x18AGENT_RUN_PHASE_CANCELED\x10\x06BAZ?code-code.internal/go-contract/platform/agent_run/v1;agentrunv1b\x06proto3"

var (
	file_platform_agent_run_v1_agent_run_proto_rawDescOnce sync.Once
	file_platform_agent_run_v1_agent_run_proto_rawDescData []byte
)

func file_platform_agent_run_v1_agent_run_proto_rawDescGZIP() []byte {
	file_platform_agent_run_v1_agent_run_proto_rawDescOnce.Do(func() {
		file_platform_agent_run_v1_agent_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_agent_run_v1_agent_run_proto_rawDesc), len(file_platform_agent_run_v1_agent_run_proto_rawDesc)))
	})
	return file_platform_agent_run_v1_agent_run_proto_rawDescData
}

var file_platform_agent_run_v1_agent_run_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_platform_agent_run_v1_agent_run_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_platform_agent_run_v1_agent_run_proto_goTypes = []any{
	(AgentRunPrepareJobRunType)(0),   // 0: platform.agent_run.v1.AgentRunPrepareJobRunType
	(AgentRunPrepareJobPhase)(0),     // 1: platform.agent_run.v1.AgentRunPrepareJobPhase
	(AgentRunPhase)(0),               // 2: platform.agent_run.v1.AgentRunPhase
	(*AgentRunSpec)(nil),             // 3: platform.agent_run.v1.AgentRunSpec
	(*AgentRunAuthRequirement)(nil),  // 4: platform.agent_run.v1.AgentRunAuthRequirement
	(*AgentRunPrepareJob)(nil),       // 5: platform.agent_run.v1.AgentRunPrepareJob
	(*AgentRunPrepareJobStatus)(nil), // 6: platform.agent_run.v1.AgentRunPrepareJobStatus
	(*AgentRunRef)(nil),              // 7: platform.agent_run.v1.AgentRunRef
	(*WorkloadRef)(nil),              // 8: platform.agent_run.v1.WorkloadRef
	(*AgentRunStatus)(nil),           // 9: platform.agent_run.v1.AgentRunStatus
	(*AgentRunState)(nil),            // 10: platform.agent_run.v1.AgentRunState
	(*v1.RunRequest)(nil),            // 11: agent.core.v1.RunRequest
	(*v1.RuntimeEnvironment)(nil),    // 12: agent.core.v1.RuntimeEnvironment
	(*v11.ProviderRunBinding)(nil),   // 13: provider.v1.ProviderRunBinding
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*v12.Condition)(nil),            // 15: platform.condition.v1.Condition
	(*v13.RunResult)(nil),            // 16: agent.result.v1.RunResult
}
var file_platform_agent_run_v1_agent_run_proto_depIdxs = []int32{
	11, // 0: platform.agent_run.v1.AgentRunSpec.request:type_name -> agent.core.v1.RunRequest
	4,  // 1: platform.agent_run.v1.AgentRunSpec.auth_requirement:type_name -> platform.agent_run.v1.AgentRunAuthRequirement
	12, // 2: platform.agent_run.v1.AgentRunSpec.runtime_environment:type_name -> agent.core.v1.RuntimeEnvironment
	5,  // 3: platform.agent_run.v1.AgentRunSpec.prepare_jobs:type_name -> platform.agent_run.v1.AgentRunPrepareJob
	13, // 4: platform.agent_run.v1.AgentRunAuthRequirement.provider_run_binding:type_name -> provider.v1.ProviderRunBinding
	0,  // 5: platform.agent_run.v1.AgentRunPrepareJob.run_type:type_name -> platform.agent_run.v1.AgentRunPrepareJobRunType
	1,  // 6: platform.agent_run.v1.AgentRunPrepareJobStatus.phase:type_name -> platform.agent_run.v1.AgentRunPrepareJobPhase
	14, // 7: platform.agent_run.v1.AgentRunPrepareJobStatus.started_at:type_name -> google.protobuf.Timestamp
	14, // 8: platform.agent_run.v1.AgentRunPrepareJobStatus.finished_at:type_name -> google.protobuf.Timestamp
	2,  // 9: platform.agent_run.v1.AgentRunStatus.phase:type_name -> platform.agent_run.v1.AgentRunPhase
	8,  // 10: platform.agent_run.v1.AgentRunStatus.workload:type_name -> platform.agent_run.v1.WorkloadRef
	15, // 11: platform.agent_run.v1.AgentRunStatus.conditions:type_name -> platform.condition.v1.Condition
	16, // 12: platform.agent_run.v1.AgentRunStatus.result:type_name -> agent.result.v1.RunResult
	14, // 13: platform.agent_run.v1.AgentRunStatus.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 14: platform.agent_run.v1.AgentRunStatus.prepare_jobs:type_name -> platform.agent_run.v1.AgentRunPrepareJobStatus
	3,  // 15: platform.agent_run.v1.AgentRunState.spec:type_name -> platform.agent_run.v1.AgentRunSpec
	9,  // 16: platform.agent_run.v1.AgentRunState.status:type_name -> platform.agent_run.v1.AgentRunStatus
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_platform_agent_run_v1_agent_run_proto_init() }
func file_platform_agent_run_v1_agent_run_proto_init() {
	if File_platform_agent_run_v1_agent_run_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_agent_run_v1_agent_run_proto_rawDesc), len(file_platform_agent_run_v1_agent_run_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_agent_run_v1_agent_run_proto_goTypes,
		DependencyIndexes: file_platform_agent_run_v1_agent_run_proto_depIdxs,
		EnumInfos:         file_platform_agent_run_v1_agent_run_proto_enumTypes,
		MessageInfos:      file_platform_agent_run_v1_agent_run_proto_msgTypes,
	}.Build()
	File_platform_agent_run_v1_agent_run_proto = out.File
	file_platform_agent_run_v1_agent_run_proto_goTypes = nil
	file_platform_agent_run_v1_agent_run_proto_depIdxs = nil
}
