// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: credential/v1/credential.proto

package credentialv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CredentialKind identifies the semantic kind of one credential.
type CredentialKind int32

const (
	CredentialKind_CREDENTIAL_KIND_UNSPECIFIED CredentialKind = 0
	CredentialKind_CREDENTIAL_KIND_API_KEY     CredentialKind = 1
	CredentialKind_CREDENTIAL_KIND_OAUTH       CredentialKind = 2
	CredentialKind_CREDENTIAL_KIND_SESSION     CredentialKind = 3
)

// Enum value maps for CredentialKind.
var (
	CredentialKind_name = map[int32]string{
		0: "CREDENTIAL_KIND_UNSPECIFIED",
		1: "CREDENTIAL_KIND_API_KEY",
		2: "CREDENTIAL_KIND_OAUTH",
		3: "CREDENTIAL_KIND_SESSION",
	}
	CredentialKind_value = map[string]int32{
		"CREDENTIAL_KIND_UNSPECIFIED": 0,
		"CREDENTIAL_KIND_API_KEY":     1,
		"CREDENTIAL_KIND_OAUTH":       2,
		"CREDENTIAL_KIND_SESSION":     3,
	}
)

func (x CredentialKind) Enum() *CredentialKind {
	p := new(CredentialKind)
	*p = x
	return p
}

func (x CredentialKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialKind) Descriptor() protoreflect.EnumDescriptor {
	return file_credential_v1_credential_proto_enumTypes[0].Descriptor()
}

func (CredentialKind) Type() protoreflect.EnumType {
	return &file_credential_v1_credential_proto_enumTypes[0]
}

func (x CredentialKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialKind.Descriptor instead.
func (CredentialKind) EnumDescriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{0}
}

// CredentialPurpose documents the intended use of a credential.
// This is informational and does not restrict actual usage; it helps the
// console UI guide users toward the right credential for each slot.
type CredentialPurpose int32

const (
	CredentialPurpose_CREDENTIAL_PURPOSE_UNSPECIFIED CredentialPurpose = 0
	// Data-plane: used for LLM inference requests.
	CredentialPurpose_CREDENTIAL_PURPOSE_DATA_PLANE CredentialPurpose = 1
	// Management-plane: used for quota, usage, billing queries.
	CredentialPurpose_CREDENTIAL_PURPOSE_MANAGEMENT_PLANE CredentialPurpose = 2
)

// Enum value maps for CredentialPurpose.
var (
	CredentialPurpose_name = map[int32]string{
		0: "CREDENTIAL_PURPOSE_UNSPECIFIED",
		1: "CREDENTIAL_PURPOSE_DATA_PLANE",
		2: "CREDENTIAL_PURPOSE_MANAGEMENT_PLANE",
	}
	CredentialPurpose_value = map[string]int32{
		"CREDENTIAL_PURPOSE_UNSPECIFIED":      0,
		"CREDENTIAL_PURPOSE_DATA_PLANE":       1,
		"CREDENTIAL_PURPOSE_MANAGEMENT_PLANE": 2,
	}
)

func (x CredentialPurpose) Enum() *CredentialPurpose {
	p := new(CredentialPurpose)
	*p = x
	return p
}

func (x CredentialPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_credential_v1_credential_proto_enumTypes[1].Descriptor()
}

func (CredentialPurpose) Type() protoreflect.EnumType {
	return &file_credential_v1_credential_proto_enumTypes[1]
}

func (x CredentialPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialPurpose.Descriptor instead.
func (CredentialPurpose) EnumDescriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{1}
}

// CredentialRef references a credential by stable identity.
type CredentialRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRef) Reset() {
	*x = CredentialRef{}
	mi := &file_credential_v1_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRef) ProtoMessage() {}

func (x *CredentialRef) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRef.ProtoReflect.Descriptor instead.
func (*CredentialRef) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialRef) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type CredentialGrantRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialGrantRef) Reset() {
	*x = CredentialGrantRef{}
	mi := &file_credential_v1_credential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialGrantRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialGrantRef) ProtoMessage() {}

func (x *CredentialGrantRef) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialGrantRef.ProtoReflect.Descriptor instead.
func (*CredentialGrantRef) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialGrantRef) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

// CredentialDefinition describes one credential resource owned by the platform.
type CredentialDefinition struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CredentialId string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	DisplayName  string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Kind         CredentialKind         `protobuf:"varint,3,opt,name=kind,proto3,enum=credential.v1.CredentialKind" json:"kind,omitempty"`
	// Intended purpose. Helps the console UI guide users.
	Purpose CredentialPurpose `protobuf:"varint,4,opt,name=purpose,proto3,enum=credential.v1.CredentialPurpose" json:"purpose,omitempty"`
	// Provider vendor identity when this credential is bound to one known
	// vendor. Empty means unspecified vendor.
	VendorId string `protobuf:"bytes,5,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	// Kind-specific management metadata.
	//
	// Types that are valid to be assigned to KindMetadata:
	//
	//	*CredentialDefinition_OauthMetadata
	//	*CredentialDefinition_SessionMetadata
	KindMetadata  isCredentialDefinition_KindMetadata `protobuf_oneof:"kind_metadata"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialDefinition) Reset() {
	*x = CredentialDefinition{}
	mi := &file_credential_v1_credential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialDefinition) ProtoMessage() {}

func (x *CredentialDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialDefinition.ProtoReflect.Descriptor instead.
func (*CredentialDefinition) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialDefinition) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *CredentialDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CredentialDefinition) GetKind() CredentialKind {
	if x != nil {
		return x.Kind
	}
	return CredentialKind_CREDENTIAL_KIND_UNSPECIFIED
}

func (x *CredentialDefinition) GetPurpose() CredentialPurpose {
	if x != nil {
		return x.Purpose
	}
	return CredentialPurpose_CREDENTIAL_PURPOSE_UNSPECIFIED
}

func (x *CredentialDefinition) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *CredentialDefinition) GetKindMetadata() isCredentialDefinition_KindMetadata {
	if x != nil {
		return x.KindMetadata
	}
	return nil
}

func (x *CredentialDefinition) GetOauthMetadata() *OAuthMetadata {
	if x != nil {
		if x, ok := x.KindMetadata.(*CredentialDefinition_OauthMetadata); ok {
			return x.OauthMetadata
		}
	}
	return nil
}

func (x *CredentialDefinition) GetSessionMetadata() *SessionMetadata {
	if x != nil {
		if x, ok := x.KindMetadata.(*CredentialDefinition_SessionMetadata); ok {
			return x.SessionMetadata
		}
	}
	return nil
}

type isCredentialDefinition_KindMetadata interface {
	isCredentialDefinition_KindMetadata()
}

type CredentialDefinition_OauthMetadata struct {
	OauthMetadata *OAuthMetadata `protobuf:"bytes,11,opt,name=oauth_metadata,json=oauthMetadata,proto3,oneof"`
}

type CredentialDefinition_SessionMetadata struct {
	SessionMetadata *SessionMetadata `protobuf:"bytes,12,opt,name=session_metadata,json=sessionMetadata,proto3,oneof"`
}

func (*CredentialDefinition_OauthMetadata) isCredentialDefinition_KindMetadata() {}

func (*CredentialDefinition_SessionMetadata) isCredentialDefinition_KindMetadata() {}

// OAuthMetadata stores the user-declared CLI OAuth binding.
// Controller-owned lifecycle fields (credential_generation, next_refresh_after,
// last_refreshed_at, account_email) live exclusively in CRD status.
type OAuthMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CLI owner identifier (e.g. "codex", "qwen"). Determines
	// which CLI OAuth contract and refresh method to use.
	CliId         string `protobuf:"bytes,1,opt,name=cli_id,json=cliId,proto3" json:"cli_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthMetadata) Reset() {
	*x = OAuthMetadata{}
	mi := &file_credential_v1_credential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthMetadata) ProtoMessage() {}

func (x *OAuthMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthMetadata.ProtoReflect.Descriptor instead.
func (*OAuthMetadata) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{3}
}

func (x *OAuthMetadata) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

// SessionMetadata stores one session credential schema binding.
type SessionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	RequiredKeys  []string               `protobuf:"bytes,2,rep,name=required_keys,json=requiredKeys,proto3" json:"required_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMetadata) Reset() {
	*x = SessionMetadata{}
	mi := &file_credential_v1_credential_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMetadata) ProtoMessage() {}

func (x *SessionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMetadata.ProtoReflect.Descriptor instead.
func (*SessionMetadata) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{4}
}

func (x *SessionMetadata) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *SessionMetadata) GetRequiredKeys() []string {
	if x != nil {
		return x.RequiredKeys
	}
	return nil
}

// ResolvedCredential describes the provider-ready auth material resolved from
// one credential reference.
type ResolvedCredential struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CredentialId string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Kind         CredentialKind         `protobuf:"varint,2,opt,name=kind,proto3,enum=credential.v1.CredentialKind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Material:
	//
	//	*ResolvedCredential_ApiKey
	//	*ResolvedCredential_Oauth
	//	*ResolvedCredential_Session
	Material      isResolvedCredential_Material `protobuf_oneof:"material"`
	GrantId       string                        `protobuf:"bytes,6,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedCredential) Reset() {
	*x = ResolvedCredential{}
	mi := &file_credential_v1_credential_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedCredential) ProtoMessage() {}

func (x *ResolvedCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedCredential.ProtoReflect.Descriptor instead.
func (*ResolvedCredential) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{5}
}

func (x *ResolvedCredential) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *ResolvedCredential) GetKind() CredentialKind {
	if x != nil {
		return x.Kind
	}
	return CredentialKind_CREDENTIAL_KIND_UNSPECIFIED
}

func (x *ResolvedCredential) GetMaterial() isResolvedCredential_Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *ResolvedCredential) GetApiKey() *ApiKeyCredential {
	if x != nil {
		if x, ok := x.Material.(*ResolvedCredential_ApiKey); ok {
			return x.ApiKey
		}
	}
	return nil
}

func (x *ResolvedCredential) GetOauth() *OAuthCredential {
	if x != nil {
		if x, ok := x.Material.(*ResolvedCredential_Oauth); ok {
			return x.Oauth
		}
	}
	return nil
}

func (x *ResolvedCredential) GetSession() *SessionCredential {
	if x != nil {
		if x, ok := x.Material.(*ResolvedCredential_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *ResolvedCredential) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type isResolvedCredential_Material interface {
	isResolvedCredential_Material()
}

type ResolvedCredential_ApiKey struct {
	ApiKey *ApiKeyCredential `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3,oneof"`
}

type ResolvedCredential_Oauth struct {
	Oauth *OAuthCredential `protobuf:"bytes,4,opt,name=oauth,proto3,oneof"`
}

type ResolvedCredential_Session struct {
	Session *SessionCredential `protobuf:"bytes,5,opt,name=session,proto3,oneof"`
}

func (*ResolvedCredential_ApiKey) isResolvedCredential_Material() {}

func (*ResolvedCredential_Oauth) isResolvedCredential_Material() {}

func (*ResolvedCredential_Session) isResolvedCredential_Material() {}

// ApiKeyCredential describes one resolved API key credential.
type ApiKeyCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyCredential) Reset() {
	*x = ApiKeyCredential{}
	mi := &file_credential_v1_credential_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyCredential) ProtoMessage() {}

func (x *ApiKeyCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyCredential.ProtoReflect.Descriptor instead.
func (*ApiKeyCredential) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{6}
}

func (x *ApiKeyCredential) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// OAuthCredential describes one resolved OAuth credential.
type OAuthCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IdToken       string                 `protobuf:"bytes,7,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthCredential) Reset() {
	*x = OAuthCredential{}
	mi := &file_credential_v1_credential_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthCredential) ProtoMessage() {}

func (x *OAuthCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthCredential.ProtoReflect.Descriptor instead.
func (*OAuthCredential) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{7}
}

func (x *OAuthCredential) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuthCredential) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuthCredential) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *OAuthCredential) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *OAuthCredential) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *OAuthCredential) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuthCredential) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

// SessionCredential describes one resolved management-plane session credential.
type SessionCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Values        map[string]string      `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCredential) Reset() {
	*x = SessionCredential{}
	mi := &file_credential_v1_credential_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCredential) ProtoMessage() {}

func (x *SessionCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credential_v1_credential_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCredential.ProtoReflect.Descriptor instead.
func (*SessionCredential) Descriptor() ([]byte, []int) {
	return file_credential_v1_credential_proto_rawDescGZIP(), []int{8}
}

func (x *SessionCredential) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *SessionCredential) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_credential_v1_credential_proto protoreflect.FileDescriptor

const file_credential_v1_credential_proto_rawDesc = "" +
	"\n" +
	"\x1ecredential/v1/credential.proto\x12\rcredential.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\rCredentialRef\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\"/\n" +
	"\x12CredentialGrantRef\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\"\xb5\x03\n" +
	"\x14CredentialDefinition\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x121\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1d.credential.v1.CredentialKindR\x04kind\x12:\n" +
	"\apurpose\x18\x04 \x01(\x0e2 .credential.v1.CredentialPurposeR\apurpose\x12\x1b\n" +
	"\tvendor_id\x18\x05 \x01(\tR\bvendorId\x12E\n" +
	"\x0eoauth_metadata\x18\v \x01(\v2\x1c.credential.v1.OAuthMetadataH\x00R\roauthMetadata\x12K\n" +
	"\x10session_metadata\x18\f \x01(\v2\x1e.credential.v1.SessionMetadataH\x00R\x0fsessionMetadataB\x0f\n" +
	"\rkind_metadataJ\x04\b\x06\x10\aJ\x04\b\n" +
	"\x10\vR\x06cli_idR\x10api_key_metadata\"\x8b\x01\n" +
	"\rOAuthMetadata\x12\x15\n" +
	"\x06cli_id\x18\x01 \x01(\tR\x05cliIdJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\raccount_emailR\x15credential_generationR\x12next_refresh_afterR\x11last_refreshed_at\"S\n" +
	"\x0fSessionMetadata\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12#\n" +
	"\rrequired_keys\x18\x02 \x03(\tR\frequiredKeys\"\xc5\x02\n" +
	"\x12ResolvedCredential\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.credential.v1.CredentialKindR\x04kind\x12:\n" +
	"\aapi_key\x18\x03 \x01(\v2\x1f.credential.v1.ApiKeyCredentialH\x00R\x06apiKey\x126\n" +
	"\x05oauth\x18\x04 \x01(\v2\x1e.credential.v1.OAuthCredentialH\x00R\x05oauth\x12<\n" +
	"\asession\x18\x05 \x01(\v2 .credential.v1.SessionCredentialH\x00R\asession\x12\x19\n" +
	"\bgrant_id\x18\x06 \x01(\tR\agrantIdB\n" +
	"\n" +
	"\bmaterial\"+\n" +
	"\x10ApiKeyCredential\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"\xcb\x02\n" +
	"\x0fOAuthCredential\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12#\n" +
	"\rrefresh_token\x18\x06 \x01(\tR\frefreshToken\x12\x19\n" +
	"\bid_token\x18\a \x01(\tR\aidTokenJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vR\raccount_emailR\x15credential_generationR\frefreshed_at\"\xb1\x01\n" +
	"\x11SessionCredential\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12D\n" +
	"\x06values\x18\x02 \x03(\v2,.credential.v1.SessionCredential.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x86\x01\n" +
	"\x0eCredentialKind\x12\x1f\n" +
	"\x1bCREDENTIAL_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CREDENTIAL_KIND_API_KEY\x10\x01\x12\x19\n" +
	"\x15CREDENTIAL_KIND_OAUTH\x10\x02\x12\x1b\n" +
	"\x17CREDENTIAL_KIND_SESSION\x10\x03*\x83\x01\n" +
	"\x11CredentialPurpose\x12\"\n" +
	"\x1eCREDENTIAL_PURPOSE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCREDENTIAL_PURPOSE_DATA_PLANE\x10\x01\x12'\n" +
	"#CREDENTIAL_PURPOSE_MANAGEMENT_PLANE\x10\x02B;Z9code-code.internal/go-contract/credential/v1;credentialv1b\x06proto3"

var (
	file_credential_v1_credential_proto_rawDescOnce sync.Once
	file_credential_v1_credential_proto_rawDescData []byte
)

func file_credential_v1_credential_proto_rawDescGZIP() []byte {
	file_credential_v1_credential_proto_rawDescOnce.Do(func() {
		file_credential_v1_credential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credential_v1_credential_proto_rawDesc), len(file_credential_v1_credential_proto_rawDesc)))
	})
	return file_credential_v1_credential_proto_rawDescData
}

var file_credential_v1_credential_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_credential_v1_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_credential_v1_credential_proto_goTypes = []any{
	(CredentialKind)(0),           // 0: credential.v1.CredentialKind
	(CredentialPurpose)(0),        // 1: credential.v1.CredentialPurpose
	(*CredentialRef)(nil),         // 2: credential.v1.CredentialRef
	(*CredentialGrantRef)(nil),    // 3: credential.v1.CredentialGrantRef
	(*CredentialDefinition)(nil),  // 4: credential.v1.CredentialDefinition
	(*OAuthMetadata)(nil),         // 5: credential.v1.OAuthMetadata
	(*SessionMetadata)(nil),       // 6: credential.v1.SessionMetadata
	(*ResolvedCredential)(nil),    // 7: credential.v1.ResolvedCredential
	(*ApiKeyCredential)(nil),      // 8: credential.v1.ApiKeyCredential
	(*OAuthCredential)(nil),       // 9: credential.v1.OAuthCredential
	(*SessionCredential)(nil),     // 10: credential.v1.SessionCredential
	nil,                           // 11: credential.v1.SessionCredential.ValuesEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_credential_v1_credential_proto_depIdxs = []int32{
	0,  // 0: credential.v1.CredentialDefinition.kind:type_name -> credential.v1.CredentialKind
	1,  // 1: credential.v1.CredentialDefinition.purpose:type_name -> credential.v1.CredentialPurpose
	5,  // 2: credential.v1.CredentialDefinition.oauth_metadata:type_name -> credential.v1.OAuthMetadata
	6,  // 3: credential.v1.CredentialDefinition.session_metadata:type_name -> credential.v1.SessionMetadata
	0,  // 4: credential.v1.ResolvedCredential.kind:type_name -> credential.v1.CredentialKind
	8,  // 5: credential.v1.ResolvedCredential.api_key:type_name -> credential.v1.ApiKeyCredential
	9,  // 6: credential.v1.ResolvedCredential.oauth:type_name -> credential.v1.OAuthCredential
	10, // 7: credential.v1.ResolvedCredential.session:type_name -> credential.v1.SessionCredential
	12, // 8: credential.v1.OAuthCredential.expires_at:type_name -> google.protobuf.Timestamp
	11, // 9: credential.v1.SessionCredential.values:type_name -> credential.v1.SessionCredential.ValuesEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_credential_v1_credential_proto_init() }
func file_credential_v1_credential_proto_init() {
	if File_credential_v1_credential_proto != nil {
		return
	}
	file_credential_v1_credential_proto_msgTypes[2].OneofWrappers = []any{
		(*CredentialDefinition_OauthMetadata)(nil),
		(*CredentialDefinition_SessionMetadata)(nil),
	}
	file_credential_v1_credential_proto_msgTypes[5].OneofWrappers = []any{
		(*ResolvedCredential_ApiKey)(nil),
		(*ResolvedCredential_Oauth)(nil),
		(*ResolvedCredential_Session)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credential_v1_credential_proto_rawDesc), len(file_credential_v1_credential_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_credential_v1_credential_proto_goTypes,
		DependencyIndexes: file_credential_v1_credential_proto_depIdxs,
		EnumInfos:         file_credential_v1_credential_proto_enumTypes,
		MessageInfos:      file_credential_v1_credential_proto_msgTypes,
	}.Build()
	File_credential_v1_credential_proto = out.File
	file_credential_v1_credential_proto_goTypes = nil
	file_credential_v1_credential_proto_depIdxs = nil
}
