apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-support-service-runtime
rules:
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "create", "delete"]
