// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: egress/v1/policy.proto

package egressv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EgressAction int32

const (
	EgressAction_EGRESS_ACTION_UNSPECIFIED EgressAction = 0
	EgressAction_EGRESS_ACTION_DIRECT      EgressAction = 1
	EgressAction_EGRESS_ACTION_PROXY       EgressAction = 2
)

// Enum value maps for EgressAction.
var (
	EgressAction_name = map[int32]string{
		0: "EGRESS_ACTION_UNSPECIFIED",
		1: "EGRESS_ACTION_DIRECT",
		2: "EGRESS_ACTION_PROXY",
	}
	EgressAction_value = map[string]int32{
		"EGRESS_ACTION_UNSPECIFIED": 0,
		"EGRESS_ACTION_DIRECT":      1,
		"EGRESS_ACTION_PROXY":       2,
	}
)

func (x EgressAction) Enum() *EgressAction {
	p := new(EgressAction)
	*p = x
	return p
}

func (x EgressAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressAction) Descriptor() protoreflect.EnumDescriptor {
	return file_egress_v1_policy_proto_enumTypes[0].Descriptor()
}

func (EgressAction) Type() protoreflect.EnumType {
	return &file_egress_v1_policy_proto_enumTypes[0]
}

func (x EgressAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressAction.Descriptor instead.
func (EgressAction) EnumDescriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{0}
}

type EgressProxyProtocol int32

const (
	EgressProxyProtocol_EGRESS_PROXY_PROTOCOL_UNSPECIFIED EgressProxyProtocol = 0
	EgressProxyProtocol_EGRESS_PROXY_PROTOCOL_HTTP        EgressProxyProtocol = 1
)

// Enum value maps for EgressProxyProtocol.
var (
	EgressProxyProtocol_name = map[int32]string{
		0: "EGRESS_PROXY_PROTOCOL_UNSPECIFIED",
		1: "EGRESS_PROXY_PROTOCOL_HTTP",
	}
	EgressProxyProtocol_value = map[string]int32{
		"EGRESS_PROXY_PROTOCOL_UNSPECIFIED": 0,
		"EGRESS_PROXY_PROTOCOL_HTTP":        1,
	}
)

func (x EgressProxyProtocol) Enum() *EgressProxyProtocol {
	p := new(EgressProxyProtocol)
	*p = x
	return p
}

func (x EgressProxyProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressProxyProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_egress_v1_policy_proto_enumTypes[1].Descriptor()
}

func (EgressProxyProtocol) Type() protoreflect.EnumType {
	return &file_egress_v1_policy_proto_enumTypes[1]
}

func (x EgressProxyProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressProxyProtocol.Descriptor instead.
func (EgressProxyProtocol) EnumDescriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{1}
}

type EgressExternalRuleSetLoadPhase int32

const (
	EgressExternalRuleSetLoadPhase_EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_UNSPECIFIED EgressExternalRuleSetLoadPhase = 0
	EgressExternalRuleSetLoadPhase_EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_DISABLED    EgressExternalRuleSetLoadPhase = 1
	EgressExternalRuleSetLoadPhase_EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_LOADED      EgressExternalRuleSetLoadPhase = 2
	EgressExternalRuleSetLoadPhase_EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_NOT_LOADED  EgressExternalRuleSetLoadPhase = 3
	EgressExternalRuleSetLoadPhase_EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_FAILED      EgressExternalRuleSetLoadPhase = 4
)

// Enum value maps for EgressExternalRuleSetLoadPhase.
var (
	EgressExternalRuleSetLoadPhase_name = map[int32]string{
		0: "EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_UNSPECIFIED",
		1: "EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_DISABLED",
		2: "EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_LOADED",
		3: "EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_NOT_LOADED",
		4: "EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_FAILED",
	}
	EgressExternalRuleSetLoadPhase_value = map[string]int32{
		"EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_UNSPECIFIED": 0,
		"EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_DISABLED":    1,
		"EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_LOADED":      2,
		"EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_NOT_LOADED":  3,
		"EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_FAILED":      4,
	}
)

func (x EgressExternalRuleSetLoadPhase) Enum() *EgressExternalRuleSetLoadPhase {
	p := new(EgressExternalRuleSetLoadPhase)
	*p = x
	return p
}

func (x EgressExternalRuleSetLoadPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressExternalRuleSetLoadPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_egress_v1_policy_proto_enumTypes[2].Descriptor()
}

func (EgressExternalRuleSetLoadPhase) Type() protoreflect.EnumType {
	return &file_egress_v1_policy_proto_enumTypes[2]
}

func (x EgressExternalRuleSetLoadPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressExternalRuleSetLoadPhase.Descriptor instead.
func (EgressExternalRuleSetLoadPhase) EnumDescriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{2}
}

type EgressSyncPhase int32

const (
	EgressSyncPhase_EGRESS_SYNC_PHASE_UNSPECIFIED EgressSyncPhase = 0
	EgressSyncPhase_EGRESS_SYNC_PHASE_PENDING     EgressSyncPhase = 1
	EgressSyncPhase_EGRESS_SYNC_PHASE_SYNCED      EgressSyncPhase = 2
	EgressSyncPhase_EGRESS_SYNC_PHASE_FAILED      EgressSyncPhase = 3
)

// Enum value maps for EgressSyncPhase.
var (
	EgressSyncPhase_name = map[int32]string{
		0: "EGRESS_SYNC_PHASE_UNSPECIFIED",
		1: "EGRESS_SYNC_PHASE_PENDING",
		2: "EGRESS_SYNC_PHASE_SYNCED",
		3: "EGRESS_SYNC_PHASE_FAILED",
	}
	EgressSyncPhase_value = map[string]int32{
		"EGRESS_SYNC_PHASE_UNSPECIFIED": 0,
		"EGRESS_SYNC_PHASE_PENDING":     1,
		"EGRESS_SYNC_PHASE_SYNCED":      2,
		"EGRESS_SYNC_PHASE_FAILED":      3,
	}
)

func (x EgressSyncPhase) Enum() *EgressSyncPhase {
	p := new(EgressSyncPhase)
	*p = x
	return p
}

func (x EgressSyncPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressSyncPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_egress_v1_policy_proto_enumTypes[3].Descriptor()
}

func (EgressSyncPhase) Type() protoreflect.EnumType {
	return &file_egress_v1_policy_proto_enumTypes[3]
}

func (x EgressSyncPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressSyncPhase.Descriptor instead.
func (EgressSyncPhase) EnumDescriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{3}
}

// EgressPolicy declares one Istio-owned outbound policy intent.
type EgressPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PolicyId        string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Proxies         []*EgressProxy         `protobuf:"bytes,4,rep,name=proxies,proto3" json:"proxies,omitempty"`
	CustomRules     []*EgressRule          `protobuf:"bytes,5,rep,name=custom_rules,json=customRules,proto3" json:"custom_rules,omitempty"`
	ExternalRuleSet *EgressExternalRuleSet `protobuf:"bytes,6,opt,name=external_rule_set,json=externalRuleSet,proto3" json:"external_rule_set,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EgressPolicy) Reset() {
	*x = EgressPolicy{}
	mi := &file_egress_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicy) ProtoMessage() {}

func (x *EgressPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_egress_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicy.ProtoReflect.Descriptor instead.
func (*EgressPolicy) Descriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *EgressPolicy) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *EgressPolicy) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EgressPolicy) GetProxies() []*EgressProxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *EgressPolicy) GetCustomRules() []*EgressRule {
	if x != nil {
		return x.CustomRules
	}
	return nil
}

func (x *EgressPolicy) GetExternalRuleSet() *EgressExternalRuleSet {
	if x != nil {
		return x.ExternalRuleSet
	}
	return nil
}

// EgressProxy declares one selectable HTTP proxy target.
type EgressProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Protocol      EgressProxyProtocol    `protobuf:"varint,3,opt,name=protocol,proto3,enum=egress.v1.EgressProxyProtocol" json:"protocol,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressProxy) Reset() {
	*x = EgressProxy{}
	mi := &file_egress_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressProxy) ProtoMessage() {}

func (x *EgressProxy) ProtoReflect() protoreflect.Message {
	mi := &file_egress_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressProxy.ProtoReflect.Descriptor instead.
func (*EgressProxy) Descriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *EgressProxy) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *EgressProxy) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EgressProxy) GetProtocol() EgressProxyProtocol {
	if x != nil {
		return x.Protocol
	}
	return EgressProxyProtocol_EGRESS_PROXY_PROTOCOL_UNSPECIFIED
}

func (x *EgressProxy) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// EgressRule declares one user-controlled host matching rule.
type EgressRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Match         *EgressRuleMatch       `protobuf:"bytes,3,opt,name=match,proto3" json:"match,omitempty"`
	Action        EgressAction           `protobuf:"varint,4,opt,name=action,proto3,enum=egress.v1.EgressAction" json:"action,omitempty"`
	ProxyId       string                 `protobuf:"bytes,5,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRule) Reset() {
	*x = EgressRule{}
	mi := &file_egress_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRule) ProtoMessage() {}

func (x *EgressRule) ProtoReflect() protoreflect.Message {
	mi := &file_egress_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRule.ProtoReflect.Descriptor instead.
func (*EgressRule) Descriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *EgressRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *EgressRule) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EgressRule) GetMatch() *EgressRuleMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *EgressRule) GetAction() EgressAction {
	if x != nil {
		return x.Action
	}
	return EgressAction_EGRESS_ACTION_UNSPECIFIED
}

func (x *EgressRule) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

// EgressRuleMatch describes how one rule matches an outbound host.
type EgressRuleMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*EgressRuleMatch_HostExact
	//	*EgressRuleMatch_HostSuffix
	Kind          isEgressRuleMatch_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRuleMatch) Reset() {
	*x = EgressRuleMatch{}
	mi := &file_egress_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRuleMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRuleMatch) ProtoMessage() {}

func (x *EgressRuleMatch) ProtoReflect() protoreflect.Message {
	mi := &file_egress_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRuleMatch.ProtoReflect.Descriptor instead.
func (*EgressRuleMatch) Descriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *EgressRuleMatch) GetKind() isEgressRuleMatch_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *EgressRuleMatch) GetHostExact() string {
	if x != nil {
		if x, ok := x.Kind.(*EgressRuleMatch_HostExact); ok {
			return x.HostExact
		}
	}
	return ""
}

func (x *EgressRuleMatch) GetHostSuffix() string {
	if x != nil {
		if x, ok := x.Kind.(*EgressRuleMatch_HostSuffix); ok {
			return x.HostSuffix
		}
	}
	return ""
}

type isEgressRuleMatch_Kind interface {
	isEgressRuleMatch_Kind()
}

type EgressRuleMatch_HostExact struct {
	HostExact string `protobuf:"bytes,1,opt,name=host_exact,json=hostExact,proto3,oneof"`
}

type EgressRuleMatch_HostSuffix struct {
	// host_suffix matches the suffix domain itself and all subdomains.
	// For example: host_suffix="example.com" matches example.com and
	// api.example.com.
	HostSuffix string `protobuf:"bytes,2,opt,name=host_suffix,json=hostSuffix,proto3,oneof"`
}

func (*EgressRuleMatch_HostExact) isEgressRuleMatch_Kind() {}

func (*EgressRuleMatch_HostSuffix) isEgressRuleMatch_Kind() {}

// EgressExternalRuleSet declares the single user-configured AutoProxy source.
type EgressExternalRuleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUrl     string                 `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Action        EgressAction           `protobuf:"varint,3,opt,name=action,proto3,enum=egress.v1.EgressAction" json:"action,omitempty"`
	ProxyId       string                 `protobuf:"bytes,4,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressExternalRuleSet) Reset() {
	*x = EgressExternalRuleSet{}
	mi := &file_egress_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressExternalRuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressExternalRuleSet) ProtoMessage() {}

func (x *EgressExternalRuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_egress_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressExternalRuleSet.ProtoReflect.Descriptor instead.
func (*EgressExternalRuleSet) Descriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *EgressExternalRuleSet) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *EgressExternalRuleSet) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EgressExternalRuleSet) GetAction() EgressAction {
	if x != nil {
		return x.Action
	}
	return EgressAction_EGRESS_ACTION_UNSPECIFIED
}

func (x *EgressExternalRuleSet) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

// EgressExternalRuleSetStatus stores the latest observed external rule load result.
type EgressExternalRuleSetStatus struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Phase            EgressExternalRuleSetLoadPhase `protobuf:"varint,1,opt,name=phase,proto3,enum=egress.v1.EgressExternalRuleSetLoadPhase" json:"phase,omitempty"`
	SourceUrl        string                         `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	LoadedHostCount  int32                          `protobuf:"varint,3,opt,name=loaded_host_count,json=loadedHostCount,proto3" json:"loaded_host_count,omitempty"`
	SkippedRuleCount int32                          `protobuf:"varint,4,opt,name=skipped_rule_count,json=skippedRuleCount,proto3" json:"skipped_rule_count,omitempty"`
	Message          string                         `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	LoadedAt         *timestamppb.Timestamp         `protobuf:"bytes,6,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EgressExternalRuleSetStatus) Reset() {
	*x = EgressExternalRuleSetStatus{}
	mi := &file_egress_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressExternalRuleSetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressExternalRuleSetStatus) ProtoMessage() {}

func (x *EgressExternalRuleSetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_egress_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressExternalRuleSetStatus.ProtoReflect.Descriptor instead.
func (*EgressExternalRuleSetStatus) Descriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *EgressExternalRuleSetStatus) GetPhase() EgressExternalRuleSetLoadPhase {
	if x != nil {
		return x.Phase
	}
	return EgressExternalRuleSetLoadPhase_EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_UNSPECIFIED
}

func (x *EgressExternalRuleSetStatus) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *EgressExternalRuleSetStatus) GetLoadedHostCount() int32 {
	if x != nil {
		return x.LoadedHostCount
	}
	return 0
}

func (x *EgressExternalRuleSetStatus) GetSkippedRuleCount() int32 {
	if x != nil {
		return x.SkippedRuleCount
	}
	return 0
}

func (x *EgressExternalRuleSetStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EgressExternalRuleSetStatus) GetLoadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LoadedAt
	}
	return nil
}

// EgressResourceRef references one Istio egress resource.
type EgressResourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressResourceRef) Reset() {
	*x = EgressResourceRef{}
	mi := &file_egress_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressResourceRef) ProtoMessage() {}

func (x *EgressResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_egress_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressResourceRef.ProtoReflect.Descriptor instead.
func (*EgressResourceRef) Descriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *EgressResourceRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EgressResourceRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EgressResourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// EgressSyncStatus stores observed Istio egress sync state.
type EgressSyncStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Phase              EgressSyncPhase        `protobuf:"varint,1,opt,name=phase,proto3,enum=egress.v1.EgressSyncPhase" json:"phase,omitempty"`
	Reason             string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ObservedGeneration int64                  `protobuf:"varint,3,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	TargetGateway      *EgressResourceRef     `protobuf:"bytes,4,opt,name=target_gateway,json=targetGateway,proto3" json:"target_gateway,omitempty"`
	AppliedResources   []*EgressResourceRef   `protobuf:"bytes,5,rep,name=applied_resources,json=appliedResources,proto3" json:"applied_resources,omitempty"`
	LastSyncedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_synced_at,json=lastSyncedAt,proto3" json:"last_synced_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EgressSyncStatus) Reset() {
	*x = EgressSyncStatus{}
	mi := &file_egress_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressSyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressSyncStatus) ProtoMessage() {}

func (x *EgressSyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_egress_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressSyncStatus.ProtoReflect.Descriptor instead.
func (*EgressSyncStatus) Descriptor() ([]byte, []int) {
	return file_egress_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *EgressSyncStatus) GetPhase() EgressSyncPhase {
	if x != nil {
		return x.Phase
	}
	return EgressSyncPhase_EGRESS_SYNC_PHASE_UNSPECIFIED
}

func (x *EgressSyncStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EgressSyncStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *EgressSyncStatus) GetTargetGateway() *EgressResourceRef {
	if x != nil {
		return x.TargetGateway
	}
	return nil
}

func (x *EgressSyncStatus) GetAppliedResources() []*EgressResourceRef {
	if x != nil {
		return x.AppliedResources
	}
	return nil
}

func (x *EgressSyncStatus) GetLastSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncedAt
	}
	return nil
}

var File_egress_v1_policy_proto protoreflect.FileDescriptor

const file_egress_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x16egress/v1/policy.proto\x12\tegress.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x02\n" +
	"\fEgressPolicy\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x120\n" +
	"\aproxies\x18\x04 \x03(\v2\x16.egress.v1.EgressProxyR\aproxies\x128\n" +
	"\fcustom_rules\x18\x05 \x03(\v2\x15.egress.v1.EgressRuleR\vcustomRules\x12L\n" +
	"\x11external_rule_set\x18\x06 \x01(\v2 .egress.v1.EgressExternalRuleSetR\x0fexternalRuleSet\"\x99\x01\n" +
	"\vEgressProxy\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12:\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x1e.egress.v1.EgressProxyProtocolR\bprotocol\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\xc6\x01\n" +
	"\n" +
	"EgressRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x120\n" +
	"\x05match\x18\x03 \x01(\v2\x1a.egress.v1.EgressRuleMatchR\x05match\x12/\n" +
	"\x06action\x18\x04 \x01(\x0e2\x17.egress.v1.EgressActionR\x06action\x12\x19\n" +
	"\bproxy_id\x18\x05 \x01(\tR\aproxyId\"]\n" +
	"\x0fEgressRuleMatch\x12\x1f\n" +
	"\n" +
	"host_exact\x18\x01 \x01(\tH\x00R\thostExact\x12!\n" +
	"\vhost_suffix\x18\x02 \x01(\tH\x00R\n" +
	"hostSuffixB\x06\n" +
	"\x04kind\"\x9c\x01\n" +
	"\x15EgressExternalRuleSet\x12\x1d\n" +
	"\n" +
	"source_url\x18\x01 \x01(\tR\tsourceUrl\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12/\n" +
	"\x06action\x18\x03 \x01(\x0e2\x17.egress.v1.EgressActionR\x06action\x12\x19\n" +
	"\bproxy_id\x18\x04 \x01(\tR\aproxyId\"\xaa\x02\n" +
	"\x1bEgressExternalRuleSetStatus\x12?\n" +
	"\x05phase\x18\x01 \x01(\x0e2).egress.v1.EgressExternalRuleSetLoadPhaseR\x05phase\x12\x1d\n" +
	"\n" +
	"source_url\x18\x02 \x01(\tR\tsourceUrl\x12*\n" +
	"\x11loaded_host_count\x18\x03 \x01(\x05R\x0floadedHostCount\x12,\n" +
	"\x12skipped_rule_count\x18\x04 \x01(\x05R\x10skippedRuleCount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x127\n" +
	"\tloaded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bloadedAt\"Y\n" +
	"\x11EgressResourceRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xdf\x02\n" +
	"\x10EgressSyncStatus\x120\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1a.egress.v1.EgressSyncPhaseR\x05phase\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12/\n" +
	"\x13observed_generation\x18\x03 \x01(\x03R\x12observedGeneration\x12C\n" +
	"\x0etarget_gateway\x18\x04 \x01(\v2\x1c.egress.v1.EgressResourceRefR\rtargetGateway\x12I\n" +
	"\x11applied_resources\x18\x05 \x03(\v2\x1c.egress.v1.EgressResourceRefR\x10appliedResources\x12@\n" +
	"\x0elast_synced_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncedAt*`\n" +
	"\fEgressAction\x12\x1d\n" +
	"\x19EGRESS_ACTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EGRESS_ACTION_DIRECT\x10\x01\x12\x17\n" +
	"\x13EGRESS_ACTION_PROXY\x10\x02*\\\n" +
	"\x13EgressProxyProtocol\x12%\n" +
	"!EGRESS_PROXY_PROTOCOL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEGRESS_PROXY_PROTOCOL_HTTP\x10\x01*\x9b\x02\n" +
	"\x1eEgressExternalRuleSetLoadPhase\x123\n" +
	"/EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_UNSPECIFIED\x10\x00\x120\n" +
	",EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_DISABLED\x10\x01\x12.\n" +
	"*EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_LOADED\x10\x02\x122\n" +
	".EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_NOT_LOADED\x10\x03\x12.\n" +
	"*EGRESS_EXTERNAL_RULE_SET_LOAD_PHASE_FAILED\x10\x04*\x8f\x01\n" +
	"\x0fEgressSyncPhase\x12!\n" +
	"\x1dEGRESS_SYNC_PHASE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EGRESS_SYNC_PHASE_PENDING\x10\x01\x12\x1c\n" +
	"\x18EGRESS_SYNC_PHASE_SYNCED\x10\x02\x12\x1c\n" +
	"\x18EGRESS_SYNC_PHASE_FAILED\x10\x03B3Z1code-code.internal/go-contract/egress/v1;egressv1b\x06proto3"

var (
	file_egress_v1_policy_proto_rawDescOnce sync.Once
	file_egress_v1_policy_proto_rawDescData []byte
)

func file_egress_v1_policy_proto_rawDescGZIP() []byte {
	file_egress_v1_policy_proto_rawDescOnce.Do(func() {
		file_egress_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_egress_v1_policy_proto_rawDesc), len(file_egress_v1_policy_proto_rawDesc)))
	})
	return file_egress_v1_policy_proto_rawDescData
}

var file_egress_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_egress_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_egress_v1_policy_proto_goTypes = []any{
	(EgressAction)(0),                   // 0: egress.v1.EgressAction
	(EgressProxyProtocol)(0),            // 1: egress.v1.EgressProxyProtocol
	(EgressExternalRuleSetLoadPhase)(0), // 2: egress.v1.EgressExternalRuleSetLoadPhase
	(EgressSyncPhase)(0),                // 3: egress.v1.EgressSyncPhase
	(*EgressPolicy)(nil),                // 4: egress.v1.EgressPolicy
	(*EgressProxy)(nil),                 // 5: egress.v1.EgressProxy
	(*EgressRule)(nil),                  // 6: egress.v1.EgressRule
	(*EgressRuleMatch)(nil),             // 7: egress.v1.EgressRuleMatch
	(*EgressExternalRuleSet)(nil),       // 8: egress.v1.EgressExternalRuleSet
	(*EgressExternalRuleSetStatus)(nil), // 9: egress.v1.EgressExternalRuleSetStatus
	(*EgressResourceRef)(nil),           // 10: egress.v1.EgressResourceRef
	(*EgressSyncStatus)(nil),            // 11: egress.v1.EgressSyncStatus
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_egress_v1_policy_proto_depIdxs = []int32{
	5,  // 0: egress.v1.EgressPolicy.proxies:type_name -> egress.v1.EgressProxy
	6,  // 1: egress.v1.EgressPolicy.custom_rules:type_name -> egress.v1.EgressRule
	8,  // 2: egress.v1.EgressPolicy.external_rule_set:type_name -> egress.v1.EgressExternalRuleSet
	1,  // 3: egress.v1.EgressProxy.protocol:type_name -> egress.v1.EgressProxyProtocol
	7,  // 4: egress.v1.EgressRule.match:type_name -> egress.v1.EgressRuleMatch
	0,  // 5: egress.v1.EgressRule.action:type_name -> egress.v1.EgressAction
	0,  // 6: egress.v1.EgressExternalRuleSet.action:type_name -> egress.v1.EgressAction
	2,  // 7: egress.v1.EgressExternalRuleSetStatus.phase:type_name -> egress.v1.EgressExternalRuleSetLoadPhase
	12, // 8: egress.v1.EgressExternalRuleSetStatus.loaded_at:type_name -> google.protobuf.Timestamp
	3,  // 9: egress.v1.EgressSyncStatus.phase:type_name -> egress.v1.EgressSyncPhase
	10, // 10: egress.v1.EgressSyncStatus.target_gateway:type_name -> egress.v1.EgressResourceRef
	10, // 11: egress.v1.EgressSyncStatus.applied_resources:type_name -> egress.v1.EgressResourceRef
	12, // 12: egress.v1.EgressSyncStatus.last_synced_at:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_egress_v1_policy_proto_init() }
func file_egress_v1_policy_proto_init() {
	if File_egress_v1_policy_proto != nil {
		return
	}
	file_egress_v1_policy_proto_msgTypes[3].OneofWrappers = []any{
		(*EgressRuleMatch_HostExact)(nil),
		(*EgressRuleMatch_HostSuffix)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_egress_v1_policy_proto_rawDesc), len(file_egress_v1_policy_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_egress_v1_policy_proto_goTypes,
		DependencyIndexes: file_egress_v1_policy_proto_depIdxs,
		EnumInfos:         file_egress_v1_policy_proto_enumTypes,
		MessageInfos:      file_egress_v1_policy_proto_msgTypes,
	}.Build()
	File_egress_v1_policy_proto = out.File
	file_egress_v1_policy_proto_goTypes = nil
	file_egress_v1_policy_proto_depIdxs = nil
}
