apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/name: image-preflight
spec:
  automountServiceAccountToken: false
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: preflight
      image: __IMAGE__
      imagePullPolicy: __IMAGE_PULL_POLICY__
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
