// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: provider/v1/provider.proto

package providerv1

import (
	v11 "code-code.internal/go-contract/api_protocol/v1"
	v1 "code-code.internal/go-contract/credential/v1"
	v12 "code-code.internal/go-contract/model/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderSurfaceModelCatalogProbeMethod int32

const (
	ProviderSurfaceModelCatalogProbeMethod_PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_UNSPECIFIED          ProviderSurfaceModelCatalogProbeMethod = 0
	ProviderSurfaceModelCatalogProbeMethod_PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_PROTOCOL_BEST_EFFORT ProviderSurfaceModelCatalogProbeMethod = 1
	ProviderSurfaceModelCatalogProbeMethod_PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_STATIC               ProviderSurfaceModelCatalogProbeMethod = 2
	ProviderSurfaceModelCatalogProbeMethod_PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_ADAPTER              ProviderSurfaceModelCatalogProbeMethod = 3
)

// Enum value maps for ProviderSurfaceModelCatalogProbeMethod.
var (
	ProviderSurfaceModelCatalogProbeMethod_name = map[int32]string{
		0: "PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_UNSPECIFIED",
		1: "PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_PROTOCOL_BEST_EFFORT",
		2: "PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_STATIC",
		3: "PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_ADAPTER",
	}
	ProviderSurfaceModelCatalogProbeMethod_value = map[string]int32{
		"PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_UNSPECIFIED":          0,
		"PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_PROTOCOL_BEST_EFFORT": 1,
		"PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_STATIC":               2,
		"PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_ADAPTER":              3,
	}
)

func (x ProviderSurfaceModelCatalogProbeMethod) Enum() *ProviderSurfaceModelCatalogProbeMethod {
	p := new(ProviderSurfaceModelCatalogProbeMethod)
	*p = x
	return p
}

func (x ProviderSurfaceModelCatalogProbeMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderSurfaceModelCatalogProbeMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[0].Descriptor()
}

func (ProviderSurfaceModelCatalogProbeMethod) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[0]
}

func (x ProviderSurfaceModelCatalogProbeMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderSurfaceModelCatalogProbeMethod.Descriptor instead.
func (ProviderSurfaceModelCatalogProbeMethod) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

// ProviderSurfaceKind identifies the semantic kind of one provider surface.
type ProviderSurfaceKind int32

const (
	ProviderSurfaceKind_PROVIDER_SURFACE_KIND_UNSPECIFIED ProviderSurfaceKind = 0
	ProviderSurfaceKind_PROVIDER_SURFACE_KIND_API         ProviderSurfaceKind = 1
	ProviderSurfaceKind_PROVIDER_SURFACE_KIND_CLI         ProviderSurfaceKind = 2
	ProviderSurfaceKind_PROVIDER_SURFACE_KIND_WEB         ProviderSurfaceKind = 3
)

// Enum value maps for ProviderSurfaceKind.
var (
	ProviderSurfaceKind_name = map[int32]string{
		0: "PROVIDER_SURFACE_KIND_UNSPECIFIED",
		1: "PROVIDER_SURFACE_KIND_API",
		2: "PROVIDER_SURFACE_KIND_CLI",
		3: "PROVIDER_SURFACE_KIND_WEB",
	}
	ProviderSurfaceKind_value = map[string]int32{
		"PROVIDER_SURFACE_KIND_UNSPECIFIED": 0,
		"PROVIDER_SURFACE_KIND_API":         1,
		"PROVIDER_SURFACE_KIND_CLI":         2,
		"PROVIDER_SURFACE_KIND_WEB":         3,
	}
)

func (x ProviderSurfaceKind) Enum() *ProviderSurfaceKind {
	p := new(ProviderSurfaceKind)
	*p = x
	return p
}

func (x ProviderSurfaceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderSurfaceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[1].Descriptor()
}

func (ProviderSurfaceKind) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[1]
}

func (x ProviderSurfaceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderSurfaceKind.Descriptor instead.
func (ProviderSurfaceKind) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

type ProviderSurfaceSourceKind int32

const (
	ProviderSurfaceSourceKind_PROVIDER_SURFACE_SOURCE_KIND_UNSPECIFIED ProviderSurfaceSourceKind = 0
	ProviderSurfaceSourceKind_PROVIDER_SURFACE_SOURCE_KIND_VENDOR      ProviderSurfaceSourceKind = 1
	ProviderSurfaceSourceKind_PROVIDER_SURFACE_SOURCE_KIND_CLI         ProviderSurfaceSourceKind = 2
)

// Enum value maps for ProviderSurfaceSourceKind.
var (
	ProviderSurfaceSourceKind_name = map[int32]string{
		0: "PROVIDER_SURFACE_SOURCE_KIND_UNSPECIFIED",
		1: "PROVIDER_SURFACE_SOURCE_KIND_VENDOR",
		2: "PROVIDER_SURFACE_SOURCE_KIND_CLI",
	}
	ProviderSurfaceSourceKind_value = map[string]int32{
		"PROVIDER_SURFACE_SOURCE_KIND_UNSPECIFIED": 0,
		"PROVIDER_SURFACE_SOURCE_KIND_VENDOR":      1,
		"PROVIDER_SURFACE_SOURCE_KIND_CLI":         2,
	}
)

func (x ProviderSurfaceSourceKind) Enum() *ProviderSurfaceSourceKind {
	p := new(ProviderSurfaceSourceKind)
	*p = x
	return p
}

func (x ProviderSurfaceSourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderSurfaceSourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[2].Descriptor()
}

func (ProviderSurfaceSourceKind) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[2]
}

func (x ProviderSurfaceSourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderSurfaceSourceKind.Descriptor instead.
func (ProviderSurfaceSourceKind) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

// ProviderSurfaceOrigin identifies whether a surface is derived from
// platform metadata or defined manually by the user.
type ProviderSurfaceOrigin int32

const (
	ProviderSurfaceOrigin_PROVIDER_SURFACE_ORIGIN_UNSPECIFIED ProviderSurfaceOrigin = 0
	ProviderSurfaceOrigin_PROVIDER_SURFACE_ORIGIN_DERIVED     ProviderSurfaceOrigin = 1
	ProviderSurfaceOrigin_PROVIDER_SURFACE_ORIGIN_MANUAL      ProviderSurfaceOrigin = 2
)

// Enum value maps for ProviderSurfaceOrigin.
var (
	ProviderSurfaceOrigin_name = map[int32]string{
		0: "PROVIDER_SURFACE_ORIGIN_UNSPECIFIED",
		1: "PROVIDER_SURFACE_ORIGIN_DERIVED",
		2: "PROVIDER_SURFACE_ORIGIN_MANUAL",
	}
	ProviderSurfaceOrigin_value = map[string]int32{
		"PROVIDER_SURFACE_ORIGIN_UNSPECIFIED": 0,
		"PROVIDER_SURFACE_ORIGIN_DERIVED":     1,
		"PROVIDER_SURFACE_ORIGIN_MANUAL":      2,
	}
)

func (x ProviderSurfaceOrigin) Enum() *ProviderSurfaceOrigin {
	p := new(ProviderSurfaceOrigin)
	*p = x
	return p
}

func (x ProviderSurfaceOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderSurfaceOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[3].Descriptor()
}

func (ProviderSurfaceOrigin) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[3]
}

func (x ProviderSurfaceOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderSurfaceOrigin.Descriptor instead.
func (ProviderSurfaceOrigin) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

// CatalogSource identifies where one model catalog comes from.
type CatalogSource int32

const (
	CatalogSource_CATALOG_SOURCE_UNSPECIFIED     CatalogSource = 0
	CatalogSource_CATALOG_SOURCE_MODEL_SERVICE   CatalogSource = 1
	CatalogSource_CATALOG_SOURCE_PROTOCOL_QUERY  CatalogSource = 2
	CatalogSource_CATALOG_SOURCE_FALLBACK_CONFIG CatalogSource = 3
	CatalogSource_CATALOG_SOURCE_VENDOR_PRESET   CatalogSource = 4
)

// Enum value maps for CatalogSource.
var (
	CatalogSource_name = map[int32]string{
		0: "CATALOG_SOURCE_UNSPECIFIED",
		1: "CATALOG_SOURCE_MODEL_SERVICE",
		2: "CATALOG_SOURCE_PROTOCOL_QUERY",
		3: "CATALOG_SOURCE_FALLBACK_CONFIG",
		4: "CATALOG_SOURCE_VENDOR_PRESET",
	}
	CatalogSource_value = map[string]int32{
		"CATALOG_SOURCE_UNSPECIFIED":     0,
		"CATALOG_SOURCE_MODEL_SERVICE":   1,
		"CATALOG_SOURCE_PROTOCOL_QUERY":  2,
		"CATALOG_SOURCE_FALLBACK_CONFIG": 3,
		"CATALOG_SOURCE_VENDOR_PRESET":   4,
	}
)

func (x CatalogSource) Enum() *CatalogSource {
	p := new(CatalogSource)
	*p = x
	return p
}

func (x CatalogSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatalogSource) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[4].Descriptor()
}

func (CatalogSource) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[4]
}

func (x CatalogSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatalogSource.Descriptor instead.
func (CatalogSource) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

// ProviderSurface describes one stable provider integration surface.
type ProviderSurface struct {
	state                    protoimpl.MessageState  `protogen:"open.v1"`
	SurfaceId                string                  `protobuf:"bytes,1,opt,name=surface_id,json=surfaceId,proto3" json:"surface_id,omitempty"`
	DisplayName              string                  `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SupportedCredentialKinds []v1.CredentialKind     `protobuf:"varint,3,rep,packed,name=supported_credential_kinds,json=supportedCredentialKinds,proto3,enum=credential.v1.CredentialKind" json:"supported_credential_kinds,omitempty"`
	Capabilities             *ProviderCapabilities   `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Kind                     ProviderSurfaceKind     `protobuf:"varint,6,opt,name=kind,proto3,enum=provider.v1.ProviderSurfaceKind" json:"kind,omitempty"`
	Api                      *ProviderSurfaceAPISpec `protobuf:"bytes,8,opt,name=api,proto3" json:"api,omitempty"`
	Probes                   *ProviderSurfaceProbes  `protobuf:"bytes,9,opt,name=probes,proto3" json:"probes,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ProviderSurface) Reset() {
	*x = ProviderSurface{}
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurface) ProtoMessage() {}

func (x *ProviderSurface) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurface.ProtoReflect.Descriptor instead.
func (*ProviderSurface) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderSurface) GetSurfaceId() string {
	if x != nil {
		return x.SurfaceId
	}
	return ""
}

func (x *ProviderSurface) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderSurface) GetSupportedCredentialKinds() []v1.CredentialKind {
	if x != nil {
		return x.SupportedCredentialKinds
	}
	return nil
}

func (x *ProviderSurface) GetCapabilities() *ProviderCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderSurface) GetKind() ProviderSurfaceKind {
	if x != nil {
		return x.Kind
	}
	return ProviderSurfaceKind_PROVIDER_SURFACE_KIND_UNSPECIFIED
}

func (x *ProviderSurface) GetApi() *ProviderSurfaceAPISpec {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *ProviderSurface) GetProbes() *ProviderSurfaceProbes {
	if x != nil {
		return x.Probes
	}
	return nil
}

type ProviderSurfaceAPISpec struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SupportedProtocols []v11.Protocol         `protobuf:"varint,1,rep,packed,name=supported_protocols,json=supportedProtocols,proto3,enum=api_protocol.v1.Protocol" json:"supported_protocols,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProviderSurfaceAPISpec) Reset() {
	*x = ProviderSurfaceAPISpec{}
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurfaceAPISpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurfaceAPISpec) ProtoMessage() {}

func (x *ProviderSurfaceAPISpec) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurfaceAPISpec.ProtoReflect.Descriptor instead.
func (*ProviderSurfaceAPISpec) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderSurfaceAPISpec) GetSupportedProtocols() []v11.Protocol {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

type ProviderSurfaceProbes struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	ModelCatalog  *ProviderSurfaceModelCatalogProbe `protobuf:"bytes,1,opt,name=model_catalog,json=modelCatalog,proto3" json:"model_catalog,omitempty"`
	Quota         *ProviderSurfaceQuotaProbe        `protobuf:"bytes,2,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSurfaceProbes) Reset() {
	*x = ProviderSurfaceProbes{}
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurfaceProbes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurfaceProbes) ProtoMessage() {}

func (x *ProviderSurfaceProbes) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurfaceProbes.ProtoReflect.Descriptor instead.
func (*ProviderSurfaceProbes) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderSurfaceProbes) GetModelCatalog() *ProviderSurfaceModelCatalogProbe {
	if x != nil {
		return x.ModelCatalog
	}
	return nil
}

func (x *ProviderSurfaceProbes) GetQuota() *ProviderSurfaceQuotaProbe {
	if x != nil {
		return x.Quota
	}
	return nil
}

type ProviderSurfaceModelCatalogProbe struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Method        ProviderSurfaceModelCatalogProbeMethod `protobuf:"varint,1,opt,name=method,proto3,enum=provider.v1.ProviderSurfaceModelCatalogProbeMethod" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSurfaceModelCatalogProbe) Reset() {
	*x = ProviderSurfaceModelCatalogProbe{}
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurfaceModelCatalogProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurfaceModelCatalogProbe) ProtoMessage() {}

func (x *ProviderSurfaceModelCatalogProbe) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurfaceModelCatalogProbe.ProtoReflect.Descriptor instead.
func (*ProviderSurfaceModelCatalogProbe) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderSurfaceModelCatalogProbe) GetMethod() ProviderSurfaceModelCatalogProbeMethod {
	if x != nil {
		return x.Method
	}
	return ProviderSurfaceModelCatalogProbeMethod_PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_UNSPECIFIED
}

type ProviderSurfaceQuotaProbe struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SchemaId      string                     `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Args          []*ProviderSurfaceProbeArg `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	DisplayName   string                     `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSurfaceQuotaProbe) Reset() {
	*x = ProviderSurfaceQuotaProbe{}
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurfaceQuotaProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurfaceQuotaProbe) ProtoMessage() {}

func (x *ProviderSurfaceQuotaProbe) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurfaceQuotaProbe.ProtoReflect.Descriptor instead.
func (*ProviderSurfaceQuotaProbe) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderSurfaceQuotaProbe) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ProviderSurfaceQuotaProbe) GetArgs() []*ProviderSurfaceProbeArg {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProviderSurfaceQuotaProbe) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderSurfaceQuotaProbe) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ProviderSurfaceProbeArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArgId         string                 `protobuf:"bytes,1,opt,name=arg_id,json=argId,proto3" json:"arg_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Sensitive     bool                   `protobuf:"varint,5,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	Multiline     bool                   `protobuf:"varint,6,opt,name=multiline,proto3" json:"multiline,omitempty"`
	Placeholder   string                 `protobuf:"bytes,7,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSurfaceProbeArg) Reset() {
	*x = ProviderSurfaceProbeArg{}
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurfaceProbeArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurfaceProbeArg) ProtoMessage() {}

func (x *ProviderSurfaceProbeArg) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurfaceProbeArg.ProtoReflect.Descriptor instead.
func (*ProviderSurfaceProbeArg) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderSurfaceProbeArg) GetArgId() string {
	if x != nil {
		return x.ArgId
	}
	return ""
}

func (x *ProviderSurfaceProbeArg) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderSurfaceProbeArg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProviderSurfaceProbeArg) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ProviderSurfaceProbeArg) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *ProviderSurfaceProbeArg) GetMultiline() bool {
	if x != nil {
		return x.Multiline
	}
	return false
}

func (x *ProviderSurfaceProbeArg) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

// Provider describes one user-configured provider aggregate.
type Provider struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ProviderId    string                    `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	DisplayName   string                    `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Surfaces      []*ProviderSurfaceBinding `protobuf:"bytes,7,rep,name=surfaces,proto3" json:"surfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *Provider) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Provider) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Provider) GetSurfaces() []*ProviderSurfaceBinding {
	if x != nil {
		return x.Surfaces
	}
	return nil
}

// ProviderCapabilities describes which capabilities one provider exposes natively.
type ProviderCapabilities struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SupportsModelOverride     bool                   `protobuf:"varint,1,opt,name=supports_model_override,json=supportsModelOverride,proto3" json:"supports_model_override,omitempty"`
	SupportsModelCatalogProbe bool                   `protobuf:"varint,3,opt,name=supports_model_catalog_probe,json=supportsModelCatalogProbe,proto3" json:"supports_model_catalog_probe,omitempty"`
	SupportsQuotaProbe        bool                   `protobuf:"varint,4,opt,name=supports_quota_probe,json=supportsQuotaProbe,proto3" json:"supports_quota_probe,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ProviderCapabilities) Reset() {
	*x = ProviderCapabilities{}
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCapabilities) ProtoMessage() {}

func (x *ProviderCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCapabilities.ProtoReflect.Descriptor instead.
func (*ProviderCapabilities) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ProviderCapabilities) GetSupportsModelOverride() bool {
	if x != nil {
		return x.SupportsModelOverride
	}
	return false
}

func (x *ProviderCapabilities) GetSupportsModelCatalogProbe() bool {
	if x != nil {
		return x.SupportsModelCatalogProbe
	}
	return false
}

func (x *ProviderCapabilities) GetSupportsQuotaProbe() bool {
	if x != nil {
		return x.SupportsQuotaProbe
	}
	return false
}

// ProviderSurfaceBinding describes one configured provider surface.
type ProviderSurfaceBinding struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SurfaceId             string                 `protobuf:"bytes,1,opt,name=surface_id,json=surfaceId,proto3" json:"surface_id,omitempty"`
	ProviderCredentialRef *ProviderCredentialRef `protobuf:"bytes,12,opt,name=provider_credential_ref,json=providerCredentialRef,proto3" json:"provider_credential_ref,omitempty"`
	// Concrete callable runtime bound to this surface.
	Runtime       *ProviderSurfaceRuntime   `protobuf:"bytes,13,opt,name=runtime,proto3" json:"runtime,omitempty"`
	SourceRef     *ProviderSurfaceSourceRef `protobuf:"bytes,17,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSurfaceBinding) Reset() {
	*x = ProviderSurfaceBinding{}
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurfaceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurfaceBinding) ProtoMessage() {}

func (x *ProviderSurfaceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurfaceBinding.ProtoReflect.Descriptor instead.
func (*ProviderSurfaceBinding) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderSurfaceBinding) GetSurfaceId() string {
	if x != nil {
		return x.SurfaceId
	}
	return ""
}

func (x *ProviderSurfaceBinding) GetProviderCredentialRef() *ProviderCredentialRef {
	if x != nil {
		return x.ProviderCredentialRef
	}
	return nil
}

func (x *ProviderSurfaceBinding) GetRuntime() *ProviderSurfaceRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *ProviderSurfaceBinding) GetSourceRef() *ProviderSurfaceSourceRef {
	if x != nil {
		return x.SourceRef
	}
	return nil
}

// ProviderSurfaceSourceRef identifies the package/source that owns surface
// metadata and model catalog capability.
type ProviderSurfaceSourceRef struct {
	state protoimpl.MessageState    `protogen:"open.v1"`
	Kind  ProviderSurfaceSourceKind `protobuf:"varint,1,opt,name=kind,proto3,enum=provider.v1.ProviderSurfaceSourceKind" json:"kind,omitempty"`
	// Package owner id, for example vendor_id or cli_id.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Package-local surface id.
	SurfaceId     string `protobuf:"bytes,3,opt,name=surface_id,json=surfaceId,proto3" json:"surface_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSurfaceSourceRef) Reset() {
	*x = ProviderSurfaceSourceRef{}
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurfaceSourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurfaceSourceRef) ProtoMessage() {}

func (x *ProviderSurfaceSourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurfaceSourceRef.ProtoReflect.Descriptor instead.
func (*ProviderSurfaceSourceRef) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderSurfaceSourceRef) GetKind() ProviderSurfaceSourceKind {
	if x != nil {
		return x.Kind
	}
	return ProviderSurfaceSourceKind_PROVIDER_SURFACE_SOURCE_KIND_UNSPECIFIED
}

func (x *ProviderSurfaceSourceRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderSurfaceSourceRef) GetSurfaceId() string {
	if x != nil {
		return x.SurfaceId
	}
	return ""
}

// ProviderCredentialRef references a provider credential by stable identity.
type ProviderCredentialRef struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProviderCredentialId string                 `protobuf:"bytes,1,opt,name=provider_credential_id,json=providerCredentialId,proto3" json:"provider_credential_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProviderCredentialRef) Reset() {
	*x = ProviderCredentialRef{}
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCredentialRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCredentialRef) ProtoMessage() {}

func (x *ProviderCredentialRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCredentialRef.ProtoReflect.Descriptor instead.
func (*ProviderCredentialRef) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderCredentialRef) GetProviderCredentialId() string {
	if x != nil {
		return x.ProviderCredentialId
	}
	return ""
}

// ProviderRuntimeRef references one callable surface inside one provider.
type ProviderRuntimeRef struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProviderId string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	SurfaceId  string                 `protobuf:"bytes,2,opt,name=surface_id,json=surfaceId,proto3" json:"surface_id,omitempty"`
	// Types that are valid to be assigned to Access:
	//
	//	*ProviderRuntimeRef_Api
	//	*ProviderRuntimeRef_Cli
	Access        isProviderRuntimeRef_Access `protobuf_oneof:"access"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderRuntimeRef) Reset() {
	*x = ProviderRuntimeRef{}
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRuntimeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRuntimeRef) ProtoMessage() {}

func (x *ProviderRuntimeRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRuntimeRef.ProtoReflect.Descriptor instead.
func (*ProviderRuntimeRef) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderRuntimeRef) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderRuntimeRef) GetSurfaceId() string {
	if x != nil {
		return x.SurfaceId
	}
	return ""
}

func (x *ProviderRuntimeRef) GetAccess() isProviderRuntimeRef_Access {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *ProviderRuntimeRef) GetApi() *ProviderRuntimeAPIRef {
	if x != nil {
		if x, ok := x.Access.(*ProviderRuntimeRef_Api); ok {
			return x.Api
		}
	}
	return nil
}

func (x *ProviderRuntimeRef) GetCli() *ProviderRuntimeCLIRef {
	if x != nil {
		if x, ok := x.Access.(*ProviderRuntimeRef_Cli); ok {
			return x.Cli
		}
	}
	return nil
}

type isProviderRuntimeRef_Access interface {
	isProviderRuntimeRef_Access()
}

type ProviderRuntimeRef_Api struct {
	Api *ProviderRuntimeAPIRef `protobuf:"bytes,3,opt,name=api,proto3,oneof"`
}

type ProviderRuntimeRef_Cli struct {
	Cli *ProviderRuntimeCLIRef `protobuf:"bytes,4,opt,name=cli,proto3,oneof"`
}

func (*ProviderRuntimeRef_Api) isProviderRuntimeRef_Access() {}

func (*ProviderRuntimeRef_Cli) isProviderRuntimeRef_Access() {}

type ProviderRuntimeAPIRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      v11.Protocol           `protobuf:"varint,1,opt,name=protocol,proto3,enum=api_protocol.v1.Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderRuntimeAPIRef) Reset() {
	*x = ProviderRuntimeAPIRef{}
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRuntimeAPIRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRuntimeAPIRef) ProtoMessage() {}

func (x *ProviderRuntimeAPIRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRuntimeAPIRef.ProtoReflect.Descriptor instead.
func (*ProviderRuntimeAPIRef) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *ProviderRuntimeAPIRef) GetProtocol() v11.Protocol {
	if x != nil {
		return x.Protocol
	}
	return v11.Protocol(0)
}

type ProviderRuntimeCLIRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderRuntimeCLIRef) Reset() {
	*x = ProviderRuntimeCLIRef{}
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRuntimeCLIRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRuntimeCLIRef) ProtoMessage() {}

func (x *ProviderRuntimeCLIRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRuntimeCLIRef.ProtoReflect.Descriptor instead.
func (*ProviderRuntimeCLIRef) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{13}
}

type ProviderRunBinding struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProviderId         string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	CredentialGrantRef *v1.CredentialGrantRef `protobuf:"bytes,2,opt,name=credential_grant_ref,json=credentialGrantRef,proto3" json:"credential_grant_ref,omitempty"`
	RuntimeUrl         string                 `protobuf:"bytes,3,opt,name=runtime_url,json=runtimeUrl,proto3" json:"runtime_url,omitempty"`
	MaterializationKey string                 `protobuf:"bytes,4,opt,name=materialization_key,json=materializationKey,proto3" json:"materialization_key,omitempty"`
	RuntimeCliId       string                 `protobuf:"bytes,5,opt,name=runtime_cli_id,json=runtimeCliId,proto3" json:"runtime_cli_id,omitempty"`
	ProviderModelId    string                 `protobuf:"bytes,6,opt,name=provider_model_id,json=providerModelId,proto3" json:"provider_model_id,omitempty"`
	CanonicalModelId   string                 `protobuf:"bytes,7,opt,name=canonical_model_id,json=canonicalModelId,proto3" json:"canonical_model_id,omitempty"`
	SourceModelId      string                 `protobuf:"bytes,8,opt,name=source_model_id,json=sourceModelId,proto3" json:"source_model_id,omitempty"`
	// Types that are valid to be assigned to Access:
	//
	//	*ProviderRunBinding_Api
	//	*ProviderRunBinding_Cli
	Access        isProviderRunBinding_Access `protobuf_oneof:"access"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderRunBinding) Reset() {
	*x = ProviderRunBinding{}
	mi := &file_provider_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRunBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRunBinding) ProtoMessage() {}

func (x *ProviderRunBinding) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRunBinding.ProtoReflect.Descriptor instead.
func (*ProviderRunBinding) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *ProviderRunBinding) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderRunBinding) GetCredentialGrantRef() *v1.CredentialGrantRef {
	if x != nil {
		return x.CredentialGrantRef
	}
	return nil
}

func (x *ProviderRunBinding) GetRuntimeUrl() string {
	if x != nil {
		return x.RuntimeUrl
	}
	return ""
}

func (x *ProviderRunBinding) GetMaterializationKey() string {
	if x != nil {
		return x.MaterializationKey
	}
	return ""
}

func (x *ProviderRunBinding) GetRuntimeCliId() string {
	if x != nil {
		return x.RuntimeCliId
	}
	return ""
}

func (x *ProviderRunBinding) GetProviderModelId() string {
	if x != nil {
		return x.ProviderModelId
	}
	return ""
}

func (x *ProviderRunBinding) GetCanonicalModelId() string {
	if x != nil {
		return x.CanonicalModelId
	}
	return ""
}

func (x *ProviderRunBinding) GetSourceModelId() string {
	if x != nil {
		return x.SourceModelId
	}
	return ""
}

func (x *ProviderRunBinding) GetAccess() isProviderRunBinding_Access {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *ProviderRunBinding) GetApi() *ProviderRunAPIAccess {
	if x != nil {
		if x, ok := x.Access.(*ProviderRunBinding_Api); ok {
			return x.Api
		}
	}
	return nil
}

func (x *ProviderRunBinding) GetCli() *ProviderRunCLIAccess {
	if x != nil {
		if x, ok := x.Access.(*ProviderRunBinding_Cli); ok {
			return x.Cli
		}
	}
	return nil
}

type isProviderRunBinding_Access interface {
	isProviderRunBinding_Access()
}

type ProviderRunBinding_Api struct {
	Api *ProviderRunAPIAccess `protobuf:"bytes,9,opt,name=api,proto3,oneof"`
}

type ProviderRunBinding_Cli struct {
	Cli *ProviderRunCLIAccess `protobuf:"bytes,10,opt,name=cli,proto3,oneof"`
}

func (*ProviderRunBinding_Api) isProviderRunBinding_Access() {}

func (*ProviderRunBinding_Cli) isProviderRunBinding_Access() {}

type ProviderRunAPIAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      v11.Protocol           `protobuf:"varint,1,opt,name=protocol,proto3,enum=api_protocol.v1.Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderRunAPIAccess) Reset() {
	*x = ProviderRunAPIAccess{}
	mi := &file_provider_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRunAPIAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRunAPIAccess) ProtoMessage() {}

func (x *ProviderRunAPIAccess) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRunAPIAccess.ProtoReflect.Descriptor instead.
func (*ProviderRunAPIAccess) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *ProviderRunAPIAccess) GetProtocol() v11.Protocol {
	if x != nil {
		return x.Protocol
	}
	return v11.Protocol(0)
}

type ProviderRunCLIAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderRunCLIAccess) Reset() {
	*x = ProviderRunCLIAccess{}
	mi := &file_provider_v1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRunCLIAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRunCLIAccess) ProtoMessage() {}

func (x *ProviderRunCLIAccess) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRunCLIAccess.ProtoReflect.Descriptor instead.
func (*ProviderRunCLIAccess) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{16}
}

// ProviderSurfaceRuntime describes how one configured provider surface is used.
type ProviderSurfaceRuntime struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DisplayName string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Origin      ProviderSurfaceOrigin  `protobuf:"varint,2,opt,name=origin,proto3,enum=provider.v1.ProviderSurfaceOrigin" json:"origin,omitempty"`
	Catalog     *ProviderModelCatalog  `protobuf:"bytes,4,opt,name=catalog,proto3" json:"catalog,omitempty"`
	// Types that are valid to be assigned to Access:
	//
	//	*ProviderSurfaceRuntime_Api
	//	*ProviderSurfaceRuntime_Cli
	Access              isProviderSurfaceRuntime_Access `protobuf_oneof:"access"`
	ModelCatalogProbeId string                          `protobuf:"bytes,10,opt,name=model_catalog_probe_id,json=modelCatalogProbeId,proto3" json:"model_catalog_probe_id,omitempty"`
	QuotaProbeId        string                          `protobuf:"bytes,11,opt,name=quota_probe_id,json=quotaProbeId,proto3" json:"quota_probe_id,omitempty"`
	EgressRulesetId     string                          `protobuf:"bytes,12,opt,name=egress_ruleset_id,json=egressRulesetId,proto3" json:"egress_ruleset_id,omitempty"`
	MitmId              string                          `protobuf:"bytes,13,opt,name=mitm_id,json=mitmId,proto3" json:"mitm_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProviderSurfaceRuntime) Reset() {
	*x = ProviderSurfaceRuntime{}
	mi := &file_provider_v1_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSurfaceRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSurfaceRuntime) ProtoMessage() {}

func (x *ProviderSurfaceRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSurfaceRuntime.ProtoReflect.Descriptor instead.
func (*ProviderSurfaceRuntime) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{17}
}

func (x *ProviderSurfaceRuntime) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderSurfaceRuntime) GetOrigin() ProviderSurfaceOrigin {
	if x != nil {
		return x.Origin
	}
	return ProviderSurfaceOrigin_PROVIDER_SURFACE_ORIGIN_UNSPECIFIED
}

func (x *ProviderSurfaceRuntime) GetCatalog() *ProviderModelCatalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *ProviderSurfaceRuntime) GetAccess() isProviderSurfaceRuntime_Access {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *ProviderSurfaceRuntime) GetApi() *ProviderAPISurfaceRuntime {
	if x != nil {
		if x, ok := x.Access.(*ProviderSurfaceRuntime_Api); ok {
			return x.Api
		}
	}
	return nil
}

func (x *ProviderSurfaceRuntime) GetCli() *ProviderCLISurfaceRuntime {
	if x != nil {
		if x, ok := x.Access.(*ProviderSurfaceRuntime_Cli); ok {
			return x.Cli
		}
	}
	return nil
}

func (x *ProviderSurfaceRuntime) GetModelCatalogProbeId() string {
	if x != nil {
		return x.ModelCatalogProbeId
	}
	return ""
}

func (x *ProviderSurfaceRuntime) GetQuotaProbeId() string {
	if x != nil {
		return x.QuotaProbeId
	}
	return ""
}

func (x *ProviderSurfaceRuntime) GetEgressRulesetId() string {
	if x != nil {
		return x.EgressRulesetId
	}
	return ""
}

func (x *ProviderSurfaceRuntime) GetMitmId() string {
	if x != nil {
		return x.MitmId
	}
	return ""
}

type isProviderSurfaceRuntime_Access interface {
	isProviderSurfaceRuntime_Access()
}

type ProviderSurfaceRuntime_Api struct {
	Api *ProviderAPISurfaceRuntime `protobuf:"bytes,5,opt,name=api,proto3,oneof"`
}

type ProviderSurfaceRuntime_Cli struct {
	Cli *ProviderCLISurfaceRuntime `protobuf:"bytes,6,opt,name=cli,proto3,oneof"`
}

func (*ProviderSurfaceRuntime_Api) isProviderSurfaceRuntime_Access() {}

func (*ProviderSurfaceRuntime_Cli) isProviderSurfaceRuntime_Access() {}

type ProviderAPISurfaceRuntime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      v11.Protocol           `protobuf:"varint,1,opt,name=protocol,proto3,enum=api_protocol.v1.Protocol" json:"protocol,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderAPISurfaceRuntime) Reset() {
	*x = ProviderAPISurfaceRuntime{}
	mi := &file_provider_v1_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderAPISurfaceRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderAPISurfaceRuntime) ProtoMessage() {}

func (x *ProviderAPISurfaceRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderAPISurfaceRuntime.ProtoReflect.Descriptor instead.
func (*ProviderAPISurfaceRuntime) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{18}
}

func (x *ProviderAPISurfaceRuntime) GetProtocol() v11.Protocol {
	if x != nil {
		return x.Protocol
	}
	return v11.Protocol(0)
}

func (x *ProviderAPISurfaceRuntime) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type ProviderCLISurfaceRuntime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CliId         string                 `protobuf:"bytes,1,opt,name=cli_id,json=cliId,proto3" json:"cli_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCLISurfaceRuntime) Reset() {
	*x = ProviderCLISurfaceRuntime{}
	mi := &file_provider_v1_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCLISurfaceRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCLISurfaceRuntime) ProtoMessage() {}

func (x *ProviderCLISurfaceRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCLISurfaceRuntime.ProtoReflect.Descriptor instead.
func (*ProviderCLISurfaceRuntime) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{19}
}

func (x *ProviderCLISurfaceRuntime) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

// ProviderModelCatalogEntry describes one provider-local model entry plus one
// optional canonical model binding.
type ProviderModelCatalogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProviderModelId string                 `protobuf:"bytes,1,opt,name=provider_model_id,json=providerModelId,proto3" json:"provider_model_id,omitempty"`
	ModelRef        *v12.ModelRef          `protobuf:"bytes,2,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProviderModelCatalogEntry) Reset() {
	*x = ProviderModelCatalogEntry{}
	mi := &file_provider_v1_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderModelCatalogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderModelCatalogEntry) ProtoMessage() {}

func (x *ProviderModelCatalogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderModelCatalogEntry.ProtoReflect.Descriptor instead.
func (*ProviderModelCatalogEntry) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{20}
}

func (x *ProviderModelCatalogEntry) GetProviderModelId() string {
	if x != nil {
		return x.ProviderModelId
	}
	return ""
}

func (x *ProviderModelCatalogEntry) GetModelRef() *v12.ModelRef {
	if x != nil {
		return x.ModelRef
	}
	return nil
}

// ProviderModelCatalog describes provider-callable model entries.
type ProviderModelCatalog struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Models        []*ProviderModelCatalogEntry `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Source        CatalogSource                `protobuf:"varint,2,opt,name=source,proto3,enum=provider.v1.CatalogSource" json:"source,omitempty"`
	UpdatedAt     *timestamppb.Timestamp       `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RefreshAfter  *durationpb.Duration         `protobuf:"bytes,4,opt,name=refresh_after,json=refreshAfter,proto3" json:"refresh_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderModelCatalog) Reset() {
	*x = ProviderModelCatalog{}
	mi := &file_provider_v1_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderModelCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderModelCatalog) ProtoMessage() {}

func (x *ProviderModelCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderModelCatalog.ProtoReflect.Descriptor instead.
func (*ProviderModelCatalog) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{21}
}

func (x *ProviderModelCatalog) GetModels() []*ProviderModelCatalogEntry {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ProviderModelCatalog) GetSource() CatalogSource {
	if x != nil {
		return x.Source
	}
	return CatalogSource_CATALOG_SOURCE_UNSPECIFIED
}

func (x *ProviderModelCatalog) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProviderModelCatalog) GetRefreshAfter() *durationpb.Duration {
	if x != nil {
		return x.RefreshAfter
	}
	return nil
}

// ResolvedProviderSurface describes one final callable surface plus the
// resolved auth material required to invoke it directly.
type ResolvedProviderSurface struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Surface       *ProviderSurfaceRuntime `protobuf:"bytes,1,opt,name=surface,proto3" json:"surface,omitempty"`
	Auth          *v1.ResolvedCredential  `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedProviderSurface) Reset() {
	*x = ResolvedProviderSurface{}
	mi := &file_provider_v1_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedProviderSurface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedProviderSurface) ProtoMessage() {}

func (x *ResolvedProviderSurface) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedProviderSurface.ProtoReflect.Descriptor instead.
func (*ResolvedProviderSurface) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{22}
}

func (x *ResolvedProviderSurface) GetSurface() *ProviderSurfaceRuntime {
	if x != nil {
		return x.Surface
	}
	return nil
}

func (x *ResolvedProviderSurface) GetAuth() *v1.ResolvedCredential {
	if x != nil {
		return x.Auth
	}
	return nil
}

// ResolvedProviderModel describes the final provider-routed model entry used
// for one call.
type ResolvedProviderModel struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	SurfaceId       string                   `protobuf:"bytes,1,opt,name=surface_id,json=surfaceId,proto3" json:"surface_id,omitempty"`
	ProviderModelId string                   `protobuf:"bytes,3,opt,name=provider_model_id,json=providerModelId,proto3" json:"provider_model_id,omitempty"`
	Protocol        v11.Protocol             `protobuf:"varint,4,opt,name=protocol,proto3,enum=api_protocol.v1.Protocol" json:"protocol,omitempty"`
	BaseUrl         string                   `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Model           *v12.ResolvedModel       `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Source          CatalogSource            `protobuf:"varint,8,opt,name=source,proto3,enum=provider.v1.CatalogSource" json:"source,omitempty"`
	Surface         *ResolvedProviderSurface `protobuf:"bytes,9,opt,name=surface,proto3" json:"surface,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolvedProviderModel) Reset() {
	*x = ResolvedProviderModel{}
	mi := &file_provider_v1_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedProviderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedProviderModel) ProtoMessage() {}

func (x *ResolvedProviderModel) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedProviderModel.ProtoReflect.Descriptor instead.
func (*ResolvedProviderModel) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{23}
}

func (x *ResolvedProviderModel) GetSurfaceId() string {
	if x != nil {
		return x.SurfaceId
	}
	return ""
}

func (x *ResolvedProviderModel) GetProviderModelId() string {
	if x != nil {
		return x.ProviderModelId
	}
	return ""
}

func (x *ResolvedProviderModel) GetProtocol() v11.Protocol {
	if x != nil {
		return x.Protocol
	}
	return v11.Protocol(0)
}

func (x *ResolvedProviderModel) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ResolvedProviderModel) GetModel() *v12.ResolvedModel {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *ResolvedProviderModel) GetSource() CatalogSource {
	if x != nil {
		return x.Source
	}
	return CatalogSource_CATALOG_SOURCE_UNSPECIFIED
}

func (x *ResolvedProviderModel) GetSurface() *ResolvedProviderSurface {
	if x != nil {
		return x.Surface
	}
	return nil
}

var File_provider_v1_provider_proto protoreflect.FileDescriptor

const file_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/provider.proto\x12\vprovider.v1\x1a\x1ecredential/v1/credential.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eapi_protocol/v1/protocol.proto\x1a\x14model/v1/model.proto\"\xc7\x03\n" +
	"\x0fProviderSurface\x12\x1d\n" +
	"\n" +
	"surface_id\x18\x01 \x01(\tR\tsurfaceId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12[\n" +
	"\x1asupported_credential_kinds\x18\x03 \x03(\x0e2\x1d.credential.v1.CredentialKindR\x18supportedCredentialKinds\x12E\n" +
	"\fcapabilities\x18\x05 \x01(\v2!.provider.v1.ProviderCapabilitiesR\fcapabilities\x124\n" +
	"\x04kind\x18\x06 \x01(\x0e2 .provider.v1.ProviderSurfaceKindR\x04kind\x125\n" +
	"\x03api\x18\b \x01(\v2#.provider.v1.ProviderSurfaceAPISpecR\x03api\x12:\n" +
	"\x06probes\x18\t \x01(\v2\".provider.v1.ProviderSurfaceProbesR\x06probesJ\x04\b\x04\x10\x05J\x04\b\a\x10\bR\x13supported_protocolsR\x04meta\"d\n" +
	"\x16ProviderSurfaceAPISpec\x12J\n" +
	"\x13supported_protocols\x18\x01 \x03(\x0e2\x19.api_protocol.v1.ProtocolR\x12supportedProtocols\"\xa9\x01\n" +
	"\x15ProviderSurfaceProbes\x12R\n" +
	"\rmodel_catalog\x18\x01 \x01(\v2-.provider.v1.ProviderSurfaceModelCatalogProbeR\fmodelCatalog\x12<\n" +
	"\x05quota\x18\x02 \x01(\v2&.provider.v1.ProviderSurfaceQuotaProbeR\x05quota\"o\n" +
	" ProviderSurfaceModelCatalogProbe\x12K\n" +
	"\x06method\x18\x01 \x01(\x0e23.provider.v1.ProviderSurfaceModelCatalogProbeMethodR\x06method\"\xb7\x01\n" +
	"\x19ProviderSurfaceQuotaProbe\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x128\n" +
	"\x04args\x18\x02 \x03(\v2$.provider.v1.ProviderSurfaceProbeArgR\x04args\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xef\x01\n" +
	"\x17ProviderSurfaceProbeArg\x12\x15\n" +
	"\x06arg_id\x18\x01 \x01(\tR\x05argId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1c\n" +
	"\tsensitive\x18\x05 \x01(\bR\tsensitive\x12\x1c\n" +
	"\tmultiline\x18\x06 \x01(\bR\tmultiline\x12 \n" +
	"\vplaceholder\x18\a \x01(\tR\vplaceholder\"\xeb\x01\n" +
	"\bProvider\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12?\n" +
	"\bsurfaces\x18\a \x03(\v2#.provider.v1.ProviderSurfaceBindingR\bsurfacesJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\b\x10\tR\tvendor_idR\x16provider_credential_idR\x10default_model_idR\rmodel_catalog\"\xeb\x01\n" +
	"\x14ProviderCapabilities\x126\n" +
	"\x17supports_model_override\x18\x01 \x01(\bR\x15supportsModelOverride\x12?\n" +
	"\x1csupports_model_catalog_probe\x18\x03 \x01(\bR\x19supportsModelCatalogProbe\x120\n" +
	"\x14supports_quota_probe\x18\x04 \x01(\bR\x12supportsQuotaProbeJ\x04\b\x02\x10\x03R\"supports_available_model_discovery\"\xa5\x04\n" +
	"\x16ProviderSurfaceBinding\x12\x1d\n" +
	"\n" +
	"surface_id\x18\x01 \x01(\tR\tsurfaceId\x12Z\n" +
	"\x17provider_credential_ref\x18\f \x01(\v2\".provider.v1.ProviderCredentialRefR\x15providerCredentialRef\x12=\n" +
	"\aruntime\x18\r \x01(\v2#.provider.v1.ProviderSurfaceRuntimeR\aruntime\x12D\n" +
	"\n" +
	"source_ref\x18\x11 \x01(\v2%.provider.v1.ProviderSurfaceSourceRefR\tsourceRefJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11R\x0ecredential_refR\x12network_policy_refR\bprotocolR\bbase_urlR\x0ffallback_modelsR\x11allowed_model_idsR\x10default_model_idR\x12selection_priorityR\x12vendor_account_refR\tvendor_idR\vprovider_idR\x15provider_display_name\"\x85\x01\n" +
	"\x18ProviderSurfaceSourceRef\x12:\n" +
	"\x04kind\x18\x01 \x01(\x0e2&.provider.v1.ProviderSurfaceSourceKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"surface_id\x18\x03 \x01(\tR\tsurfaceId\"M\n" +
	"\x15ProviderCredentialRef\x124\n" +
	"\x16provider_credential_id\x18\x01 \x01(\tR\x14providerCredentialId\"\xce\x01\n" +
	"\x12ProviderRuntimeRef\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"surface_id\x18\x02 \x01(\tR\tsurfaceId\x126\n" +
	"\x03api\x18\x03 \x01(\v2\".provider.v1.ProviderRuntimeAPIRefH\x00R\x03api\x126\n" +
	"\x03cli\x18\x04 \x01(\v2\".provider.v1.ProviderRuntimeCLIRefH\x00R\x03cliB\b\n" +
	"\x06access\"N\n" +
	"\x15ProviderRuntimeAPIRef\x125\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x19.api_protocol.v1.ProtocolR\bprotocol\"\x17\n" +
	"\x15ProviderRuntimeCLIRef\"\xfc\x03\n" +
	"\x12ProviderRunBinding\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12S\n" +
	"\x14credential_grant_ref\x18\x02 \x01(\v2!.credential.v1.CredentialGrantRefR\x12credentialGrantRef\x12\x1f\n" +
	"\vruntime_url\x18\x03 \x01(\tR\n" +
	"runtimeUrl\x12/\n" +
	"\x13materialization_key\x18\x04 \x01(\tR\x12materializationKey\x12$\n" +
	"\x0eruntime_cli_id\x18\x05 \x01(\tR\fruntimeCliId\x12*\n" +
	"\x11provider_model_id\x18\x06 \x01(\tR\x0fproviderModelId\x12,\n" +
	"\x12canonical_model_id\x18\a \x01(\tR\x10canonicalModelId\x12&\n" +
	"\x0fsource_model_id\x18\b \x01(\tR\rsourceModelId\x125\n" +
	"\x03api\x18\t \x01(\v2!.provider.v1.ProviderRunAPIAccessH\x00R\x03api\x125\n" +
	"\x03cli\x18\n" +
	" \x01(\v2!.provider.v1.ProviderRunCLIAccessH\x00R\x03cliB\b\n" +
	"\x06access\"M\n" +
	"\x14ProviderRunAPIAccess\x125\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x19.api_protocol.v1.ProtocolR\bprotocol\"\x16\n" +
	"\x14ProviderRunCLIAccess\"\xfe\x03\n" +
	"\x16ProviderSurfaceRuntime\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12:\n" +
	"\x06origin\x18\x02 \x01(\x0e2\".provider.v1.ProviderSurfaceOriginR\x06origin\x12;\n" +
	"\acatalog\x18\x04 \x01(\v2!.provider.v1.ProviderModelCatalogR\acatalog\x12:\n" +
	"\x03api\x18\x05 \x01(\v2&.provider.v1.ProviderAPISurfaceRuntimeH\x00R\x03api\x12:\n" +
	"\x03cli\x18\x06 \x01(\v2&.provider.v1.ProviderCLISurfaceRuntimeH\x00R\x03cli\x123\n" +
	"\x16model_catalog_probe_id\x18\n" +
	" \x01(\tR\x13modelCatalogProbeId\x12$\n" +
	"\x0equota_probe_id\x18\v \x01(\tR\fquotaProbeId\x12*\n" +
	"\x11egress_ruleset_id\x18\f \x01(\tR\x0fegressRulesetId\x12\x17\n" +
	"\amitm_id\x18\r \x01(\tR\x06mitmIdB\b\n" +
	"\x06accessJ\x04\b\x03\x10\x04R supports_dynamic_model_discovery\"m\n" +
	"\x19ProviderAPISurfaceRuntime\x125\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x19.api_protocol.v1.ProtocolR\bprotocol\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\"2\n" +
	"\x19ProviderCLISurfaceRuntime\x12\x15\n" +
	"\x06cli_id\x18\x01 \x01(\tR\x05cliId\"x\n" +
	"\x19ProviderModelCatalogEntry\x12*\n" +
	"\x11provider_model_id\x18\x01 \x01(\tR\x0fproviderModelId\x12/\n" +
	"\tmodel_ref\x18\x02 \x01(\v2\x12.model.v1.ModelRefR\bmodelRef\"\x85\x02\n" +
	"\x14ProviderModelCatalog\x12>\n" +
	"\x06models\x18\x01 \x03(\v2&.provider.v1.ProviderModelCatalogEntryR\x06models\x122\n" +
	"\x06source\x18\x02 \x01(\x0e2\x1a.provider.v1.CatalogSourceR\x06source\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\rrefresh_after\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\frefreshAfter\"\x8f\x01\n" +
	"\x17ResolvedProviderSurface\x12=\n" +
	"\asurface\x18\x01 \x01(\v2#.provider.v1.ProviderSurfaceRuntimeR\asurface\x125\n" +
	"\x04auth\x18\x02 \x01(\v2!.credential.v1.ResolvedCredentialR\x04auth\"\xf0\x02\n" +
	"\x15ResolvedProviderModel\x12\x1d\n" +
	"\n" +
	"surface_id\x18\x01 \x01(\tR\tsurfaceId\x12*\n" +
	"\x11provider_model_id\x18\x03 \x01(\tR\x0fproviderModelId\x125\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x19.api_protocol.v1.ProtocolR\bprotocol\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12-\n" +
	"\x05model\x18\x06 \x01(\v2\x17.model.v1.ResolvedModelR\x05model\x122\n" +
	"\x06source\x18\b \x01(\x0e2\x1a.provider.v1.CatalogSourceR\x06source\x12>\n" +
	"\asurface\x18\t \x01(\v2$.provider.v1.ResolvedProviderSurfaceR\asurfaceJ\x04\b\a\x10\bR\x11provider_metadata*\x9c\x02\n" +
	"&ProviderSurfaceModelCatalogProbeMethod\x12;\n" +
	"7PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_UNSPECIFIED\x10\x00\x12D\n" +
	"@PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_PROTOCOL_BEST_EFFORT\x10\x01\x126\n" +
	"2PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_STATIC\x10\x02\x127\n" +
	"3PROVIDER_SURFACE_MODEL_CATALOG_PROBE_METHOD_ADAPTER\x10\x03*\x99\x01\n" +
	"\x13ProviderSurfaceKind\x12%\n" +
	"!PROVIDER_SURFACE_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PROVIDER_SURFACE_KIND_API\x10\x01\x12\x1d\n" +
	"\x19PROVIDER_SURFACE_KIND_CLI\x10\x02\x12\x1d\n" +
	"\x19PROVIDER_SURFACE_KIND_WEB\x10\x03*\x98\x01\n" +
	"\x19ProviderSurfaceSourceKind\x12,\n" +
	"(PROVIDER_SURFACE_SOURCE_KIND_UNSPECIFIED\x10\x00\x12'\n" +
	"#PROVIDER_SURFACE_SOURCE_KIND_VENDOR\x10\x01\x12$\n" +
	" PROVIDER_SURFACE_SOURCE_KIND_CLI\x10\x02*\x89\x01\n" +
	"\x15ProviderSurfaceOrigin\x12'\n" +
	"#PROVIDER_SURFACE_ORIGIN_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fPROVIDER_SURFACE_ORIGIN_DERIVED\x10\x01\x12\"\n" +
	"\x1ePROVIDER_SURFACE_ORIGIN_MANUAL\x10\x02*\xba\x01\n" +
	"\rCatalogSource\x12\x1e\n" +
	"\x1aCATALOG_SOURCE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCATALOG_SOURCE_MODEL_SERVICE\x10\x01\x12!\n" +
	"\x1dCATALOG_SOURCE_PROTOCOL_QUERY\x10\x02\x12\"\n" +
	"\x1eCATALOG_SOURCE_FALLBACK_CONFIG\x10\x03\x12 \n" +
	"\x1cCATALOG_SOURCE_VENDOR_PRESET\x10\x04B7Z5code-code.internal/go-contract/provider/v1;providerv1b\x06proto3"

var (
	file_provider_v1_provider_proto_rawDescOnce sync.Once
	file_provider_v1_provider_proto_rawDescData []byte
)

func file_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)))
	})
	return file_provider_v1_provider_proto_rawDescData
}

var file_provider_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_provider_v1_provider_proto_goTypes = []any{
	(ProviderSurfaceModelCatalogProbeMethod)(0), // 0: provider.v1.ProviderSurfaceModelCatalogProbeMethod
	(ProviderSurfaceKind)(0),                    // 1: provider.v1.ProviderSurfaceKind
	(ProviderSurfaceSourceKind)(0),              // 2: provider.v1.ProviderSurfaceSourceKind
	(ProviderSurfaceOrigin)(0),                  // 3: provider.v1.ProviderSurfaceOrigin
	(CatalogSource)(0),                          // 4: provider.v1.CatalogSource
	(*ProviderSurface)(nil),                     // 5: provider.v1.ProviderSurface
	(*ProviderSurfaceAPISpec)(nil),              // 6: provider.v1.ProviderSurfaceAPISpec
	(*ProviderSurfaceProbes)(nil),               // 7: provider.v1.ProviderSurfaceProbes
	(*ProviderSurfaceModelCatalogProbe)(nil),    // 8: provider.v1.ProviderSurfaceModelCatalogProbe
	(*ProviderSurfaceQuotaProbe)(nil),           // 9: provider.v1.ProviderSurfaceQuotaProbe
	(*ProviderSurfaceProbeArg)(nil),             // 10: provider.v1.ProviderSurfaceProbeArg
	(*Provider)(nil),                            // 11: provider.v1.Provider
	(*ProviderCapabilities)(nil),                // 12: provider.v1.ProviderCapabilities
	(*ProviderSurfaceBinding)(nil),              // 13: provider.v1.ProviderSurfaceBinding
	(*ProviderSurfaceSourceRef)(nil),            // 14: provider.v1.ProviderSurfaceSourceRef
	(*ProviderCredentialRef)(nil),               // 15: provider.v1.ProviderCredentialRef
	(*ProviderRuntimeRef)(nil),                  // 16: provider.v1.ProviderRuntimeRef
	(*ProviderRuntimeAPIRef)(nil),               // 17: provider.v1.ProviderRuntimeAPIRef
	(*ProviderRuntimeCLIRef)(nil),               // 18: provider.v1.ProviderRuntimeCLIRef
	(*ProviderRunBinding)(nil),                  // 19: provider.v1.ProviderRunBinding
	(*ProviderRunAPIAccess)(nil),                // 20: provider.v1.ProviderRunAPIAccess
	(*ProviderRunCLIAccess)(nil),                // 21: provider.v1.ProviderRunCLIAccess
	(*ProviderSurfaceRuntime)(nil),              // 22: provider.v1.ProviderSurfaceRuntime
	(*ProviderAPISurfaceRuntime)(nil),           // 23: provider.v1.ProviderAPISurfaceRuntime
	(*ProviderCLISurfaceRuntime)(nil),           // 24: provider.v1.ProviderCLISurfaceRuntime
	(*ProviderModelCatalogEntry)(nil),           // 25: provider.v1.ProviderModelCatalogEntry
	(*ProviderModelCatalog)(nil),                // 26: provider.v1.ProviderModelCatalog
	(*ResolvedProviderSurface)(nil),             // 27: provider.v1.ResolvedProviderSurface
	(*ResolvedProviderModel)(nil),               // 28: provider.v1.ResolvedProviderModel
	(v1.CredentialKind)(0),                      // 29: credential.v1.CredentialKind
	(v11.Protocol)(0),                           // 30: api_protocol.v1.Protocol
	(*v1.CredentialGrantRef)(nil),               // 31: credential.v1.CredentialGrantRef
	(*v12.ModelRef)(nil),                        // 32: model.v1.ModelRef
	(*timestamppb.Timestamp)(nil),               // 33: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                 // 34: google.protobuf.Duration
	(*v1.ResolvedCredential)(nil),               // 35: credential.v1.ResolvedCredential
	(*v12.ResolvedModel)(nil),                   // 36: model.v1.ResolvedModel
}
var file_provider_v1_provider_proto_depIdxs = []int32{
	29, // 0: provider.v1.ProviderSurface.supported_credential_kinds:type_name -> credential.v1.CredentialKind
	12, // 1: provider.v1.ProviderSurface.capabilities:type_name -> provider.v1.ProviderCapabilities
	1,  // 2: provider.v1.ProviderSurface.kind:type_name -> provider.v1.ProviderSurfaceKind
	6,  // 3: provider.v1.ProviderSurface.api:type_name -> provider.v1.ProviderSurfaceAPISpec
	7,  // 4: provider.v1.ProviderSurface.probes:type_name -> provider.v1.ProviderSurfaceProbes
	30, // 5: provider.v1.ProviderSurfaceAPISpec.supported_protocols:type_name -> api_protocol.v1.Protocol
	8,  // 6: provider.v1.ProviderSurfaceProbes.model_catalog:type_name -> provider.v1.ProviderSurfaceModelCatalogProbe
	9,  // 7: provider.v1.ProviderSurfaceProbes.quota:type_name -> provider.v1.ProviderSurfaceQuotaProbe
	0,  // 8: provider.v1.ProviderSurfaceModelCatalogProbe.method:type_name -> provider.v1.ProviderSurfaceModelCatalogProbeMethod
	10, // 9: provider.v1.ProviderSurfaceQuotaProbe.args:type_name -> provider.v1.ProviderSurfaceProbeArg
	13, // 10: provider.v1.Provider.surfaces:type_name -> provider.v1.ProviderSurfaceBinding
	15, // 11: provider.v1.ProviderSurfaceBinding.provider_credential_ref:type_name -> provider.v1.ProviderCredentialRef
	22, // 12: provider.v1.ProviderSurfaceBinding.runtime:type_name -> provider.v1.ProviderSurfaceRuntime
	14, // 13: provider.v1.ProviderSurfaceBinding.source_ref:type_name -> provider.v1.ProviderSurfaceSourceRef
	2,  // 14: provider.v1.ProviderSurfaceSourceRef.kind:type_name -> provider.v1.ProviderSurfaceSourceKind
	17, // 15: provider.v1.ProviderRuntimeRef.api:type_name -> provider.v1.ProviderRuntimeAPIRef
	18, // 16: provider.v1.ProviderRuntimeRef.cli:type_name -> provider.v1.ProviderRuntimeCLIRef
	30, // 17: provider.v1.ProviderRuntimeAPIRef.protocol:type_name -> api_protocol.v1.Protocol
	31, // 18: provider.v1.ProviderRunBinding.credential_grant_ref:type_name -> credential.v1.CredentialGrantRef
	20, // 19: provider.v1.ProviderRunBinding.api:type_name -> provider.v1.ProviderRunAPIAccess
	21, // 20: provider.v1.ProviderRunBinding.cli:type_name -> provider.v1.ProviderRunCLIAccess
	30, // 21: provider.v1.ProviderRunAPIAccess.protocol:type_name -> api_protocol.v1.Protocol
	3,  // 22: provider.v1.ProviderSurfaceRuntime.origin:type_name -> provider.v1.ProviderSurfaceOrigin
	26, // 23: provider.v1.ProviderSurfaceRuntime.catalog:type_name -> provider.v1.ProviderModelCatalog
	23, // 24: provider.v1.ProviderSurfaceRuntime.api:type_name -> provider.v1.ProviderAPISurfaceRuntime
	24, // 25: provider.v1.ProviderSurfaceRuntime.cli:type_name -> provider.v1.ProviderCLISurfaceRuntime
	30, // 26: provider.v1.ProviderAPISurfaceRuntime.protocol:type_name -> api_protocol.v1.Protocol
	32, // 27: provider.v1.ProviderModelCatalogEntry.model_ref:type_name -> model.v1.ModelRef
	25, // 28: provider.v1.ProviderModelCatalog.models:type_name -> provider.v1.ProviderModelCatalogEntry
	4,  // 29: provider.v1.ProviderModelCatalog.source:type_name -> provider.v1.CatalogSource
	33, // 30: provider.v1.ProviderModelCatalog.updated_at:type_name -> google.protobuf.Timestamp
	34, // 31: provider.v1.ProviderModelCatalog.refresh_after:type_name -> google.protobuf.Duration
	22, // 32: provider.v1.ResolvedProviderSurface.surface:type_name -> provider.v1.ProviderSurfaceRuntime
	35, // 33: provider.v1.ResolvedProviderSurface.auth:type_name -> credential.v1.ResolvedCredential
	30, // 34: provider.v1.ResolvedProviderModel.protocol:type_name -> api_protocol.v1.Protocol
	36, // 35: provider.v1.ResolvedProviderModel.model:type_name -> model.v1.ResolvedModel
	4,  // 36: provider.v1.ResolvedProviderModel.source:type_name -> provider.v1.CatalogSource
	27, // 37: provider.v1.ResolvedProviderModel.surface:type_name -> provider.v1.ResolvedProviderSurface
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_provider_v1_provider_proto_init() }
func file_provider_v1_provider_proto_init() {
	if File_provider_v1_provider_proto != nil {
		return
	}
	file_provider_v1_provider_proto_msgTypes[11].OneofWrappers = []any{
		(*ProviderRuntimeRef_Api)(nil),
		(*ProviderRuntimeRef_Cli)(nil),
	}
	file_provider_v1_provider_proto_msgTypes[14].OneofWrappers = []any{
		(*ProviderRunBinding_Api)(nil),
		(*ProviderRunBinding_Cli)(nil),
	}
	file_provider_v1_provider_proto_msgTypes[17].OneofWrappers = []any{
		(*ProviderSurfaceRuntime_Api)(nil),
		(*ProviderSurfaceRuntime_Cli)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_provider_v1_provider_proto_depIdxs,
		EnumInfos:         file_provider_v1_provider_proto_enumTypes,
		MessageInfos:      file_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_provider_v1_provider_proto = out.File
	file_provider_v1_provider_proto_goTypes = nil
	file_provider_v1_provider_proto_depIdxs = nil
}
