apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-notifications
spec:
  tls:
    - hosts:
        - bot.staging.pood1e.site
        - bot.staging.pood1e.monster
      secretName: platform-notifications-staging-tls
  rules:
    - host: bot.staging.pood1e.site
      http:
        paths:
          - path: /wecom/callback
            pathType: Exact
            backend:
              service:
                name: wecom-callback-adapter
                port:
                  number: 8080
          - path: /wecom/robots/default/callback
            pathType: Exact
            backend:
              service:
                name: wecom-robot-default-callback-adapter
                port:
                  number: 8080
    - host: bot.staging.pood1e.monster
      http:
        paths:
          - path: /wecom/callback
            pathType: Exact
            backend:
              service:
                name: wecom-callback-adapter
                port:
                  number: 8080
          - path: /wecom/robots/default/callback
            pathType: Exact
            backend:
              service:
                name: wecom-robot-default-callback-adapter
                port:
                  number: 8080
