{{- if .Values.cliImageBuildConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cli-runtime-image-build-config
  labels:
{{ include "platform.labels" (dict "root" . "name" "cli-runtime-image-build-config" "componentLabel" "runtime-image-build") | nindent 4 }}
data:
  IMAGE_REGISTRY_PREFIX: {{ .Values.cliImageBuildConfig.imageRegistryPrefix | quote }}
  IMAGE_REGISTRY_LOOKUP_PREFIX: {{ .Values.cliImageBuildConfig.imageRegistryLookupPrefix | quote }}
  IMAGE_REGISTRY_LOOKUP_INSECURE: {{ .Values.cliImageBuildConfig.imageRegistryLookupInsecure | quote }}
  SOURCE_CONTEXT: {{ .Values.cliImageBuildConfig.sourceContext | quote }}
  SOURCE_REVISION: {{ .Values.cliImageBuildConfig.sourceRevision | quote }}
---
{{- end }}
{{- if .Values.networkEgressPolicy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.networkEgressPolicy.name }}
  labels:
{{ include "platform.labels" (dict "root" . "name" .Values.networkEgressPolicy.name "componentLabel" "egress-policy") | nindent 4 }}
    egress.platform.code-code.internal/role: policy
data:
  policy.json: |
{{ tpl .Values.networkEgressPolicy.policyJson . | nindent 4 }}
{{- end }}
