{{- range $key := keys .Values.components | sortAlpha }}
{{- $component := index $.Values.components $key }}
{{- $serviceAccount := $component.serviceAccount | default dict }}
{{- if and $component.enabled $serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $component.name }}
  labels:
{{ include "platform.labels" (dict "root" $ "name" $component.name "componentLabel" $component.componentLabel) | nindent 4 }}
{{- if hasKey $serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $serviceAccount.automountServiceAccountToken }}
{{- end }}
---
{{- end }}
{{- end }}
{{- if .Values.runtimeServiceAccounts.cliImageBuild.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runtimeServiceAccounts.cliImageBuild.name }}
  namespace: {{ .Values.global.runNamespace }}
  labels:
{{ include "platform.labels" (dict "root" . "name" .Values.runtimeServiceAccounts.cliImageBuild.name "componentLabel" "runtime-image-build") | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
