apiVersion: v1
kind: Namespace
metadata:
  name: code-code-observability
  labels:
    app.kubernetes.io/part-of: code-code
    code-code.internal/purpose: observability
    egress.platform.code-code.internal/trust-bundle: "enabled"
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
