// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/auth/v1/egress_auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveEgressRequestHeadersRequest struct {
	state                  protoimpl.MessageState         `protogen:"open.v1"`
	PolicyId               string                         `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	CredentialId           string                         `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	AdapterId              string                         `protobuf:"bytes,3,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	TargetHost             string                         `protobuf:"bytes,4,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	HeaderValuePrefix      string                         `protobuf:"bytes,5,opt,name=header_value_prefix,json=headerValuePrefix,proto3" json:"header_value_prefix,omitempty"`
	Origin                 string                         `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	RequestHeaders         map[string]string              `protobuf:"bytes,7,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SimpleReplacementRules []*EgressSimpleReplacementRule `protobuf:"bytes,8,rep,name=simple_replacement_rules,json=simpleReplacementRules,proto3" json:"simple_replacement_rules,omitempty"`
	Headers                []*EgressHeaderReplacementItem `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty"`
	AllowedHeaderNames     []string                       `protobuf:"bytes,10,rep,name=allowed_header_names,json=allowedHeaderNames,proto3" json:"allowed_header_names,omitempty"`
	RuntimeSource          *EgressRequestSource           `protobuf:"bytes,11,opt,name=runtime_source,json=runtimeSource,proto3" json:"runtime_source,omitempty"`
	TargetPath             string                         `protobuf:"bytes,12,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResolveEgressRequestHeadersRequest) Reset() {
	*x = ResolveEgressRequestHeadersRequest{}
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEgressRequestHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEgressRequestHeadersRequest) ProtoMessage() {}

func (x *ResolveEgressRequestHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEgressRequestHeadersRequest.ProtoReflect.Descriptor instead.
func (*ResolveEgressRequestHeadersRequest) Descriptor() ([]byte, []int) {
	return file_platform_auth_v1_egress_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveEgressRequestHeadersRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ResolveEgressRequestHeadersRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *ResolveEgressRequestHeadersRequest) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *ResolveEgressRequestHeadersRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *ResolveEgressRequestHeadersRequest) GetHeaderValuePrefix() string {
	if x != nil {
		return x.HeaderValuePrefix
	}
	return ""
}

func (x *ResolveEgressRequestHeadersRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ResolveEgressRequestHeadersRequest) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *ResolveEgressRequestHeadersRequest) GetSimpleReplacementRules() []*EgressSimpleReplacementRule {
	if x != nil {
		return x.SimpleReplacementRules
	}
	return nil
}

func (x *ResolveEgressRequestHeadersRequest) GetHeaders() []*EgressHeaderReplacementItem {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResolveEgressRequestHeadersRequest) GetAllowedHeaderNames() []string {
	if x != nil {
		return x.AllowedHeaderNames
	}
	return nil
}

func (x *ResolveEgressRequestHeadersRequest) GetRuntimeSource() *EgressRequestSource {
	if x != nil {
		return x.RuntimeSource
	}
	return nil
}

func (x *ResolveEgressRequestHeadersRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type ResolveEgressResponseHeadersRequest struct {
	state                  protoimpl.MessageState         `protogen:"open.v1"`
	PolicyId               string                         `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	CredentialId           string                         `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	AdapterId              string                         `protobuf:"bytes,3,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	TargetHost             string                         `protobuf:"bytes,4,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	Origin                 string                         `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	RequestHeaders         map[string]string              `protobuf:"bytes,6,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseHeaders        map[string]string              `protobuf:"bytes,7,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SimpleReplacementRules []*EgressSimpleReplacementRule `protobuf:"bytes,8,rep,name=simple_replacement_rules,json=simpleReplacementRules,proto3" json:"simple_replacement_rules,omitempty"`
	Headers                []*EgressHeaderReplacementItem `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty"`
	AllowedHeaderNames     []string                       `protobuf:"bytes,10,rep,name=allowed_header_names,json=allowedHeaderNames,proto3" json:"allowed_header_names,omitempty"`
	RuntimeSource          *EgressRequestSource           `protobuf:"bytes,11,opt,name=runtime_source,json=runtimeSource,proto3" json:"runtime_source,omitempty"`
	TargetPath             string                         `protobuf:"bytes,12,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	StatusCode             uint32                         `protobuf:"varint,13,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	HeaderValuePrefix      string                         `protobuf:"bytes,14,opt,name=header_value_prefix,json=headerValuePrefix,proto3" json:"header_value_prefix,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResolveEgressResponseHeadersRequest) Reset() {
	*x = ResolveEgressResponseHeadersRequest{}
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEgressResponseHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEgressResponseHeadersRequest) ProtoMessage() {}

func (x *ResolveEgressResponseHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEgressResponseHeadersRequest.ProtoReflect.Descriptor instead.
func (*ResolveEgressResponseHeadersRequest) Descriptor() ([]byte, []int) {
	return file_platform_auth_v1_egress_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveEgressResponseHeadersRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ResolveEgressResponseHeadersRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *ResolveEgressResponseHeadersRequest) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *ResolveEgressResponseHeadersRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *ResolveEgressResponseHeadersRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ResolveEgressResponseHeadersRequest) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *ResolveEgressResponseHeadersRequest) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *ResolveEgressResponseHeadersRequest) GetSimpleReplacementRules() []*EgressSimpleReplacementRule {
	if x != nil {
		return x.SimpleReplacementRules
	}
	return nil
}

func (x *ResolveEgressResponseHeadersRequest) GetHeaders() []*EgressHeaderReplacementItem {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResolveEgressResponseHeadersRequest) GetAllowedHeaderNames() []string {
	if x != nil {
		return x.AllowedHeaderNames
	}
	return nil
}

func (x *ResolveEgressResponseHeadersRequest) GetRuntimeSource() *EgressRequestSource {
	if x != nil {
		return x.RuntimeSource
	}
	return nil
}

func (x *ResolveEgressResponseHeadersRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ResolveEgressResponseHeadersRequest) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResolveEgressResponseHeadersRequest) GetHeaderValuePrefix() string {
	if x != nil {
		return x.HeaderValuePrefix
	}
	return ""
}

type EgressHeaderReplacementItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CurrentValue  string                 `protobuf:"bytes,2,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressHeaderReplacementItem) Reset() {
	*x = EgressHeaderReplacementItem{}
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressHeaderReplacementItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressHeaderReplacementItem) ProtoMessage() {}

func (x *EgressHeaderReplacementItem) ProtoReflect() protoreflect.Message {
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressHeaderReplacementItem.ProtoReflect.Descriptor instead.
func (*EgressHeaderReplacementItem) Descriptor() ([]byte, []int) {
	return file_platform_auth_v1_egress_auth_proto_rawDescGZIP(), []int{2}
}

func (x *EgressHeaderReplacementItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EgressHeaderReplacementItem) GetCurrentValue() string {
	if x != nil {
		return x.CurrentValue
	}
	return ""
}

type EgressSimpleReplacementRule struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	HeaderName        string                 `protobuf:"bytes,2,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	MaterialKey       string                 `protobuf:"bytes,3,opt,name=material_key,json=materialKey,proto3" json:"material_key,omitempty"`
	HeaderValuePrefix string                 `protobuf:"bytes,4,opt,name=header_value_prefix,json=headerValuePrefix,proto3" json:"header_value_prefix,omitempty"`
	Template          string                 `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EgressSimpleReplacementRule) Reset() {
	*x = EgressSimpleReplacementRule{}
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressSimpleReplacementRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressSimpleReplacementRule) ProtoMessage() {}

func (x *EgressSimpleReplacementRule) ProtoReflect() protoreflect.Message {
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressSimpleReplacementRule.ProtoReflect.Descriptor instead.
func (*EgressSimpleReplacementRule) Descriptor() ([]byte, []int) {
	return file_platform_auth_v1_egress_auth_proto_rawDescGZIP(), []int{3}
}

func (x *EgressSimpleReplacementRule) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *EgressSimpleReplacementRule) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

func (x *EgressSimpleReplacementRule) GetMaterialKey() string {
	if x != nil {
		return x.MaterialKey
	}
	return ""
}

func (x *EgressSimpleReplacementRule) GetHeaderValuePrefix() string {
	if x != nil {
		return x.HeaderValuePrefix
	}
	return ""
}

func (x *EgressSimpleReplacementRule) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

type ResolveEgressRequestHeadersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoveHeaders []string               `protobuf:"bytes,2,rep,name=remove_headers,json=removeHeaders,proto3" json:"remove_headers,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Skipped       bool                   `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEgressRequestHeadersResponse) Reset() {
	*x = ResolveEgressRequestHeadersResponse{}
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEgressRequestHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEgressRequestHeadersResponse) ProtoMessage() {}

func (x *ResolveEgressRequestHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEgressRequestHeadersResponse.ProtoReflect.Descriptor instead.
func (*ResolveEgressRequestHeadersResponse) Descriptor() ([]byte, []int) {
	return file_platform_auth_v1_egress_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveEgressRequestHeadersResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResolveEgressRequestHeadersResponse) GetRemoveHeaders() []string {
	if x != nil {
		return x.RemoveHeaders
	}
	return nil
}

func (x *ResolveEgressRequestHeadersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResolveEgressRequestHeadersResponse) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

type ResolveEgressResponseHeadersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoveHeaders []string               `protobuf:"bytes,2,rep,name=remove_headers,json=removeHeaders,proto3" json:"remove_headers,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Skipped       bool                   `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEgressResponseHeadersResponse) Reset() {
	*x = ResolveEgressResponseHeadersResponse{}
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEgressResponseHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEgressResponseHeadersResponse) ProtoMessage() {}

func (x *ResolveEgressResponseHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEgressResponseHeadersResponse.ProtoReflect.Descriptor instead.
func (*ResolveEgressResponseHeadersResponse) Descriptor() ([]byte, []int) {
	return file_platform_auth_v1_egress_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveEgressResponseHeadersResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResolveEgressResponseHeadersResponse) GetRemoveHeaders() []string {
	if x != nil {
		return x.RemoveHeaders
	}
	return nil
}

func (x *ResolveEgressResponseHeadersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResolveEgressResponseHeadersResponse) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

type EgressRequestSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*EgressRequestSource_Pod
	//	*EgressRequestSource_RunId
	//	*EgressRequestSource_WorkloadId
	Source        isEgressRequestSource_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRequestSource) Reset() {
	*x = EgressRequestSource{}
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRequestSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRequestSource) ProtoMessage() {}

func (x *EgressRequestSource) ProtoReflect() protoreflect.Message {
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRequestSource.ProtoReflect.Descriptor instead.
func (*EgressRequestSource) Descriptor() ([]byte, []int) {
	return file_platform_auth_v1_egress_auth_proto_rawDescGZIP(), []int{6}
}

func (x *EgressRequestSource) GetSource() isEgressRequestSource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *EgressRequestSource) GetPod() *EgressPodSource {
	if x != nil {
		if x, ok := x.Source.(*EgressRequestSource_Pod); ok {
			return x.Pod
		}
	}
	return nil
}

func (x *EgressRequestSource) GetRunId() string {
	if x != nil {
		if x, ok := x.Source.(*EgressRequestSource_RunId); ok {
			return x.RunId
		}
	}
	return ""
}

func (x *EgressRequestSource) GetWorkloadId() string {
	if x != nil {
		if x, ok := x.Source.(*EgressRequestSource_WorkloadId); ok {
			return x.WorkloadId
		}
	}
	return ""
}

type isEgressRequestSource_Source interface {
	isEgressRequestSource_Source()
}

type EgressRequestSource_Pod struct {
	Pod *EgressPodSource `protobuf:"bytes,1,opt,name=pod,proto3,oneof"`
}

type EgressRequestSource_RunId struct {
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3,oneof"`
}

type EgressRequestSource_WorkloadId struct {
	WorkloadId string `protobuf:"bytes,3,opt,name=workload_id,json=workloadId,proto3,oneof"`
}

func (*EgressRequestSource_Pod) isEgressRequestSource_Source() {}

func (*EgressRequestSource_RunId) isEgressRequestSource_Source() {}

func (*EgressRequestSource_WorkloadId) isEgressRequestSource_Source() {}

type EgressPodSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressPodSource) Reset() {
	*x = EgressPodSource{}
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPodSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPodSource) ProtoMessage() {}

func (x *EgressPodSource) ProtoReflect() protoreflect.Message {
	mi := &file_platform_auth_v1_egress_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPodSource.ProtoReflect.Descriptor instead.
func (*EgressPodSource) Descriptor() ([]byte, []int) {
	return file_platform_auth_v1_egress_auth_proto_rawDescGZIP(), []int{7}
}

func (x *EgressPodSource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EgressPodSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EgressPodSource) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *EgressPodSource) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_platform_auth_v1_egress_auth_proto protoreflect.FileDescriptor

const file_platform_auth_v1_egress_auth_proto_rawDesc = "" +
	"\n" +
	"\"platform/auth/v1/egress_auth.proto\x12\x10platform.auth.v1\"\xf7\x05\n" +
	"\"ResolveEgressRequestHeadersRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x03 \x01(\tR\tadapterId\x12\x1f\n" +
	"\vtarget_host\x18\x04 \x01(\tR\n" +
	"targetHost\x12.\n" +
	"\x13header_value_prefix\x18\x05 \x01(\tR\x11headerValuePrefix\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\tR\x06origin\x12q\n" +
	"\x0frequest_headers\x18\a \x03(\v2H.platform.auth.v1.ResolveEgressRequestHeadersRequest.RequestHeadersEntryR\x0erequestHeaders\x12g\n" +
	"\x18simple_replacement_rules\x18\b \x03(\v2-.platform.auth.v1.EgressSimpleReplacementRuleR\x16simpleReplacementRules\x12G\n" +
	"\aheaders\x18\t \x03(\v2-.platform.auth.v1.EgressHeaderReplacementItemR\aheaders\x120\n" +
	"\x14allowed_header_names\x18\n" +
	" \x03(\tR\x12allowedHeaderNames\x12L\n" +
	"\x0eruntime_source\x18\v \x01(\v2%.platform.auth.v1.EgressRequestSourceR\rruntimeSource\x12\x1f\n" +
	"\vtarget_path\x18\f \x01(\tR\n" +
	"targetPath\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\a\n" +
	"#ResolveEgressResponseHeadersRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x03 \x01(\tR\tadapterId\x12\x1f\n" +
	"\vtarget_host\x18\x04 \x01(\tR\n" +
	"targetHost\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12r\n" +
	"\x0frequest_headers\x18\x06 \x03(\v2I.platform.auth.v1.ResolveEgressResponseHeadersRequest.RequestHeadersEntryR\x0erequestHeaders\x12u\n" +
	"\x10response_headers\x18\a \x03(\v2J.platform.auth.v1.ResolveEgressResponseHeadersRequest.ResponseHeadersEntryR\x0fresponseHeaders\x12g\n" +
	"\x18simple_replacement_rules\x18\b \x03(\v2-.platform.auth.v1.EgressSimpleReplacementRuleR\x16simpleReplacementRules\x12G\n" +
	"\aheaders\x18\t \x03(\v2-.platform.auth.v1.EgressHeaderReplacementItemR\aheaders\x120\n" +
	"\x14allowed_header_names\x18\n" +
	" \x03(\tR\x12allowedHeaderNames\x12L\n" +
	"\x0eruntime_source\x18\v \x01(\v2%.platform.auth.v1.EgressRequestSourceR\rruntimeSource\x12\x1f\n" +
	"\vtarget_path\x18\f \x01(\tR\n" +
	"targetPath\x12\x1f\n" +
	"\vstatus_code\x18\r \x01(\rR\n" +
	"statusCode\x12.\n" +
	"\x13header_value_prefix\x18\x0e \x01(\tR\x11headerValuePrefix\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x1bEgressHeaderReplacementItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rcurrent_value\x18\x02 \x01(\tR\fcurrentValue\"\xc1\x01\n" +
	"\x1bEgressSimpleReplacementRule\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1f\n" +
	"\vheader_name\x18\x02 \x01(\tR\n" +
	"headerName\x12!\n" +
	"\fmaterial_key\x18\x03 \x01(\tR\vmaterialKey\x12.\n" +
	"\x13header_value_prefix\x18\x04 \x01(\tR\x11headerValuePrefix\x12\x1a\n" +
	"\btemplate\x18\x05 \x01(\tR\btemplate\"\x96\x02\n" +
	"#ResolveEgressRequestHeadersResponse\x12\\\n" +
	"\aheaders\x18\x01 \x03(\v2B.platform.auth.v1.ResolveEgressRequestHeadersResponse.HeadersEntryR\aheaders\x12%\n" +
	"\x0eremove_headers\x18\x02 \x03(\tR\rremoveHeaders\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\askipped\x18\x04 \x01(\bR\askipped\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"$ResolveEgressResponseHeadersResponse\x12]\n" +
	"\aheaders\x18\x01 \x03(\v2C.platform.auth.v1.ResolveEgressResponseHeadersResponse.HeadersEntryR\aheaders\x12%\n" +
	"\x0eremove_headers\x18\x02 \x03(\tR\rremoveHeaders\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\askipped\x18\x04 \x01(\bR\askipped\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\x13EgressRequestSource\x125\n" +
	"\x03pod\x18\x01 \x01(\v2!.platform.auth.v1.EgressPodSourceH\x00R\x03pod\x12\x17\n" +
	"\x06run_id\x18\x02 \x01(\tH\x00R\x05runId\x12!\n" +
	"\vworkload_id\x18\x03 \x01(\tH\x00R\n" +
	"workloadIdB\b\n" +
	"\x06source\"e\n" +
	"\x0fEgressPodSource\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ipB8Z6code-code.internal/go-contract/platform/auth/v1;authv1b\x06proto3"

var (
	file_platform_auth_v1_egress_auth_proto_rawDescOnce sync.Once
	file_platform_auth_v1_egress_auth_proto_rawDescData []byte
)

func file_platform_auth_v1_egress_auth_proto_rawDescGZIP() []byte {
	file_platform_auth_v1_egress_auth_proto_rawDescOnce.Do(func() {
		file_platform_auth_v1_egress_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_auth_v1_egress_auth_proto_rawDesc), len(file_platform_auth_v1_egress_auth_proto_rawDesc)))
	})
	return file_platform_auth_v1_egress_auth_proto_rawDescData
}

var file_platform_auth_v1_egress_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_platform_auth_v1_egress_auth_proto_goTypes = []any{
	(*ResolveEgressRequestHeadersRequest)(nil),   // 0: platform.auth.v1.ResolveEgressRequestHeadersRequest
	(*ResolveEgressResponseHeadersRequest)(nil),  // 1: platform.auth.v1.ResolveEgressResponseHeadersRequest
	(*EgressHeaderReplacementItem)(nil),          // 2: platform.auth.v1.EgressHeaderReplacementItem
	(*EgressSimpleReplacementRule)(nil),          // 3: platform.auth.v1.EgressSimpleReplacementRule
	(*ResolveEgressRequestHeadersResponse)(nil),  // 4: platform.auth.v1.ResolveEgressRequestHeadersResponse
	(*ResolveEgressResponseHeadersResponse)(nil), // 5: platform.auth.v1.ResolveEgressResponseHeadersResponse
	(*EgressRequestSource)(nil),                  // 6: platform.auth.v1.EgressRequestSource
	(*EgressPodSource)(nil),                      // 7: platform.auth.v1.EgressPodSource
	nil,                                          // 8: platform.auth.v1.ResolveEgressRequestHeadersRequest.RequestHeadersEntry
	nil,                                          // 9: platform.auth.v1.ResolveEgressResponseHeadersRequest.RequestHeadersEntry
	nil,                                          // 10: platform.auth.v1.ResolveEgressResponseHeadersRequest.ResponseHeadersEntry
	nil,                                          // 11: platform.auth.v1.ResolveEgressRequestHeadersResponse.HeadersEntry
	nil,                                          // 12: platform.auth.v1.ResolveEgressResponseHeadersResponse.HeadersEntry
}
var file_platform_auth_v1_egress_auth_proto_depIdxs = []int32{
	8,  // 0: platform.auth.v1.ResolveEgressRequestHeadersRequest.request_headers:type_name -> platform.auth.v1.ResolveEgressRequestHeadersRequest.RequestHeadersEntry
	3,  // 1: platform.auth.v1.ResolveEgressRequestHeadersRequest.simple_replacement_rules:type_name -> platform.auth.v1.EgressSimpleReplacementRule
	2,  // 2: platform.auth.v1.ResolveEgressRequestHeadersRequest.headers:type_name -> platform.auth.v1.EgressHeaderReplacementItem
	6,  // 3: platform.auth.v1.ResolveEgressRequestHeadersRequest.runtime_source:type_name -> platform.auth.v1.EgressRequestSource
	9,  // 4: platform.auth.v1.ResolveEgressResponseHeadersRequest.request_headers:type_name -> platform.auth.v1.ResolveEgressResponseHeadersRequest.RequestHeadersEntry
	10, // 5: platform.auth.v1.ResolveEgressResponseHeadersRequest.response_headers:type_name -> platform.auth.v1.ResolveEgressResponseHeadersRequest.ResponseHeadersEntry
	3,  // 6: platform.auth.v1.ResolveEgressResponseHeadersRequest.simple_replacement_rules:type_name -> platform.auth.v1.EgressSimpleReplacementRule
	2,  // 7: platform.auth.v1.ResolveEgressResponseHeadersRequest.headers:type_name -> platform.auth.v1.EgressHeaderReplacementItem
	6,  // 8: platform.auth.v1.ResolveEgressResponseHeadersRequest.runtime_source:type_name -> platform.auth.v1.EgressRequestSource
	11, // 9: platform.auth.v1.ResolveEgressRequestHeadersResponse.headers:type_name -> platform.auth.v1.ResolveEgressRequestHeadersResponse.HeadersEntry
	12, // 10: platform.auth.v1.ResolveEgressResponseHeadersResponse.headers:type_name -> platform.auth.v1.ResolveEgressResponseHeadersResponse.HeadersEntry
	7,  // 11: platform.auth.v1.EgressRequestSource.pod:type_name -> platform.auth.v1.EgressPodSource
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_platform_auth_v1_egress_auth_proto_init() }
func file_platform_auth_v1_egress_auth_proto_init() {
	if File_platform_auth_v1_egress_auth_proto != nil {
		return
	}
	file_platform_auth_v1_egress_auth_proto_msgTypes[6].OneofWrappers = []any{
		(*EgressRequestSource_Pod)(nil),
		(*EgressRequestSource_RunId)(nil),
		(*EgressRequestSource_WorkloadId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_auth_v1_egress_auth_proto_rawDesc), len(file_platform_auth_v1_egress_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_auth_v1_egress_auth_proto_goTypes,
		DependencyIndexes: file_platform_auth_v1_egress_auth_proto_depIdxs,
		MessageInfos:      file_platform_auth_v1_egress_auth_proto_msgTypes,
	}.Build()
	File_platform_auth_v1_egress_auth_proto = out.File
	file_platform_auth_v1_egress_auth_proto_goTypes = nil
	file_platform_auth_v1_egress_auth_proto_depIdxs = nil
}
