global:
  imageRegistry: localhost:5001
  imageTag: dev-local
  consoleBaseUrl: http://console.localhost

consoleIngress:
  host: console.localhost
  tlsEnabled: false
  tlsSecretName: console-local-unused
  sslRedirect: false
