// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/model/v1/model_service.proto

package modelservicev1connect

import (
	v1 "code-code.internal/go-contract/platform/model/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModelServiceName is the fully-qualified name of the ModelService service.
	ModelServiceName = "platform.model.v1.ModelService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModelServiceListModelsProcedure is the fully-qualified name of the ModelService's ListModels RPC.
	ModelServiceListModelsProcedure = "/platform.model.v1.ModelService/ListModels"
	// ModelServiceResolveModelRefProcedure is the fully-qualified name of the ModelService's
	// ResolveModelRef RPC.
	ModelServiceResolveModelRefProcedure = "/platform.model.v1.ModelService/ResolveModelRef"
	// ModelServiceGetModelVersionProcedure is the fully-qualified name of the ModelService's
	// GetModelVersion RPC.
	ModelServiceGetModelVersionProcedure = "/platform.model.v1.ModelService/GetModelVersion"
	// ModelServiceSyncModelDefinitionsProcedure is the fully-qualified name of the ModelService's
	// SyncModelDefinitions RPC.
	ModelServiceSyncModelDefinitionsProcedure = "/platform.model.v1.ModelService/SyncModelDefinitions"
	// ModelServiceGetModelCardProcedure is the fully-qualified name of the ModelService's GetModelCard
	// RPC.
	ModelServiceGetModelCardProcedure = "/platform.model.v1.ModelService/GetModelCard"
)

// ModelServiceClient is a client for the platform.model.v1.ModelService service.
type ModelServiceClient interface {
	ListModels(context.Context, *v1.ListModelsRequest) (*v1.ListModelsResponse, error)
	ResolveModelRef(context.Context, *v1.ResolveModelRefRequest) (*v1.ResolveModelRefResponse, error)
	GetModelVersion(context.Context, *v1.GetModelVersionRequest) (*v1.GetModelVersionResponse, error)
	SyncModelDefinitions(context.Context, *v1.SyncModelDefinitionsRequest) (*v1.SyncModelDefinitionsResponse, error)
	GetModelCard(context.Context, *v1.GetModelCardRequest) (*v1.GetModelCardResponse, error)
}

// NewModelServiceClient constructs a client for the platform.model.v1.ModelService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModelServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModelServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	modelServiceMethods := v1.File_platform_model_v1_model_service_proto.Services().ByName("ModelService").Methods()
	return &modelServiceClient{
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+ModelServiceListModelsProcedure,
			connect.WithSchema(modelServiceMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		resolveModelRef: connect.NewClient[v1.ResolveModelRefRequest, v1.ResolveModelRefResponse](
			httpClient,
			baseURL+ModelServiceResolveModelRefProcedure,
			connect.WithSchema(modelServiceMethods.ByName("ResolveModelRef")),
			connect.WithClientOptions(opts...),
		),
		getModelVersion: connect.NewClient[v1.GetModelVersionRequest, v1.GetModelVersionResponse](
			httpClient,
			baseURL+ModelServiceGetModelVersionProcedure,
			connect.WithSchema(modelServiceMethods.ByName("GetModelVersion")),
			connect.WithClientOptions(opts...),
		),
		syncModelDefinitions: connect.NewClient[v1.SyncModelDefinitionsRequest, v1.SyncModelDefinitionsResponse](
			httpClient,
			baseURL+ModelServiceSyncModelDefinitionsProcedure,
			connect.WithSchema(modelServiceMethods.ByName("SyncModelDefinitions")),
			connect.WithClientOptions(opts...),
		),
		getModelCard: connect.NewClient[v1.GetModelCardRequest, v1.GetModelCardResponse](
			httpClient,
			baseURL+ModelServiceGetModelCardProcedure,
			connect.WithSchema(modelServiceMethods.ByName("GetModelCard")),
			connect.WithClientOptions(opts...),
		),
	}
}

// modelServiceClient implements ModelServiceClient.
type modelServiceClient struct {
	listModels           *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	resolveModelRef      *connect.Client[v1.ResolveModelRefRequest, v1.ResolveModelRefResponse]
	getModelVersion      *connect.Client[v1.GetModelVersionRequest, v1.GetModelVersionResponse]
	syncModelDefinitions *connect.Client[v1.SyncModelDefinitionsRequest, v1.SyncModelDefinitionsResponse]
	getModelCard         *connect.Client[v1.GetModelCardRequest, v1.GetModelCardResponse]
}

// ListModels calls platform.model.v1.ModelService.ListModels.
func (c *modelServiceClient) ListModels(ctx context.Context, req *v1.ListModelsRequest) (*v1.ListModelsResponse, error) {
	response, err := c.listModels.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ResolveModelRef calls platform.model.v1.ModelService.ResolveModelRef.
func (c *modelServiceClient) ResolveModelRef(ctx context.Context, req *v1.ResolveModelRefRequest) (*v1.ResolveModelRefResponse, error) {
	response, err := c.resolveModelRef.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetModelVersion calls platform.model.v1.ModelService.GetModelVersion.
func (c *modelServiceClient) GetModelVersion(ctx context.Context, req *v1.GetModelVersionRequest) (*v1.GetModelVersionResponse, error) {
	response, err := c.getModelVersion.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SyncModelDefinitions calls platform.model.v1.ModelService.SyncModelDefinitions.
func (c *modelServiceClient) SyncModelDefinitions(ctx context.Context, req *v1.SyncModelDefinitionsRequest) (*v1.SyncModelDefinitionsResponse, error) {
	response, err := c.syncModelDefinitions.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetModelCard calls platform.model.v1.ModelService.GetModelCard.
func (c *modelServiceClient) GetModelCard(ctx context.Context, req *v1.GetModelCardRequest) (*v1.GetModelCardResponse, error) {
	response, err := c.getModelCard.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ModelServiceHandler is an implementation of the platform.model.v1.ModelService service.
type ModelServiceHandler interface {
	ListModels(context.Context, *v1.ListModelsRequest) (*v1.ListModelsResponse, error)
	ResolveModelRef(context.Context, *v1.ResolveModelRefRequest) (*v1.ResolveModelRefResponse, error)
	GetModelVersion(context.Context, *v1.GetModelVersionRequest) (*v1.GetModelVersionResponse, error)
	SyncModelDefinitions(context.Context, *v1.SyncModelDefinitionsRequest) (*v1.SyncModelDefinitionsResponse, error)
	GetModelCard(context.Context, *v1.GetModelCardRequest) (*v1.GetModelCardResponse, error)
}

// NewModelServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModelServiceHandler(svc ModelServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	modelServiceMethods := v1.File_platform_model_v1_model_service_proto.Services().ByName("ModelService").Methods()
	modelServiceListModelsHandler := connect.NewUnaryHandlerSimple(
		ModelServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(modelServiceMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	modelServiceResolveModelRefHandler := connect.NewUnaryHandlerSimple(
		ModelServiceResolveModelRefProcedure,
		svc.ResolveModelRef,
		connect.WithSchema(modelServiceMethods.ByName("ResolveModelRef")),
		connect.WithHandlerOptions(opts...),
	)
	modelServiceGetModelVersionHandler := connect.NewUnaryHandlerSimple(
		ModelServiceGetModelVersionProcedure,
		svc.GetModelVersion,
		connect.WithSchema(modelServiceMethods.ByName("GetModelVersion")),
		connect.WithHandlerOptions(opts...),
	)
	modelServiceSyncModelDefinitionsHandler := connect.NewUnaryHandlerSimple(
		ModelServiceSyncModelDefinitionsProcedure,
		svc.SyncModelDefinitions,
		connect.WithSchema(modelServiceMethods.ByName("SyncModelDefinitions")),
		connect.WithHandlerOptions(opts...),
	)
	modelServiceGetModelCardHandler := connect.NewUnaryHandlerSimple(
		ModelServiceGetModelCardProcedure,
		svc.GetModelCard,
		connect.WithSchema(modelServiceMethods.ByName("GetModelCard")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.model.v1.ModelService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModelServiceListModelsProcedure:
			modelServiceListModelsHandler.ServeHTTP(w, r)
		case ModelServiceResolveModelRefProcedure:
			modelServiceResolveModelRefHandler.ServeHTTP(w, r)
		case ModelServiceGetModelVersionProcedure:
			modelServiceGetModelVersionHandler.ServeHTTP(w, r)
		case ModelServiceSyncModelDefinitionsProcedure:
			modelServiceSyncModelDefinitionsHandler.ServeHTTP(w, r)
		case ModelServiceGetModelCardProcedure:
			modelServiceGetModelCardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModelServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModelServiceHandler struct{}

func (UnimplementedModelServiceHandler) ListModels(context.Context, *v1.ListModelsRequest) (*v1.ListModelsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.model.v1.ModelService.ListModels is not implemented"))
}

func (UnimplementedModelServiceHandler) ResolveModelRef(context.Context, *v1.ResolveModelRefRequest) (*v1.ResolveModelRefResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.model.v1.ModelService.ResolveModelRef is not implemented"))
}

func (UnimplementedModelServiceHandler) GetModelVersion(context.Context, *v1.GetModelVersionRequest) (*v1.GetModelVersionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.model.v1.ModelService.GetModelVersion is not implemented"))
}

func (UnimplementedModelServiceHandler) SyncModelDefinitions(context.Context, *v1.SyncModelDefinitionsRequest) (*v1.SyncModelDefinitionsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.model.v1.ModelService.SyncModelDefinitions is not implemented"))
}

func (UnimplementedModelServiceHandler) GetModelCard(context.Context, *v1.GetModelCardRequest) (*v1.GetModelCardResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.model.v1.ModelService.GetModelCard is not implemented"))
}
