// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/core/v1/agent.proto

package corev1

import (
	v1 "code-code.internal/go-contract/agent/cap/v1"
	v11 "code-code.internal/go-contract/agent/input/v1"
	v12 "code-code.internal/go-contract/agent/policy/v1"
	v13 "code-code.internal/go-contract/provider/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentDescriptor describes an agent provider that can be selected by the platform.
type AgentDescriptor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderId     string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Capabilities   *v1.Capabilities       `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	InputSchema    *v11.InputSchema       `protobuf:"bytes,4,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	ProviderFilter *v12.ProviderFilter    `protobuf:"bytes,5,opt,name=provider_filter,json=providerFilter,proto3" json:"provider_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentDescriptor) Reset() {
	*x = AgentDescriptor{}
	mi := &file_agent_core_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescriptor) ProtoMessage() {}

func (x *AgentDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_agent_core_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescriptor.ProtoReflect.Descriptor instead.
func (*AgentDescriptor) Descriptor() ([]byte, []int) {
	return file_agent_core_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentDescriptor) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AgentDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AgentDescriptor) GetCapabilities() *v1.Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentDescriptor) GetInputSchema() *v11.InputSchema {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *AgentDescriptor) GetProviderFilter() *v12.ProviderFilter {
	if x != nil {
		return x.ProviderFilter
	}
	return nil
}

// RuntimeEnvironment describes the local runtime roots provided by the platform.
type RuntimeEnvironment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceDir  string                 `protobuf:"bytes,1,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	DataDir       string                 `protobuf:"bytes,2,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEnvironment) Reset() {
	*x = RuntimeEnvironment{}
	mi := &file_agent_core_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEnvironment) ProtoMessage() {}

func (x *RuntimeEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_agent_core_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEnvironment.ProtoReflect.Descriptor instead.
func (*RuntimeEnvironment) Descriptor() ([]byte, []int) {
	return file_agent_core_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeEnvironment) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

func (x *RuntimeEnvironment) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

// RunRequest is the platform input for starting one run.
type RunRequest struct {
	state                 protoimpl.MessageState     `protogen:"open.v1"`
	RunId                 string                     `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TraceId               string                     `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Input                 *v11.RunInput              `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	ResumeToken           string                     `protobuf:"bytes,4,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
	ResolvedProviderModel *v13.ResolvedProviderModel `protobuf:"bytes,5,opt,name=resolved_provider_model,json=resolvedProviderModel,proto3" json:"resolved_provider_model,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_agent_core_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_core_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_agent_core_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RunRequest) GetInput() *v11.RunInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunRequest) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *RunRequest) GetResolvedProviderModel() *v13.ResolvedProviderModel {
	if x != nil {
		return x.ResolvedProviderModel
	}
	return nil
}

var File_agent_core_v1_agent_proto protoreflect.FileDescriptor

const file_agent_core_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x19agent/core/v1/agent.proto\x12\ragent.core.v1\x1a\x16agent/cap/v1/cap.proto\x1a\x1aagent/input/v1/input.proto\x1a\x1cagent/policy/v1/policy.proto\x1a\x1aprovider/v1/provider.proto\"\x9f\x02\n" +
	"\x0fAgentDescriptor\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12>\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x1a.agent.cap.v1.CapabilitiesR\fcapabilities\x12>\n" +
	"\finput_schema\x18\x04 \x01(\v2\x1b.agent.input.v1.InputSchemaR\vinputSchema\x12H\n" +
	"\x0fprovider_filter\x18\x05 \x01(\v2\x1f.agent.policy.v1.ProviderFilterR\x0eproviderFilter\"T\n" +
	"\x12RuntimeEnvironment\x12#\n" +
	"\rworkspace_dir\x18\x01 \x01(\tR\fworkspaceDir\x12\x19\n" +
	"\bdata_dir\x18\x02 \x01(\tR\adataDir\"\xed\x01\n" +
	"\n" +
	"RunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12.\n" +
	"\x05input\x18\x03 \x01(\v2\x18.agent.input.v1.RunInputR\x05input\x12!\n" +
	"\fresume_token\x18\x04 \x01(\tR\vresumeToken\x12Z\n" +
	"\x17resolved_provider_model\x18\x05 \x01(\v2\".provider.v1.ResolvedProviderModelR\x15resolvedProviderModelB5Z3code-code.internal/go-contract/agent/core/v1;corev1b\x06proto3"

var (
	file_agent_core_v1_agent_proto_rawDescOnce sync.Once
	file_agent_core_v1_agent_proto_rawDescData []byte
)

func file_agent_core_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_core_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_core_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_core_v1_agent_proto_rawDesc), len(file_agent_core_v1_agent_proto_rawDesc)))
	})
	return file_agent_core_v1_agent_proto_rawDescData
}

var file_agent_core_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agent_core_v1_agent_proto_goTypes = []any{
	(*AgentDescriptor)(nil),           // 0: agent.core.v1.AgentDescriptor
	(*RuntimeEnvironment)(nil),        // 1: agent.core.v1.RuntimeEnvironment
	(*RunRequest)(nil),                // 2: agent.core.v1.RunRequest
	(*v1.Capabilities)(nil),           // 3: agent.cap.v1.Capabilities
	(*v11.InputSchema)(nil),           // 4: agent.input.v1.InputSchema
	(*v12.ProviderFilter)(nil),        // 5: agent.policy.v1.ProviderFilter
	(*v11.RunInput)(nil),              // 6: agent.input.v1.RunInput
	(*v13.ResolvedProviderModel)(nil), // 7: provider.v1.ResolvedProviderModel
}
var file_agent_core_v1_agent_proto_depIdxs = []int32{
	3, // 0: agent.core.v1.AgentDescriptor.capabilities:type_name -> agent.cap.v1.Capabilities
	4, // 1: agent.core.v1.AgentDescriptor.input_schema:type_name -> agent.input.v1.InputSchema
	5, // 2: agent.core.v1.AgentDescriptor.provider_filter:type_name -> agent.policy.v1.ProviderFilter
	6, // 3: agent.core.v1.RunRequest.input:type_name -> agent.input.v1.RunInput
	7, // 4: agent.core.v1.RunRequest.resolved_provider_model:type_name -> provider.v1.ResolvedProviderModel
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_agent_core_v1_agent_proto_init() }
func file_agent_core_v1_agent_proto_init() {
	if File_agent_core_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_core_v1_agent_proto_rawDesc), len(file_agent_core_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_core_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_core_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_core_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_core_v1_agent_proto = out.File
	file_agent_core_v1_agent_proto_goTypes = nil
	file_agent_core_v1_agent_proto_depIdxs = nil
}
