// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/rule/v1/rule.proto

package rulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Rule describes one reusable rule instruction.
type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_platform_rule_v1_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_platform_rule_v1_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_platform_rule_v1_rule_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_platform_rule_v1_rule_proto protoreflect.FileDescriptor

const file_platform_rule_v1_rule_proto_rawDesc = "" +
	"\n" +
	"\x1bplatform/rule/v1/rule.proto\x12\x10platform.rule.v1\"o\n" +
	"\x04Rule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontentB8Z6code-code.internal/go-contract/platform/rule/v1;rulev1b\x06proto3"

var (
	file_platform_rule_v1_rule_proto_rawDescOnce sync.Once
	file_platform_rule_v1_rule_proto_rawDescData []byte
)

func file_platform_rule_v1_rule_proto_rawDescGZIP() []byte {
	file_platform_rule_v1_rule_proto_rawDescOnce.Do(func() {
		file_platform_rule_v1_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_rule_v1_rule_proto_rawDesc), len(file_platform_rule_v1_rule_proto_rawDesc)))
	})
	return file_platform_rule_v1_rule_proto_rawDescData
}

var file_platform_rule_v1_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_platform_rule_v1_rule_proto_goTypes = []any{
	(*Rule)(nil), // 0: platform.rule.v1.Rule
}
var file_platform_rule_v1_rule_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platform_rule_v1_rule_proto_init() }
func file_platform_rule_v1_rule_proto_init() {
	if File_platform_rule_v1_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_rule_v1_rule_proto_rawDesc), len(file_platform_rule_v1_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_rule_v1_rule_proto_goTypes,
		DependencyIndexes: file_platform_rule_v1_rule_proto_depIdxs,
		MessageInfos:      file_platform_rule_v1_rule_proto_msgTypes,
	}.Build()
	File_platform_rule_v1_rule_proto = out.File
	file_platform_rule_v1_rule_proto_goTypes = nil
	file_platform_rule_v1_rule_proto_depIdxs = nil
}
