apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: alerting
spec:
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-headless
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: alerting
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
    - name: cluster-tcp
      port: 9094
      protocol: TCP
      targetPort: cluster-tcp
    - name: cluster-udp
      port: 9094
      protocol: UDP
      targetPort: cluster-udp

