// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agent/runtime_sidecar/v1/runtime_sidecar.proto

package runtimesidecarv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CLIOutputSidecarService_GetAccumulator_FullMethodName = "/agent.runtime_sidecar.v1.CLIOutputSidecarService/GetAccumulator"
	CLIOutputSidecarService_Stop_FullMethodName           = "/agent.runtime_sidecar.v1.CLIOutputSidecarService/Stop"
)

// CLIOutputSidecarServiceClient is the client API for CLIOutputSidecarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CLIOutputSidecarService is the pod-local query/control surface exposed by
// the CLI output parsing sidecar.
type CLIOutputSidecarServiceClient interface {
	// GetAccumulator returns the current accumulated assistant/reasoning text.
	GetAccumulator(ctx context.Context, in *GetAccumulatorRequest, opts ...grpc.CallOption) (*GetAccumulatorResponse, error)
	// Stop requests the current run to stop.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type cLIOutputSidecarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCLIOutputSidecarServiceClient(cc grpc.ClientConnInterface) CLIOutputSidecarServiceClient {
	return &cLIOutputSidecarServiceClient{cc}
}

func (c *cLIOutputSidecarServiceClient) GetAccumulator(ctx context.Context, in *GetAccumulatorRequest, opts ...grpc.CallOption) (*GetAccumulatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccumulatorResponse)
	err := c.cc.Invoke(ctx, CLIOutputSidecarService_GetAccumulator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIOutputSidecarServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, CLIOutputSidecarService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CLIOutputSidecarServiceServer is the server API for CLIOutputSidecarService service.
// All implementations must embed UnimplementedCLIOutputSidecarServiceServer
// for forward compatibility.
//
// CLIOutputSidecarService is the pod-local query/control surface exposed by
// the CLI output parsing sidecar.
type CLIOutputSidecarServiceServer interface {
	// GetAccumulator returns the current accumulated assistant/reasoning text.
	GetAccumulator(context.Context, *GetAccumulatorRequest) (*GetAccumulatorResponse, error)
	// Stop requests the current run to stop.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedCLIOutputSidecarServiceServer()
}

// UnimplementedCLIOutputSidecarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCLIOutputSidecarServiceServer struct{}

func (UnimplementedCLIOutputSidecarServiceServer) GetAccumulator(context.Context, *GetAccumulatorRequest) (*GetAccumulatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccumulator not implemented")
}
func (UnimplementedCLIOutputSidecarServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedCLIOutputSidecarServiceServer) mustEmbedUnimplementedCLIOutputSidecarServiceServer() {
}
func (UnimplementedCLIOutputSidecarServiceServer) testEmbeddedByValue() {}

// UnsafeCLIOutputSidecarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CLIOutputSidecarServiceServer will
// result in compilation errors.
type UnsafeCLIOutputSidecarServiceServer interface {
	mustEmbedUnimplementedCLIOutputSidecarServiceServer()
}

func RegisterCLIOutputSidecarServiceServer(s grpc.ServiceRegistrar, srv CLIOutputSidecarServiceServer) {
	// If the following call pancis, it indicates UnimplementedCLIOutputSidecarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CLIOutputSidecarService_ServiceDesc, srv)
}

func _CLIOutputSidecarService_GetAccumulator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccumulatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIOutputSidecarServiceServer).GetAccumulator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIOutputSidecarService_GetAccumulator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIOutputSidecarServiceServer).GetAccumulator(ctx, req.(*GetAccumulatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIOutputSidecarService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIOutputSidecarServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIOutputSidecarService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIOutputSidecarServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CLIOutputSidecarService_ServiceDesc is the grpc.ServiceDesc for CLIOutputSidecarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CLIOutputSidecarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.runtime_sidecar.v1.CLIOutputSidecarService",
	HandlerType: (*CLIOutputSidecarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccumulator",
			Handler:    _CLIOutputSidecarService_GetAccumulator_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _CLIOutputSidecarService_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/runtime_sidecar/v1/runtime_sidecar.proto",
}
