// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vendor_definition/v1/vendor.proto

package vendordefinitionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VendorRef references one vendor by stable identity.
type VendorRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      string                 `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorRef) Reset() {
	*x = VendorRef{}
	mi := &file_vendor_definition_v1_vendor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorRef) ProtoMessage() {}

func (x *VendorRef) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_definition_v1_vendor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorRef.ProtoReflect.Descriptor instead.
func (*VendorRef) Descriptor() ([]byte, []int) {
	return file_vendor_definition_v1_vendor_proto_rawDescGZIP(), []int{0}
}

func (x *VendorRef) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

// Vendor describes one AI service provider.
type Vendor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier aligned with ModelDefinition.vendor_id.
	// Examples: "openai", "anthropic", "google", "deepseek".
	VendorId string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	// Human-readable display name (e.g. "OpenAI").
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Public vendor logo URL, typically hosted by the vendor website.
	IconUrl string `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	// Official website.
	WebsiteUrl string `protobuf:"bytes,4,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	// Short description.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Stable alternate identifiers accepted from source catalogs.
	Aliases       []string `protobuf:"bytes,7,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	mi := &file_vendor_definition_v1_vendor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_definition_v1_vendor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_vendor_definition_v1_vendor_proto_rawDescGZIP(), []int{1}
}

func (x *Vendor) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *Vendor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Vendor) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Vendor) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *Vendor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vendor) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

var File_vendor_definition_v1_vendor_proto protoreflect.FileDescriptor

const file_vendor_definition_v1_vendor_proto_rawDesc = "" +
	"\n" +
	"!vendor_definition/v1/vendor.proto\x12\x14vendor_definition.v1\"(\n" +
	"\tVendorRef\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\tR\bvendorId\"\xcc\x01\n" +
	"\x06Vendor\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\tR\bvendorId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x1f\n" +
	"\vwebsite_url\x18\x04 \x01(\tR\n" +
	"websiteUrl\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aaliases\x18\a \x03(\tR\aaliasesJ\x04\b\x06\x10\aR\x04kindBHZFcode-code.internal/go-contract/vendor_definition/v1;vendordefinitionv1b\x06proto3"

var (
	file_vendor_definition_v1_vendor_proto_rawDescOnce sync.Once
	file_vendor_definition_v1_vendor_proto_rawDescData []byte
)

func file_vendor_definition_v1_vendor_proto_rawDescGZIP() []byte {
	file_vendor_definition_v1_vendor_proto_rawDescOnce.Do(func() {
		file_vendor_definition_v1_vendor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vendor_definition_v1_vendor_proto_rawDesc), len(file_vendor_definition_v1_vendor_proto_rawDesc)))
	})
	return file_vendor_definition_v1_vendor_proto_rawDescData
}

var file_vendor_definition_v1_vendor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vendor_definition_v1_vendor_proto_goTypes = []any{
	(*VendorRef)(nil), // 0: vendor_definition.v1.VendorRef
	(*Vendor)(nil),    // 1: vendor_definition.v1.Vendor
}
var file_vendor_definition_v1_vendor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vendor_definition_v1_vendor_proto_init() }
func file_vendor_definition_v1_vendor_proto_init() {
	if File_vendor_definition_v1_vendor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vendor_definition_v1_vendor_proto_rawDesc), len(file_vendor_definition_v1_vendor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vendor_definition_v1_vendor_proto_goTypes,
		DependencyIndexes: file_vendor_definition_v1_vendor_proto_depIdxs,
		MessageInfos:      file_vendor_definition_v1_vendor_proto_msgTypes,
	}.Build()
	File_vendor_definition_v1_vendor_proto = out.File
	file_vendor_definition_v1_vendor_proto_goTypes = nil
	file_vendor_definition_v1_vendor_proto_depIdxs = nil
}
