{{- if .Values.components.waypoints.enabled }}
{{- range $namespace := list .Values.global.platformNamespace .Values.global.infraNamespace .Values.global.runNamespace .Values.global.observabilityNamespace }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: {{ $namespace }}
  labels:
{{ include "istio-platform.labels" (dict "root" $ "name" (printf "%s-waypoint" $namespace) "componentLabel" "ambient-waypoint") | nindent 4 }}
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
---
{{- end }}
{{- end }}
