{{- if .Values.components.controlPlaneEgress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: control-plane-default-deny-egress
  namespace: {{ .Values.global.platformNamespace }}
  labels:
{{ include "istio-platform.labels" (dict "root" . "name" "control-plane-default-deny-egress" "componentLabel" "network-policy") | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: control-plane-egress
  namespace: {{ .Values.global.platformNamespace }}
  labels:
{{ include "istio-platform.labels" (dict "root" . "name" "control-plane-egress" "componentLabel" "network-policy") | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.platformNamespace }}
          podSelector: {}
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 172.16.0.0/12
        - ipBlock:
            cidr: 192.168.0.0/16
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.infraNamespace }}
          podSelector: {}
      ports:
        - protocol: TCP
          port: 4222
        - protocol: TCP
          port: 4318
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 9090
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.runNamespace }}
          podSelector:
            matchLabels:
              code-code.internal/runtime: platform-lightweight-http-workflow
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.egressNamespace }}
      ports:
        - protocol: TCP
          port: 15008
        - protocol: TCP
          port: 443
{{- end }}
