// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/oauth/v1/oauth.proto

package oauthv1

import (
	v1 "code-code.internal/go-contract/credential/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartOAuthAuthorizationSessionRequest struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	CliId              string                    `protobuf:"bytes,1,opt,name=cli_id,json=cliId,proto3" json:"cli_id,omitempty"`
	Flow               v1.OAuthAuthorizationFlow `protobuf:"varint,2,opt,name=flow,proto3,enum=credential.v1.OAuthAuthorizationFlow" json:"flow,omitempty"`
	TargetCredentialId string                    `protobuf:"bytes,4,opt,name=target_credential_id,json=targetCredentialId,proto3" json:"target_credential_id,omitempty"`
	TargetDisplayName  string                    `protobuf:"bytes,5,opt,name=target_display_name,json=targetDisplayName,proto3" json:"target_display_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartOAuthAuthorizationSessionRequest) Reset() {
	*x = StartOAuthAuthorizationSessionRequest{}
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOAuthAuthorizationSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOAuthAuthorizationSessionRequest) ProtoMessage() {}

func (x *StartOAuthAuthorizationSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOAuthAuthorizationSessionRequest.ProtoReflect.Descriptor instead.
func (*StartOAuthAuthorizationSessionRequest) Descriptor() ([]byte, []int) {
	return file_platform_oauth_v1_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *StartOAuthAuthorizationSessionRequest) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

func (x *StartOAuthAuthorizationSessionRequest) GetFlow() v1.OAuthAuthorizationFlow {
	if x != nil {
		return x.Flow
	}
	return v1.OAuthAuthorizationFlow(0)
}

func (x *StartOAuthAuthorizationSessionRequest) GetTargetCredentialId() string {
	if x != nil {
		return x.TargetCredentialId
	}
	return ""
}

func (x *StartOAuthAuthorizationSessionRequest) GetTargetDisplayName() string {
	if x != nil {
		return x.TargetDisplayName
	}
	return ""
}

type StartOAuthAuthorizationSessionResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Session       *v1.OAuthAuthorizationSessionState `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOAuthAuthorizationSessionResponse) Reset() {
	*x = StartOAuthAuthorizationSessionResponse{}
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOAuthAuthorizationSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOAuthAuthorizationSessionResponse) ProtoMessage() {}

func (x *StartOAuthAuthorizationSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOAuthAuthorizationSessionResponse.ProtoReflect.Descriptor instead.
func (*StartOAuthAuthorizationSessionResponse) Descriptor() ([]byte, []int) {
	return file_platform_oauth_v1_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *StartOAuthAuthorizationSessionResponse) GetSession() *v1.OAuthAuthorizationSessionState {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetOAuthAuthorizationSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthAuthorizationSessionRequest) Reset() {
	*x = GetOAuthAuthorizationSessionRequest{}
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthAuthorizationSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthAuthorizationSessionRequest) ProtoMessage() {}

func (x *GetOAuthAuthorizationSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthAuthorizationSessionRequest.ProtoReflect.Descriptor instead.
func (*GetOAuthAuthorizationSessionRequest) Descriptor() ([]byte, []int) {
	return file_platform_oauth_v1_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *GetOAuthAuthorizationSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetOAuthAuthorizationSessionResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Session       *v1.OAuthAuthorizationSessionState `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthAuthorizationSessionResponse) Reset() {
	*x = GetOAuthAuthorizationSessionResponse{}
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthAuthorizationSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthAuthorizationSessionResponse) ProtoMessage() {}

func (x *GetOAuthAuthorizationSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthAuthorizationSessionResponse.ProtoReflect.Descriptor instead.
func (*GetOAuthAuthorizationSessionResponse) Descriptor() ([]byte, []int) {
	return file_platform_oauth_v1_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *GetOAuthAuthorizationSessionResponse) GetSession() *v1.OAuthAuthorizationSessionState {
	if x != nil {
		return x.Session
	}
	return nil
}

type CancelOAuthAuthorizationSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOAuthAuthorizationSessionRequest) Reset() {
	*x = CancelOAuthAuthorizationSessionRequest{}
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOAuthAuthorizationSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOAuthAuthorizationSessionRequest) ProtoMessage() {}

func (x *CancelOAuthAuthorizationSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOAuthAuthorizationSessionRequest.ProtoReflect.Descriptor instead.
func (*CancelOAuthAuthorizationSessionRequest) Descriptor() ([]byte, []int) {
	return file_platform_oauth_v1_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOAuthAuthorizationSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CancelOAuthAuthorizationSessionResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Session       *v1.OAuthAuthorizationSessionState `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOAuthAuthorizationSessionResponse) Reset() {
	*x = CancelOAuthAuthorizationSessionResponse{}
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOAuthAuthorizationSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOAuthAuthorizationSessionResponse) ProtoMessage() {}

func (x *CancelOAuthAuthorizationSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOAuthAuthorizationSessionResponse.ProtoReflect.Descriptor instead.
func (*CancelOAuthAuthorizationSessionResponse) Descriptor() ([]byte, []int) {
	return file_platform_oauth_v1_oauth_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOAuthAuthorizationSessionResponse) GetSession() *v1.OAuthAuthorizationSessionState {
	if x != nil {
		return x.Session
	}
	return nil
}

type RecordOAuthCodeCallbackRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProviderId          string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Code                string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	State               string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ProviderRedirectUri string                 `protobuf:"bytes,4,opt,name=provider_redirect_uri,json=providerRedirectUri,proto3" json:"provider_redirect_uri,omitempty"`
	Error               string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription    string                 `protobuf:"bytes,6,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecordOAuthCodeCallbackRequest) Reset() {
	*x = RecordOAuthCodeCallbackRequest{}
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordOAuthCodeCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordOAuthCodeCallbackRequest) ProtoMessage() {}

func (x *RecordOAuthCodeCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordOAuthCodeCallbackRequest.ProtoReflect.Descriptor instead.
func (*RecordOAuthCodeCallbackRequest) Descriptor() ([]byte, []int) {
	return file_platform_oauth_v1_oauth_proto_rawDescGZIP(), []int{6}
}

func (x *RecordOAuthCodeCallbackRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *RecordOAuthCodeCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RecordOAuthCodeCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RecordOAuthCodeCallbackRequest) GetProviderRedirectUri() string {
	if x != nil {
		return x.ProviderRedirectUri
	}
	return ""
}

func (x *RecordOAuthCodeCallbackRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RecordOAuthCodeCallbackRequest) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

type RecordOAuthCodeCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordOAuthCodeCallbackResponse) Reset() {
	*x = RecordOAuthCodeCallbackResponse{}
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordOAuthCodeCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordOAuthCodeCallbackResponse) ProtoMessage() {}

func (x *RecordOAuthCodeCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_oauth_v1_oauth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordOAuthCodeCallbackResponse.ProtoReflect.Descriptor instead.
func (*RecordOAuthCodeCallbackResponse) Descriptor() ([]byte, []int) {
	return file_platform_oauth_v1_oauth_proto_rawDescGZIP(), []int{7}
}

func (x *RecordOAuthCodeCallbackResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_platform_oauth_v1_oauth_proto protoreflect.FileDescriptor

const file_platform_oauth_v1_oauth_proto_rawDesc = "" +
	"\n" +
	"\x1dplatform/oauth/v1/oauth.proto\x12\x11platform.oauth.v1\x1a/credential/v1/oauth_authorization_session.proto\"\xf4\x01\n" +
	"%StartOAuthAuthorizationSessionRequest\x12\x15\n" +
	"\x06cli_id\x18\x01 \x01(\tR\x05cliId\x129\n" +
	"\x04flow\x18\x02 \x01(\x0e2%.credential.v1.OAuthAuthorizationFlowR\x04flow\x120\n" +
	"\x14target_credential_id\x18\x04 \x01(\tR\x12targetCredentialId\x12.\n" +
	"\x13target_display_name\x18\x05 \x01(\tR\x11targetDisplayNameJ\x04\b\x03\x10\x04R\x11network_policy_id\"q\n" +
	"&StartOAuthAuthorizationSessionResponse\x12G\n" +
	"\asession\x18\x01 \x01(\v2-.credential.v1.OAuthAuthorizationSessionStateR\asession\"D\n" +
	"#GetOAuthAuthorizationSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"o\n" +
	"$GetOAuthAuthorizationSessionResponse\x12G\n" +
	"\asession\x18\x01 \x01(\v2-.credential.v1.OAuthAuthorizationSessionStateR\asession\"G\n" +
	"&CancelOAuthAuthorizationSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"r\n" +
	"'CancelOAuthAuthorizationSessionResponse\x12G\n" +
	"\asession\x18\x01 \x01(\v2-.credential.v1.OAuthAuthorizationSessionStateR\asession\"\xe2\x01\n" +
	"\x1eRecordOAuthCodeCallbackRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x122\n" +
	"\x15provider_redirect_uri\x18\x04 \x01(\tR\x13providerRedirectUri\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12+\n" +
	"\x11error_description\x18\x06 \x01(\tR\x10errorDescription\"@\n" +
	"\x1fRecordOAuthCodeCallbackResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId2\xda\x03\n" +
	"\x13OAuthSessionService\x12\x95\x01\n" +
	"\x1eStartOAuthAuthorizationSession\x128.platform.oauth.v1.StartOAuthAuthorizationSessionRequest\x1a9.platform.oauth.v1.StartOAuthAuthorizationSessionResponse\x12\x8f\x01\n" +
	"\x1cGetOAuthAuthorizationSession\x126.platform.oauth.v1.GetOAuthAuthorizationSessionRequest\x1a7.platform.oauth.v1.GetOAuthAuthorizationSessionResponse\x12\x98\x01\n" +
	"\x1fCancelOAuthAuthorizationSession\x129.platform.oauth.v1.CancelOAuthAuthorizationSessionRequest\x1a:.platform.oauth.v1.CancelOAuthAuthorizationSessionResponse2\x99\x01\n" +
	"\x14OAuthCallbackService\x12\x80\x01\n" +
	"\x17RecordOAuthCodeCallback\x121.platform.oauth.v1.RecordOAuthCodeCallbackRequest\x1a2.platform.oauth.v1.RecordOAuthCodeCallbackResponseB:Z8code-code.internal/go-contract/platform/oauth/v1;oauthv1b\x06proto3"

var (
	file_platform_oauth_v1_oauth_proto_rawDescOnce sync.Once
	file_platform_oauth_v1_oauth_proto_rawDescData []byte
)

func file_platform_oauth_v1_oauth_proto_rawDescGZIP() []byte {
	file_platform_oauth_v1_oauth_proto_rawDescOnce.Do(func() {
		file_platform_oauth_v1_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_oauth_v1_oauth_proto_rawDesc), len(file_platform_oauth_v1_oauth_proto_rawDesc)))
	})
	return file_platform_oauth_v1_oauth_proto_rawDescData
}

var file_platform_oauth_v1_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_platform_oauth_v1_oauth_proto_goTypes = []any{
	(*StartOAuthAuthorizationSessionRequest)(nil),   // 0: platform.oauth.v1.StartOAuthAuthorizationSessionRequest
	(*StartOAuthAuthorizationSessionResponse)(nil),  // 1: platform.oauth.v1.StartOAuthAuthorizationSessionResponse
	(*GetOAuthAuthorizationSessionRequest)(nil),     // 2: platform.oauth.v1.GetOAuthAuthorizationSessionRequest
	(*GetOAuthAuthorizationSessionResponse)(nil),    // 3: platform.oauth.v1.GetOAuthAuthorizationSessionResponse
	(*CancelOAuthAuthorizationSessionRequest)(nil),  // 4: platform.oauth.v1.CancelOAuthAuthorizationSessionRequest
	(*CancelOAuthAuthorizationSessionResponse)(nil), // 5: platform.oauth.v1.CancelOAuthAuthorizationSessionResponse
	(*RecordOAuthCodeCallbackRequest)(nil),          // 6: platform.oauth.v1.RecordOAuthCodeCallbackRequest
	(*RecordOAuthCodeCallbackResponse)(nil),         // 7: platform.oauth.v1.RecordOAuthCodeCallbackResponse
	(v1.OAuthAuthorizationFlow)(0),                  // 8: credential.v1.OAuthAuthorizationFlow
	(*v1.OAuthAuthorizationSessionState)(nil),       // 9: credential.v1.OAuthAuthorizationSessionState
}
var file_platform_oauth_v1_oauth_proto_depIdxs = []int32{
	8, // 0: platform.oauth.v1.StartOAuthAuthorizationSessionRequest.flow:type_name -> credential.v1.OAuthAuthorizationFlow
	9, // 1: platform.oauth.v1.StartOAuthAuthorizationSessionResponse.session:type_name -> credential.v1.OAuthAuthorizationSessionState
	9, // 2: platform.oauth.v1.GetOAuthAuthorizationSessionResponse.session:type_name -> credential.v1.OAuthAuthorizationSessionState
	9, // 3: platform.oauth.v1.CancelOAuthAuthorizationSessionResponse.session:type_name -> credential.v1.OAuthAuthorizationSessionState
	0, // 4: platform.oauth.v1.OAuthSessionService.StartOAuthAuthorizationSession:input_type -> platform.oauth.v1.StartOAuthAuthorizationSessionRequest
	2, // 5: platform.oauth.v1.OAuthSessionService.GetOAuthAuthorizationSession:input_type -> platform.oauth.v1.GetOAuthAuthorizationSessionRequest
	4, // 6: platform.oauth.v1.OAuthSessionService.CancelOAuthAuthorizationSession:input_type -> platform.oauth.v1.CancelOAuthAuthorizationSessionRequest
	6, // 7: platform.oauth.v1.OAuthCallbackService.RecordOAuthCodeCallback:input_type -> platform.oauth.v1.RecordOAuthCodeCallbackRequest
	1, // 8: platform.oauth.v1.OAuthSessionService.StartOAuthAuthorizationSession:output_type -> platform.oauth.v1.StartOAuthAuthorizationSessionResponse
	3, // 9: platform.oauth.v1.OAuthSessionService.GetOAuthAuthorizationSession:output_type -> platform.oauth.v1.GetOAuthAuthorizationSessionResponse
	5, // 10: platform.oauth.v1.OAuthSessionService.CancelOAuthAuthorizationSession:output_type -> platform.oauth.v1.CancelOAuthAuthorizationSessionResponse
	7, // 11: platform.oauth.v1.OAuthCallbackService.RecordOAuthCodeCallback:output_type -> platform.oauth.v1.RecordOAuthCodeCallbackResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_platform_oauth_v1_oauth_proto_init() }
func file_platform_oauth_v1_oauth_proto_init() {
	if File_platform_oauth_v1_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_oauth_v1_oauth_proto_rawDesc), len(file_platform_oauth_v1_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_platform_oauth_v1_oauth_proto_goTypes,
		DependencyIndexes: file_platform_oauth_v1_oauth_proto_depIdxs,
		MessageInfos:      file_platform_oauth_v1_oauth_proto_msgTypes,
	}.Build()
	File_platform_oauth_v1_oauth_proto = out.File
	file_platform_oauth_v1_oauth_proto_goTypes = nil
	file_platform_oauth_v1_oauth_proto_depIdxs = nil
}
