#!/usr/bin/env bash
# Environment defaults for release commands.

NAMESPACE="${NAMESPACE:-code-code}"
RUN_NAMESPACE="${RUN_NAMESPACE:-${NAMESPACE}-runs}"
INFRA_NAMESPACE="${INFRA_NAMESPACE:-${NAMESPACE}-infra}"
OBSERVABILITY_NAMESPACE="${OBSERVABILITY_NAMESPACE:-${NAMESPACE}-observability}"
IMAGE_REGISTRY="${IMAGE_REGISTRY:-}"
IMAGE_PUSH_REGISTRY="${IMAGE_PUSH_REGISTRY:-${IMAGE_REGISTRY}}"
CONTAINER_NERDCTL_NAMESPACE="${CONTAINER_NERDCTL_NAMESPACE:-}"

default_image_tag() {
  local head
  head="$(git -C "${REPO_ROOT}" rev-parse --short HEAD)"
  if ! git -C "${REPO_ROOT}" diff --quiet ||
    ! git -C "${REPO_ROOT}" diff --cached --quiet ||
    [ -n "$(git -C "${REPO_ROOT}" status --porcelain --untracked-files=normal)" ]; then
    printf '%s-dirty-%s\n' "${head}" "$(date +%Y%m%d%H%M%S)"
    return
  fi
  printf '%s\n' "${head}"
}

IMAGE_TAG="${IMAGE_TAG:-$(default_image_tag)}"
DEPLOY_INFRA_MODE="${DEPLOY_INFRA_MODE:-auto}"
CONSOLE_INGRESS_KUSTOMIZE_PATH="${CONSOLE_INGRESS_KUSTOMIZE_PATH:-}"
LOCAL_INGRESS_BIND_IP="${LOCAL_INGRESS_BIND_IP:-}"
CONSOLE_INGRESS_HOST="${CONSOLE_INGRESS_HOST:-}"
CONSOLE_INGRESS_SSL_REDIRECT="${CONSOLE_INGRESS_SSL_REDIRECT:-}"
CONSOLE_INGRESS_TLS_ENABLED="${CONSOLE_INGRESS_TLS_ENABLED:-}"
CONSOLE_INGRESS_TLS_SECRET_NAME="${CONSOLE_INGRESS_TLS_SECRET_NAME:-}"
CONSOLE_INGRESS_EXTRA_HOSTS="${CONSOLE_INGRESS_EXTRA_HOSTS:-}"
WASM_IMAGE_REGISTRY="${WASM_IMAGE_REGISTRY:-${IMAGE_REGISTRY}}"
WASM_IMAGE_PUSH_REGISTRY="${WASM_IMAGE_PUSH_REGISTRY:-${WASM_IMAGE_REGISTRY}}"
WASM_INSECURE_REGISTRIES="${WASM_INSECURE_REGISTRIES:-}"
DEPLOY_PUSH_WASM_IMAGES="${DEPLOY_PUSH_WASM_IMAGES:-auto}"
ISTIO_VERSION="${ISTIO_VERSION:-1.29.2}"
ISTIO_NAMESPACE="${ISTIO_NAMESPACE:-istio-system}"
ISTIO_HELM_TIMEOUT="${ISTIO_HELM_TIMEOUT:-60s}"
ISTIOD_REQUEST_CPU="${ISTIOD_REQUEST_CPU:-100m}"
ISTIOD_REQUEST_MEMORY="${ISTIOD_REQUEST_MEMORY:-512Mi}"
ISTIOD_LIMIT_CPU="${ISTIOD_LIMIT_CPU:-1000m}"
ISTIOD_LIMIT_MEMORY="${ISTIOD_LIMIT_MEMORY:-1Gi}"
ZTUNNEL_REQUEST_CPU="${ZTUNNEL_REQUEST_CPU:-50m}"
ZTUNNEL_REQUEST_MEMORY="${ZTUNNEL_REQUEST_MEMORY:-128Mi}"
ZTUNNEL_LIMIT_CPU="${ZTUNNEL_LIMIT_CPU:-500m}"
ZTUNNEL_LIMIT_MEMORY="${ZTUNNEL_LIMIT_MEMORY:-512Mi}"
ISTIO_EGRESS_GATEWAY_RELEASE="${ISTIO_EGRESS_GATEWAY_RELEASE:-code-code-egressgateway}"
ISTIO_EGRESS_GATEWAY_NAMESPACE="${ISTIO_EGRESS_GATEWAY_NAMESPACE:-code-code-net}"
ISTIO_OTEL_COLLECTOR_SERVICE="${ISTIO_OTEL_COLLECTOR_SERVICE:-otel-collector.${OBSERVABILITY_NAMESPACE}.svc.cluster.local}"
INGRESS_NGINX_HELM_RELEASE="${INGRESS_NGINX_HELM_RELEASE:-ingress-nginx}"
INGRESS_NGINX_NAMESPACE="${INGRESS_NGINX_NAMESPACE:-ingress-nginx}"
INGRESS_NGINX_VERSION="${INGRESS_NGINX_VERSION:-}"
INGRESS_NGINX_HELM_TIMEOUT="${INGRESS_NGINX_HELM_TIMEOUT:-60s}"
INGRESS_NGINX_VALUES_FILE="${INGRESS_NGINX_VALUES_FILE:-}"
TEMPORAL_HELM_TIMEOUT="${TEMPORAL_HELM_TIMEOUT:-60s}"
TEMPORAL_HELM_RELEASE="${TEMPORAL_HELM_RELEASE:-temporal}"
GATEWAY_API_VERSION="${GATEWAY_API_VERSION:-v1.4.0}"
CERT_MANAGER_VERSION="${CERT_MANAGER_VERSION:-v1.20.2}"
TRUST_MANAGER_VERSION="${TRUST_MANAGER_VERSION:-v0.22.1}"
CERT_MANAGER_NAMESPACE="${CERT_MANAGER_NAMESPACE:-cert-manager}"
CERT_MANAGER_HELM_TIMEOUT="${CERT_MANAGER_HELM_TIMEOUT:-60s}"
KIALI_OPERATOR_VERSION="${KIALI_OPERATOR_VERSION:-2.25.0}"
KIALI_OPERATOR_HELM_TIMEOUT="${KIALI_OPERATOR_HELM_TIMEOUT:-60s}"
KIALI_INGRESS_CLASS_NAME="${KIALI_INGRESS_CLASS_NAME:-}"
KIALI_INGRESS_HOST="${KIALI_INGRESS_HOST:-}"
KIALI_INGRESS_PATH="${KIALI_INGRESS_PATH:-}"
KIALI_INGRESS_TLS_ENABLED="${KIALI_INGRESS_TLS_ENABLED:-}"
KIALI_INGRESS_TLS_SECRET_NAME="${KIALI_INGRESS_TLS_SECRET_NAME:-}"
GRAFANA_INGRESS_CLASS_NAME="${GRAFANA_INGRESS_CLASS_NAME:-}"
GRAFANA_INGRESS_HOST="${GRAFANA_INGRESS_HOST:-}"
GRAFANA_INGRESS_PATH="${GRAFANA_INGRESS_PATH:-}"
GRAFANA_INGRESS_TLS_ENABLED="${GRAFANA_INGRESS_TLS_ENABLED:-}"
GRAFANA_INGRESS_TLS_SECRET_NAME="${GRAFANA_INGRESS_TLS_SECRET_NAME:-}"
GRAFANA_ANONYMOUS_ORG_ROLE="${GRAFANA_ANONYMOUS_ORG_ROLE:-}"
GRAFANA_VIEWERS_CAN_EDIT="${GRAFANA_VIEWERS_CAN_EDIT:-}"
GRAFANA_EXPLORE_ENABLED="${GRAFANA_EXPLORE_ENABLED:-}"
ISTIO_PLATFORM_TELEMETRY_ENABLED="${ISTIO_PLATFORM_TELEMETRY_ENABLED:-false}"
HELM_HISTORY_MAX="${HELM_HISTORY_MAX:-2}"
HELM_REPO_UPDATE_MODE="${HELM_REPO_UPDATE_MODE:-on-demand}"
CHART_VERSION="${CHART_VERSION:-}"
CHART_APP_VERSION="${CHART_APP_VERSION:-}"
CHART_PACKAGE_DIR="${CHART_PACKAGE_DIR:-${REPO_ROOT}/dist/charts}"
CHART_OCI_REGISTRY="${CHART_OCI_REGISTRY:-}"
CLUSTER_BOOTSTRAP_HELM_RELEASE="${CLUSTER_BOOTSTRAP_HELM_RELEASE:-code-code-cluster-bootstrap}"
CLUSTER_ADDONS_HELM_RELEASE="${CLUSTER_ADDONS_HELM_RELEASE:-code-code-cluster-addons}"
DEV_IMAGE_INFRA_HELM_RELEASE="${DEV_IMAGE_INFRA_HELM_RELEASE:-code-code-dev-image-infra}"
INFRASTRUCTURE_CORE_HELM_RELEASE="${INFRASTRUCTURE_CORE_HELM_RELEASE:-code-code-infrastructure-core}"
INFRASTRUCTURE_ADDONS_HELM_RELEASE="${INFRASTRUCTURE_ADDONS_HELM_RELEASE:-code-code-infrastructure-addons}"
PLATFORM_HELM_RELEASE="${PLATFORM_HELM_RELEASE:-code-code-platform}"
PLATFORM_NOTIFICATIONS_HELM_RELEASE="${PLATFORM_NOTIFICATIONS_HELM_RELEASE:-code-code-platform-notifications}"
ISTIO_PLATFORM_HELM_RELEASE="${ISTIO_PLATFORM_HELM_RELEASE:-code-code-istio-platform}"
KIALI_OPERATOR_HELM_RELEASE="${KIALI_OPERATOR_HELM_RELEASE:-kiali-operator}"
CACHE_DIR="${CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/code-code/buildx}"
CACHE_REF_PREFIX="${CACHE_REF_PREFIX:-}"
IMAGE_KEEP_RECENT_IMAGES="${IMAGE_KEEP_RECENT_IMAGES:-2}"
IMAGE_GC_UNTIL_DAYS="${IMAGE_GC_UNTIL_DAYS:-14}"
IMAGE_GC_AFTER_BUILD="${IMAGE_GC_AFTER_BUILD:-1}"
FORCE_RESTART="${FORCE_RESTART:-}"
PLATFORM_ROLLOUT_TIMEOUT="${PLATFORM_ROLLOUT_TIMEOUT:-60s}"
DEPLOY_IMAGE_PREFLIGHT_ENABLED="${DEPLOY_IMAGE_PREFLIGHT_ENABLED:-true}"
DEPLOY_IMAGE_PREFLIGHT_TIMEOUT="${DEPLOY_IMAGE_PREFLIGHT_TIMEOUT:-45s}"
NOTIFICATION_INGRESS_ENABLED="${NOTIFICATION_INGRESS_ENABLED:-}"
NOTIFICATION_INGRESS_PRIMARY_HOST="${NOTIFICATION_INGRESS_PRIMARY_HOST:-}"
NOTIFICATION_INGRESS_SECONDARY_HOST="${NOTIFICATION_INGRESS_SECONDARY_HOST:-}"
NOTIFICATION_INGRESS_TLS_SECRET_NAME="${NOTIFICATION_INGRESS_TLS_SECRET_NAME:-}"
CLOUDFLARE_DDNS_DOMAINS="${CLOUDFLARE_DDNS_DOMAINS:-webhook.example.com}"
CLOUDFLARE_DDNS_PROXIED="${CLOUDFLARE_DDNS_PROXIED:-true}"
CLOUDFLARE_DDNS_IP4_PROVIDER="${CLOUDFLARE_DDNS_IP4_PROVIDER:-cloudflare.trace}"
CLOUDFLARE_DDNS_IP6_PROVIDER="${CLOUDFLARE_DDNS_IP6_PROVIDER:-none}"
CLOUDFLARE_DDNS_UPDATE_CRON="${CLOUDFLARE_DDNS_UPDATE_CRON:-@every 5m}"
CLOUDFLARE_DDNS_UPDATE_ON_START="${CLOUDFLARE_DDNS_UPDATE_ON_START:-true}"
ALLOY_CLUSTER_NAME="${ALLOY_CLUSTER_NAME:-${NAMESPACE}}"
ALLOY_LOKI_WRITE_URL="${ALLOY_LOKI_WRITE_URL:-}"
ALERTMANAGER_WECHAT_API_CORP_ID="${ALERTMANAGER_WECHAT_API_CORP_ID:-<REPLACE_WITH_WECHAT_CORP_ID>}"
ALERTMANAGER_WECHAT_AGENT_ID="${ALERTMANAGER_WECHAT_AGENT_ID:-<REPLACE_WITH_WECHAT_AGENT_ID>}"
ALERTMANAGER_WECHAT_PARTY_ID="${ALERTMANAGER_WECHAT_PARTY_ID:-<REPLACE_WITH_WECHAT_PARTY_ID>}"
SECRETS_ENV_FILE="${SECRETS_ENV_FILE:-${SCRIPT_DIR}/secrets.env}"
LOCAL_PROXY_ENV_FILE="${LOCAL_PROXY_ENV_FILE:-${SCRIPT_DIR}/local.proxy.env}"
LOCAL_PROXY_SCRIPT_FILE="${LOCAL_PROXY_SCRIPT_FILE:-${SCRIPT_DIR}/local.proxy.sh}"
PLATFORM_KUBERNETES_SERVICE_CIDR="${PLATFORM_KUBERNETES_SERVICE_CIDR:-}"
PLATFORM_API_SERVER_CIDR="${PLATFORM_API_SERVER_CIDR:-}"
PLATFORM_EGRESS_PRESET_PROXY_URL="${PLATFORM_EGRESS_PRESET_PROXY_URL:-http://127.0.0.1:10809}"
DEV_IMAGE_INFRA_REGISTRY_IMAGE="${DEV_IMAGE_INFRA_REGISTRY_IMAGE:-registry:2.8.3}"
DEV_IMAGE_INFRA_REGISTRY_SERVICE_TYPE="${DEV_IMAGE_INFRA_REGISTRY_SERVICE_TYPE:-NodePort}"
DEV_IMAGE_INFRA_REGISTRY_NODE_PORT="${DEV_IMAGE_INFRA_REGISTRY_NODE_PORT:-30500}"
DEV_IMAGE_INFRA_CACHE_IMAGE="${DEV_IMAGE_INFRA_CACHE_IMAGE:-registry:2.8.3}"
DEV_IMAGE_INFRA_CACHE_SERVICE_TYPE="${DEV_IMAGE_INFRA_CACHE_SERVICE_TYPE:-NodePort}"
DEV_IMAGE_INFRA_CACHE_DOCKER_IO_NODE_PORT="${DEV_IMAGE_INFRA_CACHE_DOCKER_IO_NODE_PORT:-30502}"
DEV_IMAGE_INFRA_CACHE_REGISTRY_K8S_IO_NODE_PORT="${DEV_IMAGE_INFRA_CACHE_REGISTRY_K8S_IO_NODE_PORT:-30503}"
DEV_IMAGE_INFRA_CACHE_QUAY_IO_NODE_PORT="${DEV_IMAGE_INFRA_CACHE_QUAY_IO_NODE_PORT:-30504}"

default_git_source_context() {
  git -C "${REPO_ROOT}" config --get remote.origin.url 2>/dev/null || true
}

default_git_source_revision() {
  git -C "${REPO_ROOT}" symbolic-ref --short HEAD 2>/dev/null ||
    git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null ||
    printf 'main\n'
}

cap_timeout_max_one_minute() {
  local value="${1:-}"
  local unit number

  if [ -z "${value}" ]; then
    printf '60s\n'
    return 0
  fi

  unit="${value: -1}"
  number="${value%?}"
  if ! [[ "${number}" =~ ^[0-9]+$ ]]; then
    printf '60s\n'
    return 0
  fi

  case "${unit}" in
    s)
      if [ "${number}" -gt 60 ]; then
        printf '60s\n'
      else
        printf '%ss\n' "${number}"
      fi
      ;;
    m)
      printf '60s\n'
      ;;
    *)
      printf '60s\n'
      ;;
  esac
}

ISTIO_HELM_TIMEOUT="$(cap_timeout_max_one_minute "${ISTIO_HELM_TIMEOUT}")"
INGRESS_NGINX_HELM_TIMEOUT="$(cap_timeout_max_one_minute "${INGRESS_NGINX_HELM_TIMEOUT}")"
TEMPORAL_HELM_TIMEOUT="$(cap_timeout_max_one_minute "${TEMPORAL_HELM_TIMEOUT}")"
CERT_MANAGER_HELM_TIMEOUT="$(cap_timeout_max_one_minute "${CERT_MANAGER_HELM_TIMEOUT}")"
KIALI_OPERATOR_HELM_TIMEOUT="$(cap_timeout_max_one_minute "${KIALI_OPERATOR_HELM_TIMEOUT}")"
PLATFORM_ROLLOUT_TIMEOUT="$(cap_timeout_max_one_minute "${PLATFORM_ROLLOUT_TIMEOUT}")"
DEPLOY_IMAGE_PREFLIGHT_TIMEOUT="$(cap_timeout_max_one_minute "${DEPLOY_IMAGE_PREFLIGHT_TIMEOUT}")"

if [ -z "${DEPLOY_EGRESS_PREFLIGHT+x}" ]; then
  if [ -n "${CI:-}" ]; then DEPLOY_EGRESS_PREFLIGHT="required"; else DEPLOY_EGRESS_PREFLIGHT="skip"; fi
fi

if [ -f "${SECRETS_ENV_FILE}" ]; then
  # shellcheck source=/dev/null
  source "${SECRETS_ENV_FILE}"
fi

if [ -f "${LOCAL_PROXY_ENV_FILE}" ]; then
  # shellcheck source=/dev/null
  source "${LOCAL_PROXY_ENV_FILE}"
fi

if [ -f "${LOCAL_PROXY_SCRIPT_FILE}" ]; then
  # shellcheck source=/dev/null
  source "${LOCAL_PROXY_SCRIPT_FILE}"
fi

BUILD_HTTP_PROXY="${BUILD_HTTP_PROXY:-}"
BUILD_HTTPS_PROXY="${BUILD_HTTPS_PROXY:-}"
BUILD_NO_PROXY="${BUILD_NO_PROXY:-}"
CLI_RUNTIME_IMAGE_REGISTRY_PREFIX="${CLI_RUNTIME_IMAGE_REGISTRY_PREFIX:-${IMAGE_REGISTRY}}"
CLI_RUNTIME_IMAGE_REGISTRY_LOOKUP_PREFIX="${CLI_RUNTIME_IMAGE_REGISTRY_LOOKUP_PREFIX:-${CLI_RUNTIME_IMAGE_REGISTRY_PREFIX}}"
CLI_RUNTIME_IMAGE_REGISTRY_LOOKUP_INSECURE="${CLI_RUNTIME_IMAGE_REGISTRY_LOOKUP_INSECURE:-false}"
CLI_RUNTIME_IMAGE_BUILD_SOURCE_CONTEXT="${CLI_RUNTIME_IMAGE_BUILD_SOURCE_CONTEXT:-$(default_git_source_context)}"
CLI_RUNTIME_IMAGE_BUILD_SOURCE_REVISION="${CLI_RUNTIME_IMAGE_BUILD_SOURCE_REVISION:-$(default_git_source_revision)}"

if [ -z "${BUILD_NO_PULL+x}" ]; then
  if [ -z "${CI:-}" ]; then BUILD_NO_PULL="auto"; else BUILD_NO_PULL=""; fi
fi
case "$(printf '%s' "${BUILD_NO_PULL}" | tr '[:upper:]' '[:lower:]')" in
  auto|1|true|yes|on) BUILD_NO_PULL="auto" ;;
  *)                  BUILD_NO_PULL="always" ;;
esac

# shellcheck source=build.env
source "${SCRIPT_DIR}/build.env"

default_go_local_goarch() {
  case "$(uname -m)" in
    x86_64) echo amd64 ;;
    arm64|aarch64) echo arm64 ;;
    *) uname -m ;;
  esac
}

if [ -z "${BUILD_WEB_DIST_DIR+x}" ] && [ -n "${CONSOLE_WEB_DIST_DIR+x}" ]; then
  BUILD_WEB_DIST_DIR="${CONSOLE_WEB_DIST_DIR}"
elif [ -z "${BUILD_WEB_DIST_DIR+x}" ]; then
  BUILD_WEB_DIST_DIR="packages/console-web/app/dist"
fi
CONSOLE_WEB_DIST_DIR="${BUILD_WEB_DIST_DIR}"
GO_LOCAL_DIST_DIR="${GO_LOCAL_DIST_DIR:-.local-bin}"
GO_LOCAL_GOARCH="${GO_LOCAL_GOARCH:-$(default_go_local_goarch)}"
GO_LOCAL_GOOS="${GO_LOCAL_GOOS:-linux}"
GO_LOCAL_LDFLAGS="${GO_LOCAL_LDFLAGS:--s -w}"
GO_LOCAL_GOCACHE="${GO_LOCAL_GOCACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/code-code/go-build}"
GO_LOCAL_GOMODCACHE="${GO_LOCAL_GOMODCACHE:-$HOME/go/pkg/mod}"
GO_LOCAL_CA_BUNDLE="${GO_LOCAL_CA_BUNDLE:-}"
GO_LOCAL_ALLOW_MISSING_CA_BUNDLE="${GO_LOCAL_ALLOW_MISSING_CA_BUNDLE:-}"
GO_LOCAL_SKIP_MOD_DOWNLOAD="${GO_LOCAL_SKIP_MOD_DOWNLOAD:-}"

if [ -z "${BUILD_WEB_MODE+x}" ]; then
  if [ -n "${CI:-}" ]; then BUILD_WEB_MODE=docker; else BUILD_WEB_MODE=local; fi
fi
if [ -z "${BUILD_GO_MODE+x}" ]; then
  if [ -n "${CI:-}" ]; then BUILD_GO_MODE=docker; else BUILD_GO_MODE=local; fi
fi
BUILD_WEB_MODE="$(printf '%s' "${BUILD_WEB_MODE}" | tr '[:upper:]' '[:lower:]')"
case "${BUILD_WEB_MODE}" in docker|local) ;; *) BUILD_WEB_MODE=local ;; esac

BUILD_GO_MODE="$(printf '%s' "${BUILD_GO_MODE}" | tr '[:upper:]' '[:lower:]')"
case "${BUILD_GO_MODE}" in docker|local) ;; *) BUILD_GO_MODE=local ;; esac

BUILD_WEB_REBUILD="$(printf '%s' "${BUILD_WEB_REBUILD:-0}" | tr '[:upper:]' '[:lower:]')"
case "${BUILD_WEB_REBUILD}" in 1|true|yes|on) BUILD_WEB_REBUILD=1 ;; *) BUILD_WEB_REBUILD=0 ;; esac

POSTGRES_HOST="${POSTGRES_HOST:-postgres.${INFRA_NAMESPACE}.svc.cluster.local}"

export IMAGE_REGISTRY IMAGE_PUSH_REGISTRY IMAGE_TAG WASM_IMAGE_REGISTRY WASM_IMAGE_PUSH_REGISTRY WASM_INSECURE_REGISTRIES DEPLOY_PUSH_WASM_IMAGES
export NAMESPACE RUN_NAMESPACE INFRA_NAMESPACE OBSERVABILITY_NAMESPACE POSTGRES_HOST CONSOLE_INGRESS_KUSTOMIZE_PATH
export LOCAL_INGRESS_BIND_IP CONSOLE_INGRESS_HOST CONSOLE_INGRESS_SSL_REDIRECT CONSOLE_INGRESS_TLS_ENABLED CONSOLE_INGRESS_TLS_SECRET_NAME
export CONSOLE_INGRESS_EXTRA_HOSTS
export ISTIOD_REQUEST_CPU ISTIOD_REQUEST_MEMORY ISTIOD_LIMIT_CPU ISTIOD_LIMIT_MEMORY
export ZTUNNEL_REQUEST_CPU ZTUNNEL_REQUEST_MEMORY ZTUNNEL_LIMIT_CPU ZTUNNEL_LIMIT_MEMORY
export BUILD_HTTP_PROXY BUILD_HTTPS_PROXY BUILD_NO_PROXY
export CONTAINER_NERDCTL_NAMESPACE
export BUILD_NPM_REGISTRY BUILD_GOPROXY BUILD_PIP_INDEX_URL BUILD_DEBIAN_MIRROR
export CHART_VERSION CHART_APP_VERSION CHART_PACKAGE_DIR CHART_OCI_REGISTRY
export HELM_REPO_UPDATE_MODE
export CLUSTER_BOOTSTRAP_HELM_RELEASE CLUSTER_ADDONS_HELM_RELEASE DEV_IMAGE_INFRA_HELM_RELEASE
export INFRASTRUCTURE_CORE_HELM_RELEASE INFRASTRUCTURE_ADDONS_HELM_RELEASE
export PLATFORM_HELM_RELEASE PLATFORM_NOTIFICATIONS_HELM_RELEASE ISTIO_PLATFORM_HELM_RELEASE
export TEMPORAL_HELM_RELEASE KIALI_OPERATOR_HELM_RELEASE KIALI_OPERATOR_VERSION KIALI_OPERATOR_HELM_TIMEOUT
export INGRESS_NGINX_HELM_RELEASE INGRESS_NGINX_NAMESPACE INGRESS_NGINX_VERSION INGRESS_NGINX_HELM_TIMEOUT INGRESS_NGINX_VALUES_FILE
export KIALI_INGRESS_CLASS_NAME KIALI_INGRESS_HOST KIALI_INGRESS_PATH KIALI_INGRESS_TLS_ENABLED KIALI_INGRESS_TLS_SECRET_NAME
export GRAFANA_INGRESS_CLASS_NAME GRAFANA_INGRESS_HOST GRAFANA_INGRESS_PATH GRAFANA_INGRESS_TLS_ENABLED GRAFANA_INGRESS_TLS_SECRET_NAME
export GRAFANA_ANONYMOUS_ORG_ROLE GRAFANA_VIEWERS_CAN_EDIT GRAFANA_EXPLORE_ENABLED
export ISTIO_PLATFORM_TELEMETRY_ENABLED
export NOTIFICATION_INGRESS_ENABLED
export NOTIFICATION_INGRESS_PRIMARY_HOST NOTIFICATION_INGRESS_SECONDARY_HOST NOTIFICATION_INGRESS_TLS_SECRET_NAME
export CLOUDFLARE_DDNS_DOMAINS CLOUDFLARE_DDNS_PROXIED
export CLOUDFLARE_DDNS_IP4_PROVIDER CLOUDFLARE_DDNS_IP6_PROVIDER
export CLOUDFLARE_DDNS_UPDATE_CRON CLOUDFLARE_DDNS_UPDATE_ON_START
export ALLOY_CLUSTER_NAME ALLOY_LOKI_WRITE_URL
export ALERTMANAGER_WECHAT_API_CORP_ID ALERTMANAGER_WECHAT_AGENT_ID ALERTMANAGER_WECHAT_PARTY_ID
export PLATFORM_KUBERNETES_SERVICE_CIDR PLATFORM_API_SERVER_CIDR
export PLATFORM_EGRESS_PRESET_PROXY_URL
export PLATFORM_ROLLOUT_TIMEOUT DEPLOY_IMAGE_PREFLIGHT_ENABLED DEPLOY_IMAGE_PREFLIGHT_TIMEOUT
export DEV_IMAGE_INFRA_REGISTRY_IMAGE DEV_IMAGE_INFRA_REGISTRY_SERVICE_TYPE DEV_IMAGE_INFRA_REGISTRY_NODE_PORT
export DEV_IMAGE_INFRA_CACHE_IMAGE DEV_IMAGE_INFRA_CACHE_SERVICE_TYPE
export DEV_IMAGE_INFRA_CACHE_DOCKER_IO_NODE_PORT DEV_IMAGE_INFRA_CACHE_REGISTRY_K8S_IO_NODE_PORT DEV_IMAGE_INFRA_CACHE_QUAY_IO_NODE_PORT
