apiVersion: v1
kind: Namespace
metadata:
  name: code-code-net
  labels:
    app.kubernetes.io/part-of: code-code
    code-code.internal/purpose: node-networking
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
