apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: code-code-observability

resources:
  - configmap.yaml
  - ingress.yaml
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: grafana-dashboard-providers
    files:
      - provisioning/dashboardproviders.yaml
  - name: grafana-dashboards-platform
    files:
      - dashboards/cluster-resources.json
      - dashboards/istio-mesh.json
      - dashboards/platform-services.json

generatorOptions:
  disableNameSuffixHash: true
