apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "<REPLACE_WITH_GRAFANA_ADMIN_USER>"
  GF_SECURITY_ADMIN_PASSWORD: "<REPLACE_WITH_GRAFANA_ADMIN_PASSWORD>"
