tempo:
  enabled: true

loki:
  enabled: true

alloy:
  enabled: true

grafana:
  enabled: true
  anonymousOrgRole: Editor
  viewersCanEdit: true
  exploreEnabled: true

kiali:
  enabled: true
  ingress:
    enabled: true

cloudflareDdns:
  enabled: false
