apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-config
data:
  DOMAINS: webhook.example.com
  PROXIED: "true"
  IP4_PROVIDER: cloudflare.trace
  IP6_PROVIDER: none
  UPDATE_CRON: "@every 5m"
  UPDATE_ON_START: "true"
