// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/cli_runtime/v1/cli_runtime_service.proto

package cliruntimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCLIRuntimeRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CliId         string                 `protobuf:"bytes,1,opt,name=cli_id,json=cliId,proto3" json:"cli_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCLIRuntimeRecordsRequest) Reset() {
	*x = ListCLIRuntimeRecordsRequest{}
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCLIRuntimeRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCLIRuntimeRecordsRequest) ProtoMessage() {}

func (x *ListCLIRuntimeRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCLIRuntimeRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListCLIRuntimeRecordsRequest) Descriptor() ([]byte, []int) {
	return file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListCLIRuntimeRecordsRequest) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

type ListCLIRuntimeRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CLIRuntimeRecord    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCLIRuntimeRecordsResponse) Reset() {
	*x = ListCLIRuntimeRecordsResponse{}
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCLIRuntimeRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCLIRuntimeRecordsResponse) ProtoMessage() {}

func (x *ListCLIRuntimeRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCLIRuntimeRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListCLIRuntimeRecordsResponse) Descriptor() ([]byte, []int) {
	return file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListCLIRuntimeRecordsResponse) GetItems() []*CLIRuntimeRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetLatestAvailableCLIRuntimeImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CliId         string                 `protobuf:"bytes,1,opt,name=cli_id,json=cliId,proto3" json:"cli_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestAvailableCLIRuntimeImagesRequest) Reset() {
	*x = GetLatestAvailableCLIRuntimeImagesRequest{}
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestAvailableCLIRuntimeImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestAvailableCLIRuntimeImagesRequest) ProtoMessage() {}

func (x *GetLatestAvailableCLIRuntimeImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestAvailableCLIRuntimeImagesRequest.ProtoReflect.Descriptor instead.
func (*GetLatestAvailableCLIRuntimeImagesRequest) Descriptor() ([]byte, []int) {
	return file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestAvailableCLIRuntimeImagesRequest) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

type GetLatestAvailableCLIRuntimeImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CLIRuntimeImage     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestAvailableCLIRuntimeImagesResponse) Reset() {
	*x = GetLatestAvailableCLIRuntimeImagesResponse{}
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestAvailableCLIRuntimeImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestAvailableCLIRuntimeImagesResponse) ProtoMessage() {}

func (x *GetLatestAvailableCLIRuntimeImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestAvailableCLIRuntimeImagesResponse.ProtoReflect.Descriptor instead.
func (*GetLatestAvailableCLIRuntimeImagesResponse) Descriptor() ([]byte, []int) {
	return file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestAvailableCLIRuntimeImagesResponse) GetItems() []*CLIRuntimeImage {
	if x != nil {
		return x.Items
	}
	return nil
}

type CLIRuntimeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *CLIVersionSnapshot    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Images        []*CLIRuntimeImage     `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIRuntimeRecord) Reset() {
	*x = CLIRuntimeRecord{}
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIRuntimeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIRuntimeRecord) ProtoMessage() {}

func (x *CLIRuntimeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIRuntimeRecord.ProtoReflect.Descriptor instead.
func (*CLIRuntimeRecord) Descriptor() ([]byte, []int) {
	return file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescGZIP(), []int{4}
}

func (x *CLIRuntimeRecord) GetVersion() *CLIVersionSnapshot {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *CLIRuntimeRecord) GetImages() []*CLIRuntimeImage {
	if x != nil {
		return x.Images
	}
	return nil
}

type CLIVersionSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CliId         string                 `protobuf:"bytes,1,opt,name=cli_id,json=cliId,proto3" json:"cli_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIVersionSnapshot) Reset() {
	*x = CLIVersionSnapshot{}
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIVersionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIVersionSnapshot) ProtoMessage() {}

func (x *CLIVersionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIVersionSnapshot.ProtoReflect.Descriptor instead.
func (*CLIVersionSnapshot) Descriptor() ([]byte, []int) {
	return file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescGZIP(), []int{5}
}

func (x *CLIVersionSnapshot) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

func (x *CLIVersionSnapshot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CLIVersionSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CLIRuntimeImage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CliId           string                 `protobuf:"bytes,1,opt,name=cli_id,json=cliId,proto3" json:"cli_id,omitempty"`
	CliVersion      string                 `protobuf:"bytes,2,opt,name=cli_version,json=cliVersion,proto3" json:"cli_version,omitempty"`
	ExecutionClass  string                 `protobuf:"bytes,3,opt,name=execution_class,json=executionClass,proto3" json:"execution_class,omitempty"`
	BuildTarget     string                 `protobuf:"bytes,4,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	ImageRepository string                 `protobuf:"bytes,5,opt,name=image_repository,json=imageRepository,proto3" json:"image_repository,omitempty"`
	ImageTag        string                 `protobuf:"bytes,6,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	Image           string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CLIRuntimeImage) Reset() {
	*x = CLIRuntimeImage{}
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIRuntimeImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIRuntimeImage) ProtoMessage() {}

func (x *CLIRuntimeImage) ProtoReflect() protoreflect.Message {
	mi := &file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIRuntimeImage.ProtoReflect.Descriptor instead.
func (*CLIRuntimeImage) Descriptor() ([]byte, []int) {
	return file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescGZIP(), []int{6}
}

func (x *CLIRuntimeImage) GetCliId() string {
	if x != nil {
		return x.CliId
	}
	return ""
}

func (x *CLIRuntimeImage) GetCliVersion() string {
	if x != nil {
		return x.CliVersion
	}
	return ""
}

func (x *CLIRuntimeImage) GetExecutionClass() string {
	if x != nil {
		return x.ExecutionClass
	}
	return ""
}

func (x *CLIRuntimeImage) GetBuildTarget() string {
	if x != nil {
		return x.BuildTarget
	}
	return ""
}

func (x *CLIRuntimeImage) GetImageRepository() string {
	if x != nil {
		return x.ImageRepository
	}
	return ""
}

func (x *CLIRuntimeImage) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *CLIRuntimeImage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_platform_cli_runtime_v1_cli_runtime_service_proto protoreflect.FileDescriptor

const file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDesc = "" +
	"\n" +
	"1platform/cli_runtime/v1/cli_runtime_service.proto\x12\x17platform.cli_runtime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x1cListCLIRuntimeRecordsRequest\x12\x15\n" +
	"\x06cli_id\x18\x01 \x01(\tR\x05cliId\"`\n" +
	"\x1dListCLIRuntimeRecordsResponse\x12?\n" +
	"\x05items\x18\x01 \x03(\v2).platform.cli_runtime.v1.CLIRuntimeRecordR\x05items\"B\n" +
	")GetLatestAvailableCLIRuntimeImagesRequest\x12\x15\n" +
	"\x06cli_id\x18\x01 \x01(\tR\x05cliId\"l\n" +
	"*GetLatestAvailableCLIRuntimeImagesResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.platform.cli_runtime.v1.CLIRuntimeImageR\x05items\"\x9b\x01\n" +
	"\x10CLIRuntimeRecord\x12E\n" +
	"\aversion\x18\x01 \x01(\v2+.platform.cli_runtime.v1.CLIVersionSnapshotR\aversion\x12@\n" +
	"\x06images\x18\x02 \x03(\v2(.platform.cli_runtime.v1.CLIRuntimeImageR\x06images\"\x80\x01\n" +
	"\x12CLIVersionSnapshot\x12\x15\n" +
	"\x06cli_id\x18\x01 \x01(\tR\x05cliId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf3\x01\n" +
	"\x0fCLIRuntimeImage\x12\x15\n" +
	"\x06cli_id\x18\x01 \x01(\tR\x05cliId\x12\x1f\n" +
	"\vcli_version\x18\x02 \x01(\tR\n" +
	"cliVersion\x12'\n" +
	"\x0fexecution_class\x18\x03 \x01(\tR\x0eexecutionClass\x12!\n" +
	"\fbuild_target\x18\x04 \x01(\tR\vbuildTarget\x12)\n" +
	"\x10image_repository\x18\x05 \x01(\tR\x0fimageRepository\x12\x1b\n" +
	"\timage_tag\x18\x06 \x01(\tR\bimageTag\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image2\xcc\x02\n" +
	"\x11CLIRuntimeService\x12\x86\x01\n" +
	"\x15ListCLIRuntimeRecords\x125.platform.cli_runtime.v1.ListCLIRuntimeRecordsRequest\x1a6.platform.cli_runtime.v1.ListCLIRuntimeRecordsResponse\x12\xad\x01\n" +
	"\"GetLatestAvailableCLIRuntimeImages\x12B.platform.cli_runtime.v1.GetLatestAvailableCLIRuntimeImagesRequest\x1aC.platform.cli_runtime.v1.GetLatestAvailableCLIRuntimeImagesResponseBEZCcode-code.internal/go-contract/platform/cli_runtime/v1;cliruntimev1b\x06proto3"

var (
	file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescOnce sync.Once
	file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescData []byte
)

func file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescGZIP() []byte {
	file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescOnce.Do(func() {
		file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDesc), len(file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDesc)))
	})
	return file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDescData
}

var file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_platform_cli_runtime_v1_cli_runtime_service_proto_goTypes = []any{
	(*ListCLIRuntimeRecordsRequest)(nil),               // 0: platform.cli_runtime.v1.ListCLIRuntimeRecordsRequest
	(*ListCLIRuntimeRecordsResponse)(nil),              // 1: platform.cli_runtime.v1.ListCLIRuntimeRecordsResponse
	(*GetLatestAvailableCLIRuntimeImagesRequest)(nil),  // 2: platform.cli_runtime.v1.GetLatestAvailableCLIRuntimeImagesRequest
	(*GetLatestAvailableCLIRuntimeImagesResponse)(nil), // 3: platform.cli_runtime.v1.GetLatestAvailableCLIRuntimeImagesResponse
	(*CLIRuntimeRecord)(nil),                           // 4: platform.cli_runtime.v1.CLIRuntimeRecord
	(*CLIVersionSnapshot)(nil),                         // 5: platform.cli_runtime.v1.CLIVersionSnapshot
	(*CLIRuntimeImage)(nil),                            // 6: platform.cli_runtime.v1.CLIRuntimeImage
	(*timestamppb.Timestamp)(nil),                      // 7: google.protobuf.Timestamp
}
var file_platform_cli_runtime_v1_cli_runtime_service_proto_depIdxs = []int32{
	4, // 0: platform.cli_runtime.v1.ListCLIRuntimeRecordsResponse.items:type_name -> platform.cli_runtime.v1.CLIRuntimeRecord
	6, // 1: platform.cli_runtime.v1.GetLatestAvailableCLIRuntimeImagesResponse.items:type_name -> platform.cli_runtime.v1.CLIRuntimeImage
	5, // 2: platform.cli_runtime.v1.CLIRuntimeRecord.version:type_name -> platform.cli_runtime.v1.CLIVersionSnapshot
	6, // 3: platform.cli_runtime.v1.CLIRuntimeRecord.images:type_name -> platform.cli_runtime.v1.CLIRuntimeImage
	7, // 4: platform.cli_runtime.v1.CLIVersionSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: platform.cli_runtime.v1.CLIRuntimeService.ListCLIRuntimeRecords:input_type -> platform.cli_runtime.v1.ListCLIRuntimeRecordsRequest
	2, // 6: platform.cli_runtime.v1.CLIRuntimeService.GetLatestAvailableCLIRuntimeImages:input_type -> platform.cli_runtime.v1.GetLatestAvailableCLIRuntimeImagesRequest
	1, // 7: platform.cli_runtime.v1.CLIRuntimeService.ListCLIRuntimeRecords:output_type -> platform.cli_runtime.v1.ListCLIRuntimeRecordsResponse
	3, // 8: platform.cli_runtime.v1.CLIRuntimeService.GetLatestAvailableCLIRuntimeImages:output_type -> platform.cli_runtime.v1.GetLatestAvailableCLIRuntimeImagesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_platform_cli_runtime_v1_cli_runtime_service_proto_init() }
func file_platform_cli_runtime_v1_cli_runtime_service_proto_init() {
	if File_platform_cli_runtime_v1_cli_runtime_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDesc), len(file_platform_cli_runtime_v1_cli_runtime_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_cli_runtime_v1_cli_runtime_service_proto_goTypes,
		DependencyIndexes: file_platform_cli_runtime_v1_cli_runtime_service_proto_depIdxs,
		MessageInfos:      file_platform_cli_runtime_v1_cli_runtime_service_proto_msgTypes,
	}.Build()
	File_platform_cli_runtime_v1_cli_runtime_service_proto = out.File
	file_platform_cli_runtime_v1_cli_runtime_service_proto_goTypes = nil
	file_platform_cli_runtime_v1_cli_runtime_service_proto_depIdxs = nil
}
