apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: code-code-observability
spec:
  auth:
    strategy: anonymous
  deployment:
    cluster_wide_access: true
    instance_name: kiali
    logger:
      log_format: text
      log_level: info
    namespace: code-code-observability
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    service_type: NodePort
    view_only_mode: true
  external_services:
    custom_dashboards:
      discovery_auto_threshold: 10
      discovery_enabled: "auto"
      enabled: true
      namespace_label: namespace
    grafana:
      enabled: true
      internal_url: http://grafana.code-code-observability.svc.cluster.local:3000/grafana/
      health_check_url: http://grafana.code-code-observability.svc.cluster.local:3000/grafana/api/health
    prometheus:
      url: http://prometheus.code-code-observability.svc.cluster.local:9090
    tracing:
      enabled: true
      health_check_url: http://tempo.code-code-observability.svc.cluster.local:3200/ready
      internal_url: http://tempo.code-code-observability.svc.cluster.local:3200/
      provider: tempo
      tempo_config:
        datasource_uid: tempo
        org_id: "1"
        url_format: grafana
      use_grpc: false
  custom_dashboards:
    - name: kubernetes-resources
      title: Pod Resources
      runtime: Kubernetes
      discoverOn: container_cpu_usage_seconds_total
      items:
        - chart:
            name: CPU Usage
            unit: cores
            spans: 6
            metricName: container_cpu_usage_seconds_total
            dataType: rate
            aggregator: sum
            aggregations:
              - label: pod
                displayName: Pod
              - label: container
                displayName: Container
        - chart:
            name: Memory Working Set
            unit: bytes
            spans: 6
            metricName: container_memory_working_set_bytes
            dataType: raw
            aggregator: sum
            aggregations:
              - label: pod
                displayName: Pod
              - label: container
                displayName: Container
  server:
    node_port: 32031
    web_root: /kiali
    web_schema: http
