apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: code-code
  labels:
    app.kubernetes.io/name: code-code-waypoint
    app.kubernetes.io/component: ambient-waypoint
    app.kubernetes.io/part-of: code-code
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: code-code-infra
  labels:
    app.kubernetes.io/name: code-code-infra-waypoint
    app.kubernetes.io/component: ambient-waypoint
    app.kubernetes.io/part-of: code-code
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: code-code-runs
  labels:
    app.kubernetes.io/name: code-code-runs-waypoint
    app.kubernetes.io/component: ambient-waypoint
    app.kubernetes.io/part-of: code-code
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: code-code-observability
  labels:
    app.kubernetes.io/name: code-code-observability-waypoint
    app.kubernetes.io/component: ambient-waypoint
    app.kubernetes.io/part-of: code-code
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
