apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-provider-service
subjects:
  - kind: ServiceAccount
    name: platform-provider-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-provider-service
