apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: code-code

resources:
  - apprise-api.yaml
  - notification-dispatcher.yaml
  - wecom-callback-adapter.yaml
  - wecom-robot-callback-adapter.yaml
  - ingress.yaml
