apiVersion: v1
kind: Secret
metadata:
  name: notification-apprise-urls
type: Opaque
stringData:
  urls: <enterprise-wechat-webhook-url>
---
apiVersion: v1
kind: Secret
metadata:
  name: wecom-callback
type: Opaque
stringData:
  token: <wecom-callback-token>
  encoding-aes-key: <43-char-encoding-aes-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: wecom-robot-default-callback
type: Opaque
stringData:
  token: <wecom-robot-default-token>
  encoding-aes-key: <43-char-wecom-robot-default-encoding-aes-key>
