// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: model/v1/model.proto

package modelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AliasKind identifies the semantic kind of one model alias.
type AliasKind int32

const (
	AliasKind_ALIAS_KIND_UNSPECIFIED AliasKind = 0
	AliasKind_ALIAS_KIND_STABLE      AliasKind = 1
	AliasKind_ALIAS_KIND_SNAPSHOT    AliasKind = 2
	AliasKind_ALIAS_KIND_BEDROCK     AliasKind = 3
	AliasKind_ALIAS_KIND_VERTEX      AliasKind = 4
)

// Enum value maps for AliasKind.
var (
	AliasKind_name = map[int32]string{
		0: "ALIAS_KIND_UNSPECIFIED",
		1: "ALIAS_KIND_STABLE",
		2: "ALIAS_KIND_SNAPSHOT",
		3: "ALIAS_KIND_BEDROCK",
		4: "ALIAS_KIND_VERTEX",
	}
	AliasKind_value = map[string]int32{
		"ALIAS_KIND_UNSPECIFIED": 0,
		"ALIAS_KIND_STABLE":      1,
		"ALIAS_KIND_SNAPSHOT":    2,
		"ALIAS_KIND_BEDROCK":     3,
		"ALIAS_KIND_VERTEX":      4,
	}
)

func (x AliasKind) Enum() *AliasKind {
	p := new(AliasKind)
	*p = x
	return p
}

func (x AliasKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AliasKind) Descriptor() protoreflect.EnumDescriptor {
	return file_model_v1_model_proto_enumTypes[0].Descriptor()
}

func (AliasKind) Type() protoreflect.EnumType {
	return &file_model_v1_model_proto_enumTypes[0]
}

func (x AliasKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AliasKind.Descriptor instead.
func (AliasKind) EnumDescriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{0}
}

// ModelCapability identifies a capability exposed by one model.
type ModelCapability int32

const (
	ModelCapability_MODEL_CAPABILITY_UNSPECIFIED       ModelCapability = 0
	ModelCapability_MODEL_CAPABILITY_TOOL_CALLING      ModelCapability = 1
	ModelCapability_MODEL_CAPABILITY_STRUCTURED_OUTPUT ModelCapability = 2
	ModelCapability_MODEL_CAPABILITY_IMAGE_INPUT       ModelCapability = 3
	ModelCapability_MODEL_CAPABILITY_STREAMING         ModelCapability = 4
)

// Enum value maps for ModelCapability.
var (
	ModelCapability_name = map[int32]string{
		0: "MODEL_CAPABILITY_UNSPECIFIED",
		1: "MODEL_CAPABILITY_TOOL_CALLING",
		2: "MODEL_CAPABILITY_STRUCTURED_OUTPUT",
		3: "MODEL_CAPABILITY_IMAGE_INPUT",
		4: "MODEL_CAPABILITY_STREAMING",
	}
	ModelCapability_value = map[string]int32{
		"MODEL_CAPABILITY_UNSPECIFIED":       0,
		"MODEL_CAPABILITY_TOOL_CALLING":      1,
		"MODEL_CAPABILITY_STRUCTURED_OUTPUT": 2,
		"MODEL_CAPABILITY_IMAGE_INPUT":       3,
		"MODEL_CAPABILITY_STREAMING":         4,
	}
)

func (x ModelCapability) Enum() *ModelCapability {
	p := new(ModelCapability)
	*p = x
	return p
}

func (x ModelCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_model_v1_model_proto_enumTypes[1].Descriptor()
}

func (ModelCapability) Type() protoreflect.EnumType {
	return &file_model_v1_model_proto_enumTypes[1]
}

func (x ModelCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelCapability.Descriptor instead.
func (ModelCapability) EnumDescriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{1}
}

// ModelShape identifies the request/response surface used to call one model.
type ModelShape int32

const (
	ModelShape_MODEL_SHAPE_UNSPECIFIED        ModelShape = 0
	ModelShape_MODEL_SHAPE_RESPONSES          ModelShape = 1
	ModelShape_MODEL_SHAPE_CHAT_COMPLETIONS   ModelShape = 2
	ModelShape_MODEL_SHAPE_ANTHROPIC_MESSAGES ModelShape = 3
)

// Enum value maps for ModelShape.
var (
	ModelShape_name = map[int32]string{
		0: "MODEL_SHAPE_UNSPECIFIED",
		1: "MODEL_SHAPE_RESPONSES",
		2: "MODEL_SHAPE_CHAT_COMPLETIONS",
		3: "MODEL_SHAPE_ANTHROPIC_MESSAGES",
	}
	ModelShape_value = map[string]int32{
		"MODEL_SHAPE_UNSPECIFIED":        0,
		"MODEL_SHAPE_RESPONSES":          1,
		"MODEL_SHAPE_CHAT_COMPLETIONS":   2,
		"MODEL_SHAPE_ANTHROPIC_MESSAGES": 3,
	}
)

func (x ModelShape) Enum() *ModelShape {
	p := new(ModelShape)
	*p = x
	return p
}

func (x ModelShape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelShape) Descriptor() protoreflect.EnumDescriptor {
	return file_model_v1_model_proto_enumTypes[2].Descriptor()
}

func (ModelShape) Type() protoreflect.EnumType {
	return &file_model_v1_model_proto_enumTypes[2]
}

func (x ModelShape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelShape.Descriptor instead.
func (ModelShape) EnumDescriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{2}
}

// Modality identifies one input or output modality exposed by one model.
type Modality int32

const (
	Modality_MODALITY_UNSPECIFIED Modality = 0
	Modality_MODALITY_TEXT        Modality = 1
	Modality_MODALITY_IMAGE       Modality = 2
	Modality_MODALITY_AUDIO       Modality = 3
	Modality_MODALITY_VIDEO       Modality = 4
)

// Enum value maps for Modality.
var (
	Modality_name = map[int32]string{
		0: "MODALITY_UNSPECIFIED",
		1: "MODALITY_TEXT",
		2: "MODALITY_IMAGE",
		3: "MODALITY_AUDIO",
		4: "MODALITY_VIDEO",
	}
	Modality_value = map[string]int32{
		"MODALITY_UNSPECIFIED": 0,
		"MODALITY_TEXT":        1,
		"MODALITY_IMAGE":       2,
		"MODALITY_AUDIO":       3,
		"MODALITY_VIDEO":       4,
	}
)

func (x Modality) Enum() *Modality {
	p := new(Modality)
	*p = x
	return p
}

func (x Modality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Modality) Descriptor() protoreflect.EnumDescriptor {
	return file_model_v1_model_proto_enumTypes[3].Descriptor()
}

func (Modality) Type() protoreflect.EnumType {
	return &file_model_v1_model_proto_enumTypes[3]
}

func (x Modality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Modality.Descriptor instead.
func (Modality) EnumDescriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{3}
}

// ModelRef references one default model definition by stable identity.
// Canonical identity is vendor_id + model_id.
type ModelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	VendorId      string                 `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRef) Reset() {
	*x = ModelRef{}
	mi := &file_model_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRef) ProtoMessage() {}

func (x *ModelRef) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRef.ProtoReflect.Descriptor instead.
func (*ModelRef) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *ModelRef) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelRef) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

// ModelDefinition describes one default model definition.
type ModelDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ModelId             string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	DisplayName         string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Aliases             []*ModelAlias          `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	ContextWindowTokens int64                  `protobuf:"varint,4,opt,name=context_window_tokens,json=contextWindowTokens,proto3" json:"context_window_tokens,omitempty"`
	MaxOutputTokens     int64                  `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	Capabilities        []ModelCapability      `protobuf:"varint,6,rep,packed,name=capabilities,proto3,enum=model.v1.ModelCapability" json:"capabilities,omitempty"`
	PrimaryShape        ModelShape             `protobuf:"varint,7,opt,name=primary_shape,json=primaryShape,proto3,enum=model.v1.ModelShape" json:"primary_shape,omitempty"`
	SupportedShapes     []ModelShape           `protobuf:"varint,8,rep,packed,name=supported_shapes,json=supportedShapes,proto3,enum=model.v1.ModelShape" json:"supported_shapes,omitempty"`
	InputModalities     []Modality             `protobuf:"varint,9,rep,packed,name=input_modalities,json=inputModalities,proto3,enum=model.v1.Modality" json:"input_modalities,omitempty"`
	OutputModalities    []Modality             `protobuf:"varint,10,rep,packed,name=output_modalities,json=outputModalities,proto3,enum=model.v1.Modality" json:"output_modalities,omitempty"`
	// Model vendor stable identifier aligned with industry APIs
	// (OpenAI owned_by, Gemini publisher prefix).
	// Examples: "openai", "anthropic", "google", "meta", "deepseek".
	VendorId      string `protobuf:"bytes,15,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelDefinition) Reset() {
	*x = ModelDefinition{}
	mi := &file_model_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDefinition) ProtoMessage() {}

func (x *ModelDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDefinition.ProtoReflect.Descriptor instead.
func (*ModelDefinition) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *ModelDefinition) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelDefinition) GetAliases() []*ModelAlias {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ModelDefinition) GetContextWindowTokens() int64 {
	if x != nil {
		return x.ContextWindowTokens
	}
	return 0
}

func (x *ModelDefinition) GetMaxOutputTokens() int64 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *ModelDefinition) GetCapabilities() []ModelCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ModelDefinition) GetPrimaryShape() ModelShape {
	if x != nil {
		return x.PrimaryShape
	}
	return ModelShape_MODEL_SHAPE_UNSPECIFIED
}

func (x *ModelDefinition) GetSupportedShapes() []ModelShape {
	if x != nil {
		return x.SupportedShapes
	}
	return nil
}

func (x *ModelDefinition) GetInputModalities() []Modality {
	if x != nil {
		return x.InputModalities
	}
	return nil
}

func (x *ModelDefinition) GetOutputModalities() []Modality {
	if x != nil {
		return x.OutputModalities
	}
	return nil
}

func (x *ModelDefinition) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

// ModelOverride describes provider-supplied overrides for one default model
// definition.
type ModelOverride struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FieldMask           *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	DisplayName         *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	ContextWindowTokens *int64                 `protobuf:"varint,4,opt,name=context_window_tokens,json=contextWindowTokens,proto3,oneof" json:"context_window_tokens,omitempty"`
	MaxOutputTokens     *int64                 `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3,oneof" json:"max_output_tokens,omitempty"`
	Capabilities        []ModelCapability      `protobuf:"varint,6,rep,packed,name=capabilities,proto3,enum=model.v1.ModelCapability" json:"capabilities,omitempty"`
	PrimaryShape        *ModelShape            `protobuf:"varint,7,opt,name=primary_shape,json=primaryShape,proto3,enum=model.v1.ModelShape,oneof" json:"primary_shape,omitempty"`
	SupportedShapes     []ModelShape           `protobuf:"varint,8,rep,packed,name=supported_shapes,json=supportedShapes,proto3,enum=model.v1.ModelShape" json:"supported_shapes,omitempty"`
	InputModalities     []Modality             `protobuf:"varint,9,rep,packed,name=input_modalities,json=inputModalities,proto3,enum=model.v1.Modality" json:"input_modalities,omitempty"`
	OutputModalities    []Modality             `protobuf:"varint,10,rep,packed,name=output_modalities,json=outputModalities,proto3,enum=model.v1.Modality" json:"output_modalities,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModelOverride) Reset() {
	*x = ModelOverride{}
	mi := &file_model_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelOverride) ProtoMessage() {}

func (x *ModelOverride) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelOverride.ProtoReflect.Descriptor instead.
func (*ModelOverride) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *ModelOverride) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *ModelOverride) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *ModelOverride) GetContextWindowTokens() int64 {
	if x != nil && x.ContextWindowTokens != nil {
		return *x.ContextWindowTokens
	}
	return 0
}

func (x *ModelOverride) GetMaxOutputTokens() int64 {
	if x != nil && x.MaxOutputTokens != nil {
		return *x.MaxOutputTokens
	}
	return 0
}

func (x *ModelOverride) GetCapabilities() []ModelCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ModelOverride) GetPrimaryShape() ModelShape {
	if x != nil && x.PrimaryShape != nil {
		return *x.PrimaryShape
	}
	return ModelShape_MODEL_SHAPE_UNSPECIFIED
}

func (x *ModelOverride) GetSupportedShapes() []ModelShape {
	if x != nil {
		return x.SupportedShapes
	}
	return nil
}

func (x *ModelOverride) GetInputModalities() []Modality {
	if x != nil {
		return x.InputModalities
	}
	return nil
}

func (x *ModelOverride) GetOutputModalities() []Modality {
	if x != nil {
		return x.OutputModalities
	}
	return nil
}

// ResolvedModel describes the effective model after merging the default
// definition with an optional override.
type ResolvedModel struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ModelId             string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	EffectiveDefinition *ModelDefinition       `protobuf:"bytes,2,opt,name=effective_definition,json=effectiveDefinition,proto3" json:"effective_definition,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResolvedModel) Reset() {
	*x = ResolvedModel{}
	mi := &file_model_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedModel) ProtoMessage() {}

func (x *ResolvedModel) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedModel.ProtoReflect.Descriptor instead.
func (*ResolvedModel) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *ResolvedModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ResolvedModel) GetEffectiveDefinition() *ModelDefinition {
	if x != nil {
		return x.EffectiveDefinition
	}
	return nil
}

// ModelAlias describes an alternate model identifier.
type ModelAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AliasKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=model.v1.AliasKind" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelAlias) Reset() {
	*x = ModelAlias{}
	mi := &file_model_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelAlias) ProtoMessage() {}

func (x *ModelAlias) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelAlias.ProtoReflect.Descriptor instead.
func (*ModelAlias) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *ModelAlias) GetKind() AliasKind {
	if x != nil {
		return x.Kind
	}
	return AliasKind_ALIAS_KIND_UNSPECIFIED
}

func (x *ModelAlias) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_model_v1_model_proto protoreflect.FileDescriptor

const file_model_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x14model/v1/model.proto\x12\bmodel.v1\x1a google/protobuf/field_mask.proto\"B\n" +
	"\bModelRef\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\tR\bvendorId\"\xb8\x05\n" +
	"\x0fModelDefinition\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12.\n" +
	"\aaliases\x18\x03 \x03(\v2\x14.model.v1.ModelAliasR\aaliases\x122\n" +
	"\x15context_window_tokens\x18\x04 \x01(\x03R\x13contextWindowTokens\x12*\n" +
	"\x11max_output_tokens\x18\x05 \x01(\x03R\x0fmaxOutputTokens\x12=\n" +
	"\fcapabilities\x18\x06 \x03(\x0e2\x19.model.v1.ModelCapabilityR\fcapabilities\x129\n" +
	"\rprimary_shape\x18\a \x01(\x0e2\x14.model.v1.ModelShapeR\fprimaryShape\x12?\n" +
	"\x10supported_shapes\x18\b \x03(\x0e2\x14.model.v1.ModelShapeR\x0fsupportedShapes\x12=\n" +
	"\x10input_modalities\x18\t \x03(\x0e2\x12.model.v1.ModalityR\x0finputModalities\x12?\n" +
	"\x11output_modalities\x18\n" +
	" \x03(\x0e2\x12.model.v1.ModalityR\x10outputModalities\x12\x1b\n" +
	"\tvendor_id\x18\x0f \x01(\tR\bvendorIdJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x10\x10\x11J\x04\b\x11\x10\x12J\x04\b\x12\x10\x13R\x10knowledge_cutoffR\x0ftraining_cutoffR\apricingR\tlifecycleR\tfamily_idR\vdescriptionR\x06labels\"\x90\x06\n" +
	"\rModelOverride\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x127\n" +
	"\x15context_window_tokens\x18\x04 \x01(\x03H\x01R\x13contextWindowTokens\x88\x01\x01\x12/\n" +
	"\x11max_output_tokens\x18\x05 \x01(\x03H\x02R\x0fmaxOutputTokens\x88\x01\x01\x12=\n" +
	"\fcapabilities\x18\x06 \x03(\x0e2\x19.model.v1.ModelCapabilityR\fcapabilities\x12>\n" +
	"\rprimary_shape\x18\a \x01(\x0e2\x14.model.v1.ModelShapeH\x03R\fprimaryShape\x88\x01\x01\x12?\n" +
	"\x10supported_shapes\x18\b \x03(\x0e2\x14.model.v1.ModelShapeR\x0fsupportedShapes\x12=\n" +
	"\x10input_modalities\x18\t \x03(\x0e2\x12.model.v1.ModalityR\x0finputModalities\x12?\n" +
	"\x11output_modalities\x18\n" +
	" \x03(\x0e2\x12.model.v1.ModalityR\x10outputModalitiesB\x0f\n" +
	"\r_display_nameB\x18\n" +
	"\x16_context_window_tokensB\x14\n" +
	"\x12_max_output_tokensB\x10\n" +
	"\x0e_primary_shapeJ\x04\b\x03\x10\x04J\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11J\x04\b\x11\x10\x12J\x04\b\x12\x10\x13R\aaliasesR\x10knowledge_cutoffR\x0ftraining_cutoffR\apricingR\tlifecycleR\tvendor_idR\tfamily_idR\vdescriptionR\x06labels\"x\n" +
	"\rResolvedModel\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12L\n" +
	"\x14effective_definition\x18\x02 \x01(\v2\x19.model.v1.ModelDefinitionR\x13effectiveDefinition\"K\n" +
	"\n" +
	"ModelAlias\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.model.v1.AliasKindR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*\x86\x01\n" +
	"\tAliasKind\x12\x1a\n" +
	"\x16ALIAS_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ALIAS_KIND_STABLE\x10\x01\x12\x17\n" +
	"\x13ALIAS_KIND_SNAPSHOT\x10\x02\x12\x16\n" +
	"\x12ALIAS_KIND_BEDROCK\x10\x03\x12\x15\n" +
	"\x11ALIAS_KIND_VERTEX\x10\x04*\xc0\x01\n" +
	"\x0fModelCapability\x12 \n" +
	"\x1cMODEL_CAPABILITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dMODEL_CAPABILITY_TOOL_CALLING\x10\x01\x12&\n" +
	"\"MODEL_CAPABILITY_STRUCTURED_OUTPUT\x10\x02\x12 \n" +
	"\x1cMODEL_CAPABILITY_IMAGE_INPUT\x10\x03\x12\x1e\n" +
	"\x1aMODEL_CAPABILITY_STREAMING\x10\x04*\x8a\x01\n" +
	"\n" +
	"ModelShape\x12\x1b\n" +
	"\x17MODEL_SHAPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MODEL_SHAPE_RESPONSES\x10\x01\x12 \n" +
	"\x1cMODEL_SHAPE_CHAT_COMPLETIONS\x10\x02\x12\"\n" +
	"\x1eMODEL_SHAPE_ANTHROPIC_MESSAGES\x10\x03*s\n" +
	"\bModality\x12\x18\n" +
	"\x14MODALITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMODALITY_TEXT\x10\x01\x12\x12\n" +
	"\x0eMODALITY_IMAGE\x10\x02\x12\x12\n" +
	"\x0eMODALITY_AUDIO\x10\x03\x12\x12\n" +
	"\x0eMODALITY_VIDEO\x10\x04B1Z/code-code.internal/go-contract/model/v1;modelv1b\x06proto3"

var (
	file_model_v1_model_proto_rawDescOnce sync.Once
	file_model_v1_model_proto_rawDescData []byte
)

func file_model_v1_model_proto_rawDescGZIP() []byte {
	file_model_v1_model_proto_rawDescOnce.Do(func() {
		file_model_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_v1_model_proto_rawDesc), len(file_model_v1_model_proto_rawDesc)))
	})
	return file_model_v1_model_proto_rawDescData
}

var file_model_v1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_model_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_model_v1_model_proto_goTypes = []any{
	(AliasKind)(0),                // 0: model.v1.AliasKind
	(ModelCapability)(0),          // 1: model.v1.ModelCapability
	(ModelShape)(0),               // 2: model.v1.ModelShape
	(Modality)(0),                 // 3: model.v1.Modality
	(*ModelRef)(nil),              // 4: model.v1.ModelRef
	(*ModelDefinition)(nil),       // 5: model.v1.ModelDefinition
	(*ModelOverride)(nil),         // 6: model.v1.ModelOverride
	(*ResolvedModel)(nil),         // 7: model.v1.ResolvedModel
	(*ModelAlias)(nil),            // 8: model.v1.ModelAlias
	(*fieldmaskpb.FieldMask)(nil), // 9: google.protobuf.FieldMask
}
var file_model_v1_model_proto_depIdxs = []int32{
	8,  // 0: model.v1.ModelDefinition.aliases:type_name -> model.v1.ModelAlias
	1,  // 1: model.v1.ModelDefinition.capabilities:type_name -> model.v1.ModelCapability
	2,  // 2: model.v1.ModelDefinition.primary_shape:type_name -> model.v1.ModelShape
	2,  // 3: model.v1.ModelDefinition.supported_shapes:type_name -> model.v1.ModelShape
	3,  // 4: model.v1.ModelDefinition.input_modalities:type_name -> model.v1.Modality
	3,  // 5: model.v1.ModelDefinition.output_modalities:type_name -> model.v1.Modality
	9,  // 6: model.v1.ModelOverride.field_mask:type_name -> google.protobuf.FieldMask
	1,  // 7: model.v1.ModelOverride.capabilities:type_name -> model.v1.ModelCapability
	2,  // 8: model.v1.ModelOverride.primary_shape:type_name -> model.v1.ModelShape
	2,  // 9: model.v1.ModelOverride.supported_shapes:type_name -> model.v1.ModelShape
	3,  // 10: model.v1.ModelOverride.input_modalities:type_name -> model.v1.Modality
	3,  // 11: model.v1.ModelOverride.output_modalities:type_name -> model.v1.Modality
	5,  // 12: model.v1.ResolvedModel.effective_definition:type_name -> model.v1.ModelDefinition
	0,  // 13: model.v1.ModelAlias.kind:type_name -> model.v1.AliasKind
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_model_v1_model_proto_init() }
func file_model_v1_model_proto_init() {
	if File_model_v1_model_proto != nil {
		return
	}
	file_model_v1_model_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_v1_model_proto_rawDesc), len(file_model_v1_model_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_v1_model_proto_goTypes,
		DependencyIndexes: file_model_v1_model_proto_depIdxs,
		EnumInfos:         file_model_v1_model_proto_enumTypes,
		MessageInfos:      file_model_v1_model_proto_msgTypes,
	}.Build()
	File_model_v1_model_proto = out.File
	file_model_v1_model_proto_goTypes = nil
	file_model_v1_model_proto_depIdxs = nil
}
