// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/egress/v1/egress_service.proto

package egressservicev1connect

import (
	v11 "code-code.internal/go-contract/platform/egress/v1"
	v1 "code-code.internal/go-contract/platform/management/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EgressServiceName is the fully-qualified name of the EgressService service.
	EgressServiceName = "platform.egress.v1.EgressService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EgressServiceListEgressPoliciesProcedure is the fully-qualified name of the EgressService's
	// ListEgressPolicies RPC.
	EgressServiceListEgressPoliciesProcedure = "/platform.egress.v1.EgressService/ListEgressPolicies"
	// EgressServiceUpdateEgressPolicyProcedure is the fully-qualified name of the EgressService's
	// UpdateEgressPolicy RPC.
	EgressServiceUpdateEgressPolicyProcedure = "/platform.egress.v1.EgressService/UpdateEgressPolicy"
	// EgressServiceGetEgressRuntimePolicyProcedure is the fully-qualified name of the EgressService's
	// GetEgressRuntimePolicy RPC.
	EgressServiceGetEgressRuntimePolicyProcedure = "/platform.egress.v1.EgressService/GetEgressRuntimePolicy"
)

// EgressServiceClient is a client for the platform.egress.v1.EgressService service.
type EgressServiceClient interface {
	ListEgressPolicies(context.Context, *v1.ListEgressPoliciesRequest) (*v1.ListEgressPoliciesResponse, error)
	UpdateEgressPolicy(context.Context, *v1.UpdateEgressPolicyRequest) (*v1.UpdateEgressPolicyResponse, error)
	GetEgressRuntimePolicy(context.Context, *v11.GetEgressRuntimePolicyRequest) (*v11.GetEgressRuntimePolicyResponse, error)
}

// NewEgressServiceClient constructs a client for the platform.egress.v1.EgressService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEgressServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EgressServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	egressServiceMethods := v11.File_platform_egress_v1_egress_service_proto.Services().ByName("EgressService").Methods()
	return &egressServiceClient{
		listEgressPolicies: connect.NewClient[v1.ListEgressPoliciesRequest, v1.ListEgressPoliciesResponse](
			httpClient,
			baseURL+EgressServiceListEgressPoliciesProcedure,
			connect.WithSchema(egressServiceMethods.ByName("ListEgressPolicies")),
			connect.WithClientOptions(opts...),
		),
		updateEgressPolicy: connect.NewClient[v1.UpdateEgressPolicyRequest, v1.UpdateEgressPolicyResponse](
			httpClient,
			baseURL+EgressServiceUpdateEgressPolicyProcedure,
			connect.WithSchema(egressServiceMethods.ByName("UpdateEgressPolicy")),
			connect.WithClientOptions(opts...),
		),
		getEgressRuntimePolicy: connect.NewClient[v11.GetEgressRuntimePolicyRequest, v11.GetEgressRuntimePolicyResponse](
			httpClient,
			baseURL+EgressServiceGetEgressRuntimePolicyProcedure,
			connect.WithSchema(egressServiceMethods.ByName("GetEgressRuntimePolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// egressServiceClient implements EgressServiceClient.
type egressServiceClient struct {
	listEgressPolicies     *connect.Client[v1.ListEgressPoliciesRequest, v1.ListEgressPoliciesResponse]
	updateEgressPolicy     *connect.Client[v1.UpdateEgressPolicyRequest, v1.UpdateEgressPolicyResponse]
	getEgressRuntimePolicy *connect.Client[v11.GetEgressRuntimePolicyRequest, v11.GetEgressRuntimePolicyResponse]
}

// ListEgressPolicies calls platform.egress.v1.EgressService.ListEgressPolicies.
func (c *egressServiceClient) ListEgressPolicies(ctx context.Context, req *v1.ListEgressPoliciesRequest) (*v1.ListEgressPoliciesResponse, error) {
	response, err := c.listEgressPolicies.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateEgressPolicy calls platform.egress.v1.EgressService.UpdateEgressPolicy.
func (c *egressServiceClient) UpdateEgressPolicy(ctx context.Context, req *v1.UpdateEgressPolicyRequest) (*v1.UpdateEgressPolicyResponse, error) {
	response, err := c.updateEgressPolicy.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetEgressRuntimePolicy calls platform.egress.v1.EgressService.GetEgressRuntimePolicy.
func (c *egressServiceClient) GetEgressRuntimePolicy(ctx context.Context, req *v11.GetEgressRuntimePolicyRequest) (*v11.GetEgressRuntimePolicyResponse, error) {
	response, err := c.getEgressRuntimePolicy.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// EgressServiceHandler is an implementation of the platform.egress.v1.EgressService service.
type EgressServiceHandler interface {
	ListEgressPolicies(context.Context, *v1.ListEgressPoliciesRequest) (*v1.ListEgressPoliciesResponse, error)
	UpdateEgressPolicy(context.Context, *v1.UpdateEgressPolicyRequest) (*v1.UpdateEgressPolicyResponse, error)
	GetEgressRuntimePolicy(context.Context, *v11.GetEgressRuntimePolicyRequest) (*v11.GetEgressRuntimePolicyResponse, error)
}

// NewEgressServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEgressServiceHandler(svc EgressServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	egressServiceMethods := v11.File_platform_egress_v1_egress_service_proto.Services().ByName("EgressService").Methods()
	egressServiceListEgressPoliciesHandler := connect.NewUnaryHandlerSimple(
		EgressServiceListEgressPoliciesProcedure,
		svc.ListEgressPolicies,
		connect.WithSchema(egressServiceMethods.ByName("ListEgressPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	egressServiceUpdateEgressPolicyHandler := connect.NewUnaryHandlerSimple(
		EgressServiceUpdateEgressPolicyProcedure,
		svc.UpdateEgressPolicy,
		connect.WithSchema(egressServiceMethods.ByName("UpdateEgressPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	egressServiceGetEgressRuntimePolicyHandler := connect.NewUnaryHandlerSimple(
		EgressServiceGetEgressRuntimePolicyProcedure,
		svc.GetEgressRuntimePolicy,
		connect.WithSchema(egressServiceMethods.ByName("GetEgressRuntimePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.egress.v1.EgressService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EgressServiceListEgressPoliciesProcedure:
			egressServiceListEgressPoliciesHandler.ServeHTTP(w, r)
		case EgressServiceUpdateEgressPolicyProcedure:
			egressServiceUpdateEgressPolicyHandler.ServeHTTP(w, r)
		case EgressServiceGetEgressRuntimePolicyProcedure:
			egressServiceGetEgressRuntimePolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEgressServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEgressServiceHandler struct{}

func (UnimplementedEgressServiceHandler) ListEgressPolicies(context.Context, *v1.ListEgressPoliciesRequest) (*v1.ListEgressPoliciesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.egress.v1.EgressService.ListEgressPolicies is not implemented"))
}

func (UnimplementedEgressServiceHandler) UpdateEgressPolicy(context.Context, *v1.UpdateEgressPolicyRequest) (*v1.UpdateEgressPolicyResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.egress.v1.EgressService.UpdateEgressPolicy is not implemented"))
}

func (UnimplementedEgressServiceHandler) GetEgressRuntimePolicy(context.Context, *v11.GetEgressRuntimePolicyRequest) (*v11.GetEgressRuntimePolicyResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.egress.v1.EgressService.GetEgressRuntimePolicy is not implemented"))
}
